export const ETCBC_BOOK_MAP: Record<string, string> = {
	genesis: 'Genesis',
	exodus: 'Exodus',
	leviticus: 'Leviticus',
	numbers: 'Numbers',
	deuteronomy: 'Deuteronomy',

	joshua: 'Joshua',
	judges: 'Judges',
	ruth: 'Ruth',

	'1-samuel': '1_Samuel',
	'2-samuel': '2_Samuel',
	'1-kings': '1_Kings',
	'2-kings': '2_Kings',
	'1-chronicles': '1_Chronicles',
	'2-chronicles': '2_Chronicles',

	ezra: 'Ezra',
	nehemiah: 'Nehemiah',
	esther: 'Esther',
	job: 'Job',
	psalms: 'Psalms',
	proverbs: 'Proverbs',
	ecclesiastes: 'Ecclesiastes',
	'song-of-songs': 'Song_of_songs',

	isaiah: 'Isaiah',
	jeremiah: 'Jeremiah',
	lamentations: 'Lamentations',
	ezekiel: 'Ezekiel',
	daniel: 'Daniel',
	hosea: 'Hosea',
	joel: 'Joel',
	amos: 'Amos',
	obadiah: 'Obadiah',
	jonah: 'Jonah',
	micah: 'Micah',
	nahum: 'Nahum',
	habakkuk: 'Habakkuk',
	zephaniah: 'Zephaniah',
	haggai: 'Haggai',
	zechariah: 'Zechariah',
	malachi: 'Malachi',
}
