export const letters = [
	{
		char: 'אַ',
		nameAudio: '/audio/name-alef-patach.mp3',
		soundAudio: '/audio/sound-alef-a.mp3',
	},
	{
		char: 'אָ',
		nameAudio: '/audio/name-alef-qamats.mp3',
		soundAudio: '/audio/sound-alef-a-long.mp3',
	},
	{
		char: 'אֶ',
		nameAudio: '/audio/name-alef-segol.mp3',
		soundAudio: '/audio/sound-alef-e.mp3',
	},
	{
		char: 'אֵ',
		nameAudio: '/audio/name-alef-tsere.mp3',
		soundAudio: '/audio/sound-alef-e-long.mp3',
	},
	{
		char: 'אִ',
		nameAudio: '/audio/name-alef-hiriq.mp3',
		soundAudio: '/audio/sound-alef-i.mp3',
	},
	{
		char: 'אֻ',
		nameAudio: '/audio/name-alef-qubutz.mp3',
		soundAudio: '/audio/sound-alef-u-short.mp3',
	},
	{
		char: 'אֹ',
		nameAudio: '/audio/name-alef-holam.mp3',
		soundAudio: '/audio/sound-alef-o.mp3',
	},
	{
		char: 'אְ',
		nameAudio: '/audio/name-alef-shva.mp3',
		soundAudio: '/audio/sound-alef-silent.mp3',
	},
	{
		char: 'אּ',
		nameAudio: '/audio/name-alef-dagesh.mp3',
		soundAudio: '/audio/sound-alef-emph.mp3',
	},
	{
		char: 'אֲ',
		nameAudio: '/audio/name-alef-chataf-patach.mp3',
		soundAudio: '/audio/sound-alef-a-reduced.mp3',
	},
	{
		char: 'אֱ',
		nameAudio: '/audio/name-alef-chataf-segol.mp3',
		soundAudio: '/audio/sound-alef-e-reduced.mp3',
	},
	{
		char: 'אֳ',
		nameAudio: '/audio/name-alef-chataf-qamats.mp3',
		soundAudio: '/audio/sound-alef-o-reduced.mp3',
	},
	{
		char: 'אִי',
		nameAudio: '/audio/name-alef-hiriq-yod.mp3',
		soundAudio: '/audio/sound-alef-i-long.mp3',
	},
	{
		char: 'אֵי',
		nameAudio: '/audio/name-alef-tsere-yod.mp3',
		soundAudio: '/audio/sound-alef-ei.mp3',
	},
	{
		char: 'אֶי',
		nameAudio: '/audio/name-alef-segol-yod.mp3',
		soundAudio: '/audio/sound-alef-ei-segol.mp3',
	},
	{
		char: 'א',
		nameAudio: '/audio/name-alef-base.mp3',
		soundAudio: '/audio/sound-alef-base.mp3',
		category: 'base',
	},
	{
		char: 'בַ',
		nameAudio: '/audio/name-vet-patach.mp3',
		soundAudio: '/audio/sound-vet-a.mp3',
	},
	{
		char: 'בָ',
		nameAudio: '/audio/name-vet-qamats.mp3',
		soundAudio: '/audio/sound-vet-a-long.mp3',
	},
	{
		char: 'בֶ',
		nameAudio: '/audio/name-vet-segol.mp3',
		soundAudio: '/audio/sound-vet-e.mp3',
	},
	{
		char: 'בֵ',
		nameAudio: '/audio/name-vet-tsere.mp3',
		soundAudio: '/audio/sound-vet-e-long.mp3',
	},
	{
		char: 'בִ',
		nameAudio: '/audio/name-vet-hiriq.mp3',
		soundAudio: '/audio/sound-vet-i.mp3',
	},
	{
		char: 'בֻ',
		nameAudio: '/audio/name-vet-qubutz.mp3',
		soundAudio: '/audio/sound-vet-u-short.mp3',
	},
	{
		char: 'בֹ',
		nameAudio: '/audio/name-vet-holam.mp3',
		soundAudio: '/audio/sound-vet-o.mp3',
	},
	{
		char: 'בְ',
		nameAudio: '/audio/name-vet-shva.mp3',
		soundAudio: '/audio/sound-vet-silent.mp3',
	},
	{
		char: 'בּ',
		nameAudio: '/audio/name-vet-dagesh.mp3',
		soundAudio: '/audio/sound-vet-emph.mp3',
	},
	{
		char: 'בֲ',
		nameAudio: '/audio/name-vet-chataf-patach.mp3',
		soundAudio: '/audio/sound-vet-a-reduced.mp3',
	},
	{
		char: 'בֱ',
		nameAudio: '/audio/name-vet-chataf-segol.mp3',
		soundAudio: '/audio/sound-vet-e-reduced.mp3',
	},
	{
		char: 'בֳ',
		nameAudio: '/audio/name-vet-chataf-qamats.mp3',
		soundAudio: '/audio/sound-vet-o-reduced.mp3',
	},
	{
		char: 'בִי',
		nameAudio: '/audio/name-vet-hiriq-yod.mp3',
		soundAudio: '/audio/sound-vet-i-long.mp3',
	},
	{
		char: 'בֵי',
		nameAudio: '/audio/name-vet-tsere-yod.mp3',
		soundAudio: '/audio/sound-vet-ei.mp3',
	},
	{
		char: 'בֶי',
		nameAudio: '/audio/name-vet-segol-yod.mp3',
		soundAudio: '/audio/sound-vet-ei-segol.mp3',
	},
	{
		char: 'ב',
		nameAudio: '/audio/name-vet-base.mp3',
		soundAudio: '/audio/sound-vet-base.mp3',
		category: 'base',
	},
	{
		char: 'בַּ',
		nameAudio: '/audio/name-bet-patach.mp3',
		soundAudio: '/audio/sound-bet-a.mp3',
	},
	{
		char: 'בָּ',
		nameAudio: '/audio/name-bet-qamats.mp3',
		soundAudio: '/audio/sound-bet-a-long.mp3',
	},
	{
		char: 'בֶּ',
		nameAudio: '/audio/name-bet-segol.mp3',
		soundAudio: '/audio/sound-bet-e.mp3',
	},
	{
		char: 'בֵּ',
		nameAudio: '/audio/name-bet-tsere.mp3',
		soundAudio: '/audio/sound-bet-e-long.mp3',
	},
	{
		char: 'בִּ',
		nameAudio: '/audio/name-bet-hiriq.mp3',
		soundAudio: '/audio/sound-bet-i.mp3',
	},
	{
		char: 'בֻּ',
		nameAudio: '/audio/name-bet-qubutz.mp3',
		soundAudio: '/audio/sound-bet-u-short.mp3',
	},
	{
		char: 'בֹּ',
		nameAudio: '/audio/name-bet-holam.mp3',
		soundAudio: '/audio/sound-bet-o.mp3',
	},
	{
		char: 'בְּ',
		nameAudio: '/audio/name-bet-shva.mp3',
		soundAudio: '/audio/sound-bet-silent.mp3',
	},
	{
		char: 'בּּ',
		nameAudio: '/audio/name-bet-dagesh.mp3',
		soundAudio: '/audio/sound-bet-emph.mp3',
	},
	{
		char: 'בֲּ',
		nameAudio: '/audio/name-bet-chataf-patach.mp3',
		soundAudio: '/audio/sound-bet-a-reduced.mp3',
	},
	{
		char: 'בֱּ',
		nameAudio: '/audio/name-bet-chataf-segol.mp3',
		soundAudio: '/audio/sound-bet-e-reduced.mp3',
	},
	{
		char: 'בֳּ',
		nameAudio: '/audio/name-bet-chataf-qamats.mp3',
		soundAudio: '/audio/sound-bet-o-reduced.mp3',
	},
	{
		char: 'בִּי',
		nameAudio: '/audio/name-bet-hiriq-yod.mp3',
		soundAudio: '/audio/sound-bet-i-long.mp3',
	},
	{
		char: 'בֵּי',
		nameAudio: '/audio/name-bet-tsere-yod.mp3',
		soundAudio: '/audio/sound-bet-ei.mp3',
	},
	{
		char: 'בֶּי',
		nameAudio: '/audio/name-bet-segol-yod.mp3',
		soundAudio: '/audio/sound-bet-ei-segol.mp3',
	},
	{
		char: 'בּ',
		nameAudio: '/audio/name-bet-base.mp3',
		soundAudio: '/audio/sound-bet-base.mp3',
		category: 'base',
	},
	{
		char: 'גַ',
		nameAudio: '/audio/name-gimel-patach.mp3',
		soundAudio: '/audio/sound-gimel-a.mp3',
	},
	{
		char: 'גָ',
		nameAudio: '/audio/name-gimel-qamats.mp3',
		soundAudio: '/audio/sound-gimel-a-long.mp3',
	},
	{
		char: 'גֶ',
		nameAudio: '/audio/name-gimel-segol.mp3',
		soundAudio: '/audio/sound-gimel-e.mp3',
	},
	{
		char: 'גֵ',
		nameAudio: '/audio/name-gimel-tsere.mp3',
		soundAudio: '/audio/sound-gimel-e-long.mp3',
	},
	{
		char: 'גִ',
		nameAudio: '/audio/name-gimel-hiriq.mp3',
		soundAudio: '/audio/sound-gimel-i.mp3',
	},
	{
		char: 'גֻ',
		nameAudio: '/audio/name-gimel-qubutz.mp3',
		soundAudio: '/audio/sound-gimel-u-short.mp3',
	},
	{
		char: 'גֹ',
		nameAudio: '/audio/name-gimel-holam.mp3',
		soundAudio: '/audio/sound-gimel-o.mp3',
	},
	{
		char: 'גְ',
		nameAudio: '/audio/name-gimel-shva.mp3',
		soundAudio: '/audio/sound-gimel-silent.mp3',
	},
	{
		char: 'גּ',
		nameAudio: '/audio/name-gimel-dagesh.mp3',
		soundAudio: '/audio/sound-gimel-emph.mp3',
	},
	{
		char: 'גֲ',
		nameAudio: '/audio/name-gimel-chataf-patach.mp3',
		soundAudio: '/audio/sound-gimel-a-reduced.mp3',
	},
	{
		char: 'גֱ',
		nameAudio: '/audio/name-gimel-chataf-segol.mp3',
		soundAudio: '/audio/sound-gimel-e-reduced.mp3',
	},
	{
		char: 'גֳ',
		nameAudio: '/audio/name-gimel-chataf-qamats.mp3',
		soundAudio: '/audio/sound-gimel-o-reduced.mp3',
	},
	{
		char: 'גִי',
		nameAudio: '/audio/name-gimel-hiriq-yod.mp3',
		soundAudio: '/audio/sound-gimel-i-long.mp3',
	},
	{
		char: 'גֵי',
		nameAudio: '/audio/name-gimel-tsere-yod.mp3',
		soundAudio: '/audio/sound-gimel-ei.mp3',
	},
	{
		char: 'גֶי',
		nameAudio: '/audio/name-gimel-segol-yod.mp3',
		soundAudio: '/audio/sound-gimel-ei-segol.mp3',
	},
	{
		char: 'ג',
		nameAudio: '/audio/name-gimel-base.mp3',
		soundAudio: '/audio/sound-gimel-base.mp3',
		category: 'base',
	},
	{
		char: 'דַ',
		nameAudio: '/audio/name-dalet-patach.mp3',
		soundAudio: '/audio/sound-dalet-a.mp3',
	},
	{
		char: 'דָ',
		nameAudio: '/audio/name-dalet-qamats.mp3',
		soundAudio: '/audio/sound-dalet-a-long.mp3',
	},
	{
		char: 'דֶ',
		nameAudio: '/audio/name-dalet-segol.mp3',
		soundAudio: '/audio/sound-dalet-e.mp3',
	},
	{
		char: 'דֵ',
		nameAudio: '/audio/name-dalet-tsere.mp3',
		soundAudio: '/audio/sound-dalet-e-long.mp3',
	},
	{
		char: 'דִ',
		nameAudio: '/audio/name-dalet-hiriq.mp3',
		soundAudio: '/audio/sound-dalet-i.mp3',
	},
	{
		char: 'דֻ',
		nameAudio: '/audio/name-dalet-qubutz.mp3',
		soundAudio: '/audio/sound-dalet-u-short.mp3',
	},
	{
		char: 'דֹ',
		nameAudio: '/audio/name-dalet-holam.mp3',
		soundAudio: '/audio/sound-dalet-o.mp3',
	},
	{
		char: 'דְ',
		nameAudio: '/audio/name-dalet-shva.mp3',
		soundAudio: '/audio/sound-dalet-silent.mp3',
	},
	{
		char: 'דּ',
		nameAudio: '/audio/name-dalet-dagesh.mp3',
		soundAudio: '/audio/sound-dalet-emph.mp3',
	},
	{
		char: 'דֲ',
		nameAudio: '/audio/name-dalet-chataf-patach.mp3',
		soundAudio: '/audio/sound-dalet-a-reduced.mp3',
	},
	{
		char: 'דֱ',
		nameAudio: '/audio/name-dalet-chataf-segol.mp3',
		soundAudio: '/audio/sound-dalet-e-reduced.mp3',
	},
	{
		char: 'דֳ',
		nameAudio: '/audio/name-dalet-chataf-qamats.mp3',
		soundAudio: '/audio/sound-dalet-o-reduced.mp3',
	},
	{
		char: 'דִי',
		nameAudio: '/audio/name-dalet-hiriq-yod.mp3',
		soundAudio: '/audio/sound-dalet-i-long.mp3',
	},
	{
		char: 'דֵי',
		nameAudio: '/audio/name-dalet-tsere-yod.mp3',
		soundAudio: '/audio/sound-dalet-ei.mp3',
	},
	{
		char: 'דֶי',
		nameAudio: '/audio/name-dalet-segol-yod.mp3',
		soundAudio: '/audio/sound-dalet-ei-segol.mp3',
	},
	{
		char: 'ד',
		nameAudio: '/audio/name-dalet-base.mp3',
		soundAudio: '/audio/sound-dalet-base.mp3',
		category: 'base',
	},
	{
		char: 'הַ',
		nameAudio: '/audio/name-he-patach.mp3',
		soundAudio: '/audio/sound-he-a.mp3',
	},
	{
		char: 'הָ',
		nameAudio: '/audio/name-he-qamats.mp3',
		soundAudio: '/audio/sound-he-a-long.mp3',
	},
	{
		char: 'הֶ',
		nameAudio: '/audio/name-he-segol.mp3',
		soundAudio: '/audio/sound-he-e.mp3',
	},
	{
		char: 'הֵ',
		nameAudio: '/audio/name-he-tsere.mp3',
		soundAudio: '/audio/sound-he-e-long.mp3',
	},
	{
		char: 'הִ',
		nameAudio: '/audio/name-he-hiriq.mp3',
		soundAudio: '/audio/sound-he-i.mp3',
	},
	{
		char: 'הֻ',
		nameAudio: '/audio/name-he-qubutz.mp3',
		soundAudio: '/audio/sound-he-u-short.mp3',
	},
	{
		char: 'הֹ',
		nameAudio: '/audio/name-he-holam.mp3',
		soundAudio: '/audio/sound-he-o.mp3',
	},
	{
		char: 'הְ',
		nameAudio: '/audio/name-he-shva.mp3',
		soundAudio: '/audio/sound-he-silent.mp3',
	},
	{
		char: 'הּ',
		nameAudio: '/audio/name-he-dagesh.mp3',
		soundAudio: '/audio/sound-he-emph.mp3',
	},
	{
		char: 'הֲ',
		nameAudio: '/audio/name-he-chataf-patach.mp3',
		soundAudio: '/audio/sound-he-a-reduced.mp3',
	},
	{
		char: 'הֱ',
		nameAudio: '/audio/name-he-chataf-segol.mp3',
		soundAudio: '/audio/sound-he-e-reduced.mp3',
	},
	{
		char: 'הֳ',
		nameAudio: '/audio/name-he-chataf-qamats.mp3',
		soundAudio: '/audio/sound-he-o-reduced.mp3',
	},
	{
		char: 'הִי',
		nameAudio: '/audio/name-he-hiriq-yod.mp3',
		soundAudio: '/audio/sound-he-i-long.mp3',
	},
	{
		char: 'הֵי',
		nameAudio: '/audio/name-he-tsere-yod.mp3',
		soundAudio: '/audio/sound-he-ei.mp3',
	},
	{
		char: 'הֶי',
		nameAudio: '/audio/name-he-segol-yod.mp3',
		soundAudio: '/audio/sound-he-ei-segol.mp3',
	},
	{
		char: 'ה',
		nameAudio: '/audio/name-he-base.mp3',
		soundAudio: '/audio/sound-he-base.mp3',
		category: 'base',
	},
	{
		char: 'וַ',
		nameAudio: '/audio/name-vav-patach.mp3',
		soundAudio: '/audio/sound-vav-a.mp3',
	},
	{
		char: 'וָ',
		nameAudio: '/audio/name-vav-qamats.mp3',
		soundAudio: '/audio/sound-vav-a-long.mp3',
	},
	{
		char: 'וֶ',
		nameAudio: '/audio/name-vav-segol.mp3',
		soundAudio: '/audio/sound-vav-e.mp3',
	},
	{
		char: 'וֵ',
		nameAudio: '/audio/name-vav-tsere.mp3',
		soundAudio: '/audio/sound-vav-e-long.mp3',
	},
	{
		char: 'וִ',
		nameAudio: '/audio/name-vav-hiriq.mp3',
		soundAudio: '/audio/sound-vav-i.mp3',
	},
	{
		char: 'וֻ',
		nameAudio: '/audio/name-vav-qubutz.mp3',
		soundAudio: '/audio/sound-vav-u-short.mp3',
	},
	{
		char: 'וֹ',
		nameAudio: '/audio/name-vav-holam.mp3',
		soundAudio: '/audio/sound-vav-o.mp3',
	},
	{
		char: 'וְ',
		nameAudio: '/audio/name-vav-shva.mp3',
		soundAudio: '/audio/sound-vav-silent.mp3',
	},
	{
		char: 'וּ',
		nameAudio: '/audio/name-vav-dagesh.mp3',
		soundAudio: '/audio/sound-vav-emph.mp3',
	},
	{
		char: 'וּ',
		nameAudio: '/audio/name-shuruk.mp3',
		soundAudio: '/audio/sound-vav-u.mp3',
	},
	{
		char: 'וֹ',
		nameAudio: '/audio/name-holam-male.mp3',
		soundAudio: '/audio/sound-vav-o-long.mp3',
	},
	{
		char: 'וֲ',
		nameAudio: '/audio/name-vav-chataf-patach.mp3',
		soundAudio: '/audio/sound-vav-a-reduced.mp3',
	},
	{
		char: 'וֱ',
		nameAudio: '/audio/name-vav-chataf-segol.mp3',
		soundAudio: '/audio/sound-vav-e-reduced.mp3',
	},
	{
		char: 'וֳ',
		nameAudio: '/audio/name-vav-chataf-qamats.mp3',
		soundAudio: '/audio/sound-vav-o-reduced.mp3',
	},
	{
		char: 'וִי',
		nameAudio: '/audio/name-vav-hiriq-yod.mp3',
		soundAudio: '/audio/sound-vav-i-long.mp3',
	},
	{
		char: 'וֵי',
		nameAudio: '/audio/name-vav-tsere-yod.mp3',
		soundAudio: '/audio/sound-vav-ei.mp3',
	},
	{
		char: 'וֶי',
		nameAudio: '/audio/name-vav-segol-yod.mp3',
		soundAudio: '/audio/sound-vav-ei-segol.mp3',
	},
	{
		char: 'ו',
		nameAudio: '/audio/name-vav-base.mp3',
		soundAudio: '/audio/sound-vav-base.mp3',
		category: 'base',
	},
	{
		char: 'זַ',
		nameAudio: '/audio/name-zayin-patach.mp3',
		soundAudio: '/audio/sound-zayin-a.mp3',
	},
	{
		char: 'זָ',
		nameAudio: '/audio/name-zayin-qamats.mp3',
		soundAudio: '/audio/sound-zayin-a-long.mp3',
	},
	{
		char: 'זֶ',
		nameAudio: '/audio/name-zayin-segol.mp3',
		soundAudio: '/audio/sound-zayin-e.mp3',
	},
	{
		char: 'זֵ',
		nameAudio: '/audio/name-zayin-tsere.mp3',
		soundAudio: '/audio/sound-zayin-e-long.mp3',
	},
	{
		char: 'זִ',
		nameAudio: '/audio/name-zayin-hiriq.mp3',
		soundAudio: '/audio/sound-zayin-i.mp3',
	},
	{
		char: 'זֻ',
		nameAudio: '/audio/name-zayin-qubutz.mp3',
		soundAudio: '/audio/sound-zayin-u-short.mp3',
	},
	{
		char: 'זֹ',
		nameAudio: '/audio/name-zayin-holam.mp3',
		soundAudio: '/audio/sound-zayin-o.mp3',
	},
	{
		char: 'זְ',
		nameAudio: '/audio/name-zayin-shva.mp3',
		soundAudio: '/audio/sound-zayin-silent.mp3',
	},
	{
		char: 'זּ',
		nameAudio: '/audio/name-zayin-dagesh.mp3',
		soundAudio: '/audio/sound-zayin-emph.mp3',
	},
	{
		char: 'זֲ',
		nameAudio: '/audio/name-zayin-chataf-patach.mp3',
		soundAudio: '/audio/sound-zayin-a-reduced.mp3',
	},
	{
		char: 'זֱ',
		nameAudio: '/audio/name-zayin-chataf-segol.mp3',
		soundAudio: '/audio/sound-zayin-e-reduced.mp3',
	},
	{
		char: 'זֳ',
		nameAudio: '/audio/name-zayin-chataf-qamats.mp3',
		soundAudio: '/audio/sound-zayin-o-reduced.mp3',
	},
	{
		char: 'זִי',
		nameAudio: '/audio/name-zayin-hiriq-yod.mp3',
		soundAudio: '/audio/sound-zayin-i-long.mp3',
	},
	{
		char: 'זֵי',
		nameAudio: '/audio/name-zayin-tsere-yod.mp3',
		soundAudio: '/audio/sound-zayin-ei.mp3',
	},
	{
		char: 'זֶי',
		nameAudio: '/audio/name-zayin-segol-yod.mp3',
		soundAudio: '/audio/sound-zayin-ei-segol.mp3',
	},
	{
		char: 'ז',
		nameAudio: '/audio/name-zayin-base.mp3',
		soundAudio: '/audio/sound-zayin-base.mp3',
		category: 'base',
	},
	{
		char: 'חַ',
		nameAudio: '/audio/name-chet-patach.mp3',
		soundAudio: '/audio/sound-chet-a.mp3',
	},
	{
		char: 'חָ',
		nameAudio: '/audio/name-chet-qamats.mp3',
		soundAudio: '/audio/sound-chet-a-long.mp3',
	},
	{
		char: 'חֶ',
		nameAudio: '/audio/name-chet-segol.mp3',
		soundAudio: '/audio/sound-chet-e.mp3',
	},
	{
		char: 'חֵ',
		nameAudio: '/audio/name-chet-tsere.mp3',
		soundAudio: '/audio/sound-chet-e-long.mp3',
	},
	{
		char: 'חִ',
		nameAudio: '/audio/name-chet-hiriq.mp3',
		soundAudio: '/audio/sound-chet-i.mp3',
	},
	{
		char: 'חֻ',
		nameAudio: '/audio/name-chet-qubutz.mp3',
		soundAudio: '/audio/sound-chet-u-short.mp3',
	},
	{
		char: 'חֹ',
		nameAudio: '/audio/name-chet-holam.mp3',
		soundAudio: '/audio/sound-chet-o.mp3',
	},
	{
		char: 'חְ',
		nameAudio: '/audio/name-chet-shva.mp3',
		soundAudio: '/audio/sound-chet-silent.mp3',
	},
	{
		char: 'חּ',
		nameAudio: '/audio/name-chet-dagesh.mp3',
		soundAudio: '/audio/sound-chet-emph.mp3',
	},
	{
		char: 'חֲ',
		nameAudio: '/audio/name-chet-chataf-patach.mp3',
		soundAudio: '/audio/sound-chet-a-reduced.mp3',
	},
	{
		char: 'חֱ',
		nameAudio: '/audio/name-chet-chataf-segol.mp3',
		soundAudio: '/audio/sound-chet-e-reduced.mp3',
	},
	{
		char: 'חֳ',
		nameAudio: '/audio/name-chet-chataf-qamats.mp3',
		soundAudio: '/audio/sound-chet-o-reduced.mp3',
	},
	{
		char: 'חִי',
		nameAudio: '/audio/name-chet-hiriq-yod.mp3',
		soundAudio: '/audio/sound-chet-i-long.mp3',
	},
	{
		char: 'חֵי',
		nameAudio: '/audio/name-chet-tsere-yod.mp3',
		soundAudio: '/audio/sound-chet-ei.mp3',
	},
	{
		char: 'חֶי',
		nameAudio: '/audio/name-chet-segol-yod.mp3',
		soundAudio: '/audio/sound-chet-ei-segol.mp3',
	},
	{
		char: 'ח',
		nameAudio: '/audio/name-chet-base.mp3',
		soundAudio: '/audio/sound-chet-base.mp3',
		category: 'base',
	},
	{
		char: 'טַ',
		nameAudio: '/audio/name-tet-patach.mp3',
		soundAudio: '/audio/sound-tet-a.mp3',
	},
	{
		char: 'טָ',
		nameAudio: '/audio/name-tet-qamats.mp3',
		soundAudio: '/audio/sound-tet-a-long.mp3',
	},
	{
		char: 'טֶ',
		nameAudio: '/audio/name-tet-segol.mp3',
		soundAudio: '/audio/sound-tet-e.mp3',
	},
	{
		char: 'טֵ',
		nameAudio: '/audio/name-tet-tsere.mp3',
		soundAudio: '/audio/sound-tet-e-long.mp3',
	},
	{
		char: 'טִ',
		nameAudio: '/audio/name-tet-hiriq.mp3',
		soundAudio: '/audio/sound-tet-i.mp3',
	},
	{
		char: 'טֻ',
		nameAudio: '/audio/name-tet-qubutz.mp3',
		soundAudio: '/audio/sound-tet-u-short.mp3',
	},
	{
		char: 'טֹ',
		nameAudio: '/audio/name-tet-holam.mp3',
		soundAudio: '/audio/sound-tet-o.mp3',
	},
	{
		char: 'טְ',
		nameAudio: '/audio/name-tet-shva.mp3',
		soundAudio: '/audio/sound-tet-silent.mp3',
	},
	{
		char: 'טּ',
		nameAudio: '/audio/name-tet-dagesh.mp3',
		soundAudio: '/audio/sound-tet-emph.mp3',
	},
	{
		char: 'טֲ',
		nameAudio: '/audio/name-tet-chataf-patach.mp3',
		soundAudio: '/audio/sound-tet-a-reduced.mp3',
	},
	{
		char: 'טֱ',
		nameAudio: '/audio/name-tet-chataf-segol.mp3',
		soundAudio: '/audio/sound-tet-e-reduced.mp3',
	},
	{
		char: 'טֳ',
		nameAudio: '/audio/name-tet-chataf-qamats.mp3',
		soundAudio: '/audio/sound-tet-o-reduced.mp3',
	},
	{
		char: 'טִי',
		nameAudio: '/audio/name-tet-hiriq-yod.mp3',
		soundAudio: '/audio/sound-tet-i-long.mp3',
	},
	{
		char: 'טֵי',
		nameAudio: '/audio/name-tet-tsere-yod.mp3',
		soundAudio: '/audio/sound-tet-ei.mp3',
	},
	{
		char: 'טֶי',
		nameAudio: '/audio/name-tet-segol-yod.mp3',
		soundAudio: '/audio/sound-tet-ei-segol.mp3',
	},
	{
		char: 'ט',
		nameAudio: '/audio/name-tet-base.mp3',
		soundAudio: '/audio/sound-tet-base.mp3',
		category: 'base',
	},
	{
		char: 'יַ',
		nameAudio: '/audio/name-yod-patach.mp3',
		soundAudio: '/audio/sound-yod-a.mp3',
	},
	{
		char: 'יָ',
		nameAudio: '/audio/name-yod-qamats.mp3',
		soundAudio: '/audio/sound-yod-a-long.mp3',
	},
	{
		char: 'יֶ',
		nameAudio: '/audio/name-yod-segol.mp3',
		soundAudio: '/audio/sound-yod-e.mp3',
	},
	{
		char: 'יֵ',
		nameAudio: '/audio/name-yod-tsere.mp3',
		soundAudio: '/audio/sound-yod-e-long.mp3',
	},
	{
		char: 'יִ',
		nameAudio: '/audio/name-yod-hiriq.mp3',
		soundAudio: '/audio/sound-yod-i.mp3',
	},
	{
		char: 'יֻ',
		nameAudio: '/audio/name-yod-qubutz.mp3',
		soundAudio: '/audio/sound-yod-u-short.mp3',
	},
	{
		char: 'יֹ',
		nameAudio: '/audio/name-yod-holam.mp3',
		soundAudio: '/audio/sound-yod-o.mp3',
	},
	{
		char: 'יְ',
		nameAudio: '/audio/name-yod-shva.mp3',
		soundAudio: '/audio/sound-yod-silent.mp3',
	},
	{
		char: 'יּ',
		nameAudio: '/audio/name-yod-dagesh.mp3',
		soundAudio: '/audio/sound-yod-emph.mp3',
	},
	{
		char: 'יֲ',
		nameAudio: '/audio/name-yod-chataf-patach.mp3',
		soundAudio: '/audio/sound-yod-a-reduced.mp3',
	},
	{
		char: 'יֱ',
		nameAudio: '/audio/name-yod-chataf-segol.mp3',
		soundAudio: '/audio/sound-yod-e-reduced.mp3',
	},
	{
		char: 'יֳ',
		nameAudio: '/audio/name-yod-chataf-qamats.mp3',
		soundAudio: '/audio/sound-yod-o-reduced.mp3',
	},
	{
		char: 'יִי',
		nameAudio: '/audio/name-yod-hiriq-yod.mp3',
		soundAudio: '/audio/sound-yod-i-long.mp3',
	},
	{
		char: 'יֵי',
		nameAudio: '/audio/name-yod-tsere-yod.mp3',
		soundAudio: '/audio/sound-yod-ei.mp3',
	},
	{
		char: 'יֶי',
		nameAudio: '/audio/name-yod-segol-yod.mp3',
		soundAudio: '/audio/sound-yod-ei-segol.mp3',
	},
	{
		char: 'י',
		nameAudio: '/audio/name-yod-base.mp3',
		soundAudio: '/audio/sound-yod-base.mp3',
		category: 'base',
	},
	{
		char: 'כַ',
		nameAudio: '/audio/name-khaf-patach.mp3',
		soundAudio: '/audio/sound-khaf-a.mp3',
	},
	{
		char: 'כָ',
		nameAudio: '/audio/name-khaf-qamats.mp3',
		soundAudio: '/audio/sound-khaf-a-long.mp3',
	},
	{
		char: 'כֶ',
		nameAudio: '/audio/name-khaf-segol.mp3',
		soundAudio: '/audio/sound-khaf-e.mp3',
	},
	{
		char: 'כֵ',
		nameAudio: '/audio/name-khaf-tsere.mp3',
		soundAudio: '/audio/sound-khaf-e-long.mp3',
	},
	{
		char: 'כִ',
		nameAudio: '/audio/name-khaf-hiriq.mp3',
		soundAudio: '/audio/sound-khaf-i.mp3',
	},
	{
		char: 'כֻ',
		nameAudio: '/audio/name-khaf-qubutz.mp3',
		soundAudio: '/audio/sound-khaf-u-short.mp3',
	},
	{
		char: 'כֹ',
		nameAudio: '/audio/name-khaf-holam.mp3',
		soundAudio: '/audio/sound-khaf-o.mp3',
	},
	{
		char: 'כְ',
		nameAudio: '/audio/name-khaf-shva.mp3',
		soundAudio: '/audio/sound-khaf-silent.mp3',
	},
	{
		char: 'כּ',
		nameAudio: '/audio/name-khaf-dagesh.mp3',
		soundAudio: '/audio/sound-khaf-emph.mp3',
	},
	{
		char: 'כֲ',
		nameAudio: '/audio/name-khaf-chataf-patach.mp3',
		soundAudio: '/audio/sound-khaf-a-reduced.mp3',
	},
	{
		char: 'כֱ',
		nameAudio: '/audio/name-khaf-chataf-segol.mp3',
		soundAudio: '/audio/sound-khaf-e-reduced.mp3',
	},
	{
		char: 'כֳ',
		nameAudio: '/audio/name-khaf-chataf-qamats.mp3',
		soundAudio: '/audio/sound-khaf-o-reduced.mp3',
	},
	{
		char: 'כִי',
		nameAudio: '/audio/name-khaf-hiriq-yod.mp3',
		soundAudio: '/audio/sound-khaf-i-long.mp3',
	},
	{
		char: 'כֵי',
		nameAudio: '/audio/name-khaf-tsere-yod.mp3',
		soundAudio: '/audio/sound-khaf-ei.mp3',
	},
	{
		char: 'כֶי',
		nameAudio: '/audio/name-khaf-segol-yod.mp3',
		soundAudio: '/audio/sound-khaf-ei-segol.mp3',
	},
	{
		char: 'כ',
		nameAudio: '/audio/name-khaf-base.mp3',
		soundAudio: '/audio/sound-khaf-base.mp3',
		category: 'base',
	},
	{
		char: 'כַּ',
		nameAudio: '/audio/name-kaf-patach.mp3',
		soundAudio: '/audio/sound-kaf-a.mp3',
	},
	{
		char: 'כָּ',
		nameAudio: '/audio/name-kaf-qamats.mp3',
		soundAudio: '/audio/sound-kaf-a-long.mp3',
	},
	{
		char: 'כֶּ',
		nameAudio: '/audio/name-kaf-segol.mp3',
		soundAudio: '/audio/sound-kaf-e.mp3',
	},
	{
		char: 'כֵּ',
		nameAudio: '/audio/name-kaf-tsere.mp3',
		soundAudio: '/audio/sound-kaf-e-long.mp3',
	},
	{
		char: 'כִּ',
		nameAudio: '/audio/name-kaf-hiriq.mp3',
		soundAudio: '/audio/sound-kaf-i.mp3',
	},
	{
		char: 'כֻּ',
		nameAudio: '/audio/name-kaf-qubutz.mp3',
		soundAudio: '/audio/sound-kaf-u-short.mp3',
	},
	{
		char: 'כֹּ',
		nameAudio: '/audio/name-kaf-holam.mp3',
		soundAudio: '/audio/sound-kaf-o.mp3',
	},
	{
		char: 'כְּ',
		nameAudio: '/audio/name-kaf-shva.mp3',
		soundAudio: '/audio/sound-kaf-silent.mp3',
	},
	{
		char: 'כּּ',
		nameAudio: '/audio/name-kaf-dagesh.mp3',
		soundAudio: '/audio/sound-kaf-emph.mp3',
	},
	{
		char: 'כֲּ',
		nameAudio: '/audio/name-kaf-chataf-patach.mp3',
		soundAudio: '/audio/sound-kaf-a-reduced.mp3',
	},
	{
		char: 'כֱּ',
		nameAudio: '/audio/name-kaf-chataf-segol.mp3',
		soundAudio: '/audio/sound-kaf-e-reduced.mp3',
	},
	{
		char: 'כֳּ',
		nameAudio: '/audio/name-kaf-chataf-qamats.mp3',
		soundAudio: '/audio/sound-kaf-o-reduced.mp3',
	},
	{
		char: 'כִּי',
		nameAudio: '/audio/name-kaf-hiriq-yod.mp3',
		soundAudio: '/audio/sound-kaf-i-long.mp3',
	},
	{
		char: 'כֵּי',
		nameAudio: '/audio/name-kaf-tsere-yod.mp3',
		soundAudio: '/audio/sound-kaf-ei.mp3',
	},
	{
		char: 'כֶּי',
		nameAudio: '/audio/name-kaf-segol-yod.mp3',
		soundAudio: '/audio/sound-kaf-ei-segol.mp3',
	},
	{
		char: 'כּ',
		nameAudio: '/audio/name-kaf-base.mp3',
		soundAudio: '/audio/sound-kaf-base.mp3',
		category: 'base',
	},
	{
		char: 'לַ',
		nameAudio: '/audio/name-lamed-patach.mp3',
		soundAudio: '/audio/sound-lamed-a.mp3',
	},
	{
		char: 'לָ',
		nameAudio: '/audio/name-lamed-qamats.mp3',
		soundAudio: '/audio/sound-lamed-a-long.mp3',
	},
	{
		char: 'לֶ',
		nameAudio: '/audio/name-lamed-segol.mp3',
		soundAudio: '/audio/sound-lamed-e.mp3',
	},
	{
		char: 'לֵ',
		nameAudio: '/audio/name-lamed-tsere.mp3',
		soundAudio: '/audio/sound-lamed-e-long.mp3',
	},
	{
		char: 'לִ',
		nameAudio: '/audio/name-lamed-hiriq.mp3',
		soundAudio: '/audio/sound-lamed-i.mp3',
	},
	{
		char: 'לֻ',
		nameAudio: '/audio/name-lamed-qubutz.mp3',
		soundAudio: '/audio/sound-lamed-u-short.mp3',
	},
	{
		char: 'לֹ',
		nameAudio: '/audio/name-lamed-holam.mp3',
		soundAudio: '/audio/sound-lamed-o.mp3',
	},
	{
		char: 'לְ',
		nameAudio: '/audio/name-lamed-shva.mp3',
		soundAudio: '/audio/sound-lamed-silent.mp3',
	},
	{
		char: 'לּ',
		nameAudio: '/audio/name-lamed-dagesh.mp3',
		soundAudio: '/audio/sound-lamed-emph.mp3',
	},
	{
		char: 'לֲ',
		nameAudio: '/audio/name-lamed-chataf-patach.mp3',
		soundAudio: '/audio/sound-lamed-a-reduced.mp3',
	},
	{
		char: 'לֱ',
		nameAudio: '/audio/name-lamed-chataf-segol.mp3',
		soundAudio: '/audio/sound-lamed-e-reduced.mp3',
	},
	{
		char: 'לֳ',
		nameAudio: '/audio/name-lamed-chataf-qamats.mp3',
		soundAudio: '/audio/sound-lamed-o-reduced.mp3',
	},
	{
		char: 'לִי',
		nameAudio: '/audio/name-lamed-hiriq-yod.mp3',
		soundAudio: '/audio/sound-lamed-i-long.mp3',
	},
	{
		char: 'לֵי',
		nameAudio: '/audio/name-lamed-tsere-yod.mp3',
		soundAudio: '/audio/sound-lamed-ei.mp3',
	},
	{
		char: 'לֶי',
		nameAudio: '/audio/name-lamed-segol-yod.mp3',
		soundAudio: '/audio/sound-lamed-ei-segol.mp3',
	},
	{
		char: 'ל',
		nameAudio: '/audio/name-lamed-base.mp3',
		soundAudio: '/audio/sound-lamed-base.mp3',
		category: 'base',
	},
	{
		char: 'מַ',
		nameAudio: '/audio/name-mem-patach.mp3',
		soundAudio: '/audio/sound-mem-a.mp3',
	},
	{
		char: 'מָ',
		nameAudio: '/audio/name-mem-qamats.mp3',
		soundAudio: '/audio/sound-mem-a-long.mp3',
	},
	{
		char: 'מֶ',
		nameAudio: '/audio/name-mem-segol.mp3',
		soundAudio: '/audio/sound-mem-e.mp3',
	},
	{
		char: 'מֵ',
		nameAudio: '/audio/name-mem-tsere.mp3',
		soundAudio: '/audio/sound-mem-e-long.mp3',
	},
	{
		char: 'מִ',
		nameAudio: '/audio/name-mem-hiriq.mp3',
		soundAudio: '/audio/sound-mem-i.mp3',
	},
	{
		char: 'מֻ',
		nameAudio: '/audio/name-mem-qubutz.mp3',
		soundAudio: '/audio/sound-mem-u-short.mp3',
	},
	{
		char: 'מֹ',
		nameAudio: '/audio/name-mem-holam.mp3',
		soundAudio: '/audio/sound-mem-o.mp3',
	},
	{
		char: 'מְ',
		nameAudio: '/audio/name-mem-shva.mp3',
		soundAudio: '/audio/sound-mem-silent.mp3',
	},
	{
		char: 'מּ',
		nameAudio: '/audio/name-mem-dagesh.mp3',
		soundAudio: '/audio/sound-mem-emph.mp3',
	},
	{
		char: 'מֲ',
		nameAudio: '/audio/name-mem-chataf-patach.mp3',
		soundAudio: '/audio/sound-mem-a-reduced.mp3',
	},
	{
		char: 'מֱ',
		nameAudio: '/audio/name-mem-chataf-segol.mp3',
		soundAudio: '/audio/sound-mem-e-reduced.mp3',
	},
	{
		char: 'מֳ',
		nameAudio: '/audio/name-mem-chataf-qamats.mp3',
		soundAudio: '/audio/sound-mem-o-reduced.mp3',
	},
	{
		char: 'מִי',
		nameAudio: '/audio/name-mem-hiriq-yod.mp3',
		soundAudio: '/audio/sound-mem-i-long.mp3',
	},
	{
		char: 'מֵי',
		nameAudio: '/audio/name-mem-tsere-yod.mp3',
		soundAudio: '/audio/sound-mem-ei.mp3',
	},
	{
		char: 'מֶי',
		nameAudio: '/audio/name-mem-segol-yod.mp3',
		soundAudio: '/audio/sound-mem-ei-segol.mp3',
	},
	{
		char: 'מ',
		nameAudio: '/audio/name-mem-base.mp3',
		soundAudio: '/audio/sound-mem-base.mp3',
		category: 'base',
	},
	{
		char: 'נַ',
		nameAudio: '/audio/name-nun-patach.mp3',
		soundAudio: '/audio/sound-nun-a.mp3',
	},
	{
		char: 'נָ',
		nameAudio: '/audio/name-nun-qamats.mp3',
		soundAudio: '/audio/sound-nun-a-long.mp3',
	},
	{
		char: 'נֶ',
		nameAudio: '/audio/name-nun-segol.mp3',
		soundAudio: '/audio/sound-nun-e.mp3',
	},
	{
		char: 'נֵ',
		nameAudio: '/audio/name-nun-tsere.mp3',
		soundAudio: '/audio/sound-nun-e-long.mp3',
	},
	{
		char: 'נִ',
		nameAudio: '/audio/name-nun-hiriq.mp3',
		soundAudio: '/audio/sound-nun-i.mp3',
	},
	{
		char: 'נֻ',
		nameAudio: '/audio/name-nun-qubutz.mp3',
		soundAudio: '/audio/sound-nun-u-short.mp3',
	},
	{
		char: 'נֹ',
		nameAudio: '/audio/name-nun-holam.mp3',
		soundAudio: '/audio/sound-nun-o.mp3',
	},
	{
		char: 'נְ',
		nameAudio: '/audio/name-nun-shva.mp3',
		soundAudio: '/audio/sound-nun-silent.mp3',
	},
	{
		char: 'נּ',
		nameAudio: '/audio/name-nun-dagesh.mp3',
		soundAudio: '/audio/sound-nun-emph.mp3',
	},
	{
		char: 'נֲ',
		nameAudio: '/audio/name-nun-chataf-patach.mp3',
		soundAudio: '/audio/sound-nun-a-reduced.mp3',
	},
	{
		char: 'נֱ',
		nameAudio: '/audio/name-nun-chataf-segol.mp3',
		soundAudio: '/audio/sound-nun-e-reduced.mp3',
	},
	{
		char: 'נֳ',
		nameAudio: '/audio/name-nun-chataf-qamats.mp3',
		soundAudio: '/audio/sound-nun-o-reduced.mp3',
	},
	{
		char: 'נִי',
		nameAudio: '/audio/name-nun-hiriq-yod.mp3',
		soundAudio: '/audio/sound-nun-i-long.mp3',
	},
	{
		char: 'נֵי',
		nameAudio: '/audio/name-nun-tsere-yod.mp3',
		soundAudio: '/audio/sound-nun-ei.mp3',
	},
	{
		char: 'נֶי',
		nameAudio: '/audio/name-nun-segol-yod.mp3',
		soundAudio: '/audio/sound-nun-ei-segol.mp3',
	},
	{
		char: 'נ',
		nameAudio: '/audio/name-nun-base.mp3',
		soundAudio: '/audio/sound-nun-base.mp3',
		category: 'base',
	},
	{
		char: 'סַ',
		nameAudio: '/audio/name-samekh-patach.mp3',
		soundAudio: '/audio/sound-samekh-a.mp3',
	},
	{
		char: 'סָ',
		nameAudio: '/audio/name-samekh-qamats.mp3',
		soundAudio: '/audio/sound-samekh-a-long.mp3',
	},
	{
		char: 'סֶ',
		nameAudio: '/audio/name-samekh-segol.mp3',
		soundAudio: '/audio/sound-samekh-e.mp3',
	},
	{
		char: 'סֵ',
		nameAudio: '/audio/name-samekh-tsere.mp3',
		soundAudio: '/audio/sound-samekh-e-long.mp3',
	},
	{
		char: 'סִ',
		nameAudio: '/audio/name-samekh-hiriq.mp3',
		soundAudio: '/audio/sound-samekh-i.mp3',
	},
	{
		char: 'סֻ',
		nameAudio: '/audio/name-samekh-qubutz.mp3',
		soundAudio: '/audio/sound-samekh-u-short.mp3',
	},
	{
		char: 'סֹ',
		nameAudio: '/audio/name-samekh-holam.mp3',
		soundAudio: '/audio/sound-samekh-o.mp3',
	},
	{
		char: 'סְ',
		nameAudio: '/audio/name-samekh-shva.mp3',
		soundAudio: '/audio/sound-samekh-silent.mp3',
	},
	{
		char: 'סּ',
		nameAudio: '/audio/name-samekh-dagesh.mp3',
		soundAudio: '/audio/sound-samekh-emph.mp3',
	},
	{
		char: 'סֲ',
		nameAudio: '/audio/name-samekh-chataf-patach.mp3',
		soundAudio: '/audio/sound-samekh-a-reduced.mp3',
	},
	{
		char: 'סֱ',
		nameAudio: '/audio/name-samekh-chataf-segol.mp3',
		soundAudio: '/audio/sound-samekh-e-reduced.mp3',
	},
	{
		char: 'סֳ',
		nameAudio: '/audio/name-samekh-chataf-qamats.mp3',
		soundAudio: '/audio/sound-samekh-o-reduced.mp3',
	},
	{
		char: 'סִי',
		nameAudio: '/audio/name-samekh-hiriq-yod.mp3',
		soundAudio: '/audio/sound-samekh-i-long.mp3',
	},
	{
		char: 'סֵי',
		nameAudio: '/audio/name-samekh-tsere-yod.mp3',
		soundAudio: '/audio/sound-samekh-ei.mp3',
	},
	{
		char: 'סֶי',
		nameAudio: '/audio/name-samekh-segol-yod.mp3',
		soundAudio: '/audio/sound-samekh-ei-segol.mp3',
	},
	{
		char: 'ס',
		nameAudio: '/audio/name-samekh-base.mp3',
		soundAudio: '/audio/sound-samekh-base.mp3',
		category: 'base',
	},
	{
		char: 'עַ',
		nameAudio: '/audio/name-ayin-patach.mp3',
		soundAudio: '/audio/sound-ayin-a.mp3',
	},
	{
		char: 'עָ',
		nameAudio: '/audio/name-ayin-qamats.mp3',
		soundAudio: '/audio/sound-ayin-a-long.mp3',
	},
	{
		char: 'עֶ',
		nameAudio: '/audio/name-ayin-segol.mp3',
		soundAudio: '/audio/sound-ayin-e.mp3',
	},
	{
		char: 'עֵ',
		nameAudio: '/audio/name-ayin-tsere.mp3',
		soundAudio: '/audio/sound-ayin-e-long.mp3',
	},
	{
		char: 'עִ',
		nameAudio: '/audio/name-ayin-hiriq.mp3',
		soundAudio: '/audio/sound-ayin-i.mp3',
	},
	{
		char: 'עֻ',
		nameAudio: '/audio/name-ayin-qubutz.mp3',
		soundAudio: '/audio/sound-ayin-u-short.mp3',
	},
	{
		char: 'עֹ',
		nameAudio: '/audio/name-ayin-holam.mp3',
		soundAudio: '/audio/sound-ayin-o.mp3',
	},
	{
		char: 'עְ',
		nameAudio: '/audio/name-ayin-shva.mp3',
		soundAudio: '/audio/sound-ayin-silent.mp3',
	},
	{
		char: 'עּ',
		nameAudio: '/audio/name-ayin-dagesh.mp3',
		soundAudio: '/audio/sound-ayin-emph.mp3',
	},
	{
		char: 'עֲ',
		nameAudio: '/audio/name-ayin-chataf-patach.mp3',
		soundAudio: '/audio/sound-ayin-a-reduced.mp3',
	},
	{
		char: 'עֱ',
		nameAudio: '/audio/name-ayin-chataf-segol.mp3',
		soundAudio: '/audio/sound-ayin-e-reduced.mp3',
	},
	{
		char: 'עֳ',
		nameAudio: '/audio/name-ayin-chataf-qamats.mp3',
		soundAudio: '/audio/sound-ayin-o-reduced.mp3',
	},
	{
		char: 'עִי',
		nameAudio: '/audio/name-ayin-hiriq-yod.mp3',
		soundAudio: '/audio/sound-ayin-i-long.mp3',
	},
	{
		char: 'עֵי',
		nameAudio: '/audio/name-ayin-tsere-yod.mp3',
		soundAudio: '/audio/sound-ayin-ei.mp3',
	},
	{
		char: 'עֶי',
		nameAudio: '/audio/name-ayin-segol-yod.mp3',
		soundAudio: '/audio/sound-ayin-ei-segol.mp3',
	},
	{
		char: 'ע',
		nameAudio: '/audio/name-ayin-base.mp3',
		soundAudio: '/audio/sound-ayin-base.mp3',
		category: 'base',
	},
	{
		char: 'פַ',
		nameAudio: '/audio/name-fe-patach.mp3',
		soundAudio: '/audio/sound-fe-a.mp3',
	},
	{
		char: 'פָ',
		nameAudio: '/audio/name-fe-qamats.mp3',
		soundAudio: '/audio/sound-fe-a-long.mp3',
	},
	{
		char: 'פֶ',
		nameAudio: '/audio/name-fe-segol.mp3',
		soundAudio: '/audio/sound-fe-e.mp3',
	},
	{
		char: 'פֵ',
		nameAudio: '/audio/name-fe-tsere.mp3',
		soundAudio: '/audio/sound-fe-e-long.mp3',
	},
	{
		char: 'פִ',
		nameAudio: '/audio/name-fe-hiriq.mp3',
		soundAudio: '/audio/sound-fe-i.mp3',
	},
	{
		char: 'פֻ',
		nameAudio: '/audio/name-fe-qubutz.mp3',
		soundAudio: '/audio/sound-fe-u-short.mp3',
	},
	{
		char: 'פֹ',
		nameAudio: '/audio/name-fe-holam.mp3',
		soundAudio: '/audio/sound-fe-o.mp3',
	},
	{
		char: 'פְ',
		nameAudio: '/audio/name-fe-shva.mp3',
		soundAudio: '/audio/sound-fe-silent.mp3',
	},
	{
		char: 'פּ',
		nameAudio: '/audio/name-fe-dagesh.mp3',
		soundAudio: '/audio/sound-fe-emph.mp3',
	},
	{
		char: 'פֲ',
		nameAudio: '/audio/name-fe-chataf-patach.mp3',
		soundAudio: '/audio/sound-fe-a-reduced.mp3',
	},
	{
		char: 'פֱ',
		nameAudio: '/audio/name-fe-chataf-segol.mp3',
		soundAudio: '/audio/sound-fe-e-reduced.mp3',
	},
	{
		char: 'פֳ',
		nameAudio: '/audio/name-fe-chataf-qamats.mp3',
		soundAudio: '/audio/sound-fe-o-reduced.mp3',
	},
	{
		char: 'פִי',
		nameAudio: '/audio/name-fe-hiriq-yod.mp3',
		soundAudio: '/audio/sound-fe-i-long.mp3',
	},
	{
		char: 'פֵי',
		nameAudio: '/audio/name-fe-tsere-yod.mp3',
		soundAudio: '/audio/sound-fe-ei.mp3',
	},
	{
		char: 'פֶי',
		nameAudio: '/audio/name-fe-segol-yod.mp3',
		soundAudio: '/audio/sound-fe-ei-segol.mp3',
	},
	{
		char: 'פ',
		nameAudio: '/audio/name-fe-base.mp3',
		soundAudio: '/audio/sound-fe-base.mp3',
		category: 'base',
	},
	{
		char: 'פַּ',
		nameAudio: '/audio/name-pe-patach.mp3',
		soundAudio: '/audio/sound-pe-a.mp3',
	},
	{
		char: 'פָּ',
		nameAudio: '/audio/name-pe-qamats.mp3',
		soundAudio: '/audio/sound-pe-a-long.mp3',
	},
	{
		char: 'פֶּ',
		nameAudio: '/audio/name-pe-segol.mp3',
		soundAudio: '/audio/sound-pe-e.mp3',
	},
	{
		char: 'פֵּ',
		nameAudio: '/audio/name-pe-tsere.mp3',
		soundAudio: '/audio/sound-pe-e-long.mp3',
	},
	{
		char: 'פִּ',
		nameAudio: '/audio/name-pe-hiriq.mp3',
		soundAudio: '/audio/sound-pe-i.mp3',
	},
	{
		char: 'פֻּ',
		nameAudio: '/audio/name-pe-qubutz.mp3',
		soundAudio: '/audio/sound-pe-u-short.mp3',
	},
	{
		char: 'פֹּ',
		nameAudio: '/audio/name-pe-holam.mp3',
		soundAudio: '/audio/sound-pe-o.mp3',
	},
	{
		char: 'פְּ',
		nameAudio: '/audio/name-pe-shva.mp3',
		soundAudio: '/audio/sound-pe-silent.mp3',
	},
	{
		char: 'פּּ',
		nameAudio: '/audio/name-pe-dagesh.mp3',
		soundAudio: '/audio/sound-pe-emph.mp3',
	},
	{
		char: 'פֲּ',
		nameAudio: '/audio/name-pe-chataf-patach.mp3',
		soundAudio: '/audio/sound-pe-a-reduced.mp3',
	},
	{
		char: 'פֱּ',
		nameAudio: '/audio/name-pe-chataf-segol.mp3',
		soundAudio: '/audio/sound-pe-e-reduced.mp3',
	},
	{
		char: 'פֳּ',
		nameAudio: '/audio/name-pe-chataf-qamats.mp3',
		soundAudio: '/audio/sound-pe-o-reduced.mp3',
	},
	{
		char: 'פִּי',
		nameAudio: '/audio/name-pe-hiriq-yod.mp3',
		soundAudio: '/audio/sound-pe-i-long.mp3',
	},
	{
		char: 'פֵּי',
		nameAudio: '/audio/name-pe-tsere-yod.mp3',
		soundAudio: '/audio/sound-pe-ei.mp3',
	},
	{
		char: 'פֶּי',
		nameAudio: '/audio/name-pe-segol-yod.mp3',
		soundAudio: '/audio/sound-pe-ei-segol.mp3',
	},
	{
		char: 'פּ',
		nameAudio: '/audio/name-pe-base.mp3',
		soundAudio: '/audio/sound-pe-base.mp3',
		category: 'base',
	},
	{
		char: 'צַ',
		nameAudio: '/audio/name-tsadi-patach.mp3',
		soundAudio: '/audio/sound-tsadi-a.mp3',
	},
	{
		char: 'צָ',
		nameAudio: '/audio/name-tsadi-qamats.mp3',
		soundAudio: '/audio/sound-tsadi-a-long.mp3',
	},
	{
		char: 'צֶ',
		nameAudio: '/audio/name-tsadi-segol.mp3',
		soundAudio: '/audio/sound-tsadi-e.mp3',
	},
	{
		char: 'צֵ',
		nameAudio: '/audio/name-tsadi-tsere.mp3',
		soundAudio: '/audio/sound-tsadi-e-long.mp3',
	},
	{
		char: 'צִ',
		nameAudio: '/audio/name-tsadi-hiriq.mp3',
		soundAudio: '/audio/sound-tsadi-i.mp3',
	},
	{
		char: 'צֻ',
		nameAudio: '/audio/name-tsadi-qubutz.mp3',
		soundAudio: '/audio/sound-tsadi-u-short.mp3',
	},
	{
		char: 'צֹ',
		nameAudio: '/audio/name-tsadi-holam.mp3',
		soundAudio: '/audio/sound-tsadi-o.mp3',
	},
	{
		char: 'צְ',
		nameAudio: '/audio/name-tsadi-shva.mp3',
		soundAudio: '/audio/sound-tsadi-silent.mp3',
	},
	{
		char: 'צּ',
		nameAudio: '/audio/name-tsadi-dagesh.mp3',
		soundAudio: '/audio/sound-tsadi-emph.mp3',
	},
	{
		char: 'צֲ',
		nameAudio: '/audio/name-tsadi-chataf-patach.mp3',
		soundAudio: '/audio/sound-tsadi-a-reduced.mp3',
	},
	{
		char: 'צֱ',
		nameAudio: '/audio/name-tsadi-chataf-segol.mp3',
		soundAudio: '/audio/sound-tsadi-e-reduced.mp3',
	},
	{
		char: 'צֳ',
		nameAudio: '/audio/name-tsadi-chataf-qamats.mp3',
		soundAudio: '/audio/sound-tsadi-o-reduced.mp3',
	},
	{
		char: 'צִי',
		nameAudio: '/audio/name-tsadi-hiriq-yod.mp3',
		soundAudio: '/audio/sound-tsadi-i-long.mp3',
	},
	{
		char: 'צֵי',
		nameAudio: '/audio/name-tsadi-tsere-yod.mp3',
		soundAudio: '/audio/sound-tsadi-ei.mp3',
	},
	{
		char: 'צֶי',
		nameAudio: '/audio/name-tsadi-segol-yod.mp3',
		soundAudio: '/audio/sound-tsadi-ei-segol.mp3',
	},
	{
		char: 'צ',
		nameAudio: '/audio/name-tsadi-base.mp3',
		soundAudio: '/audio/sound-tsadi-base.mp3',
		category: 'base',
	},
	{
		char: 'קַ',
		nameAudio: '/audio/name-qof-patach.mp3',
		soundAudio: '/audio/sound-qof-a.mp3',
	},
	{
		char: 'קָ',
		nameAudio: '/audio/name-qof-qamats.mp3',
		soundAudio: '/audio/sound-qof-a-long.mp3',
	},
	{
		char: 'קֶ',
		nameAudio: '/audio/name-qof-segol.mp3',
		soundAudio: '/audio/sound-qof-e.mp3',
	},
	{
		char: 'קֵ',
		nameAudio: '/audio/name-qof-tsere.mp3',
		soundAudio: '/audio/sound-qof-e-long.mp3',
	},
	{
		char: 'קִ',
		nameAudio: '/audio/name-qof-hiriq.mp3',
		soundAudio: '/audio/sound-qof-i.mp3',
	},
	{
		char: 'קֻ',
		nameAudio: '/audio/name-qof-qubutz.mp3',
		soundAudio: '/audio/sound-qof-u-short.mp3',
	},
	{
		char: 'קֹ',
		nameAudio: '/audio/name-qof-holam.mp3',
		soundAudio: '/audio/sound-qof-o.mp3',
	},
	{
		char: 'קְ',
		nameAudio: '/audio/name-qof-shva.mp3',
		soundAudio: '/audio/sound-qof-silent.mp3',
	},
	{
		char: 'קּ',
		nameAudio: '/audio/name-qof-dagesh.mp3',
		soundAudio: '/audio/sound-qof-emph.mp3',
	},
	{
		char: 'קֲ',
		nameAudio: '/audio/name-qof-chataf-patach.mp3',
		soundAudio: '/audio/sound-qof-a-reduced.mp3',
	},
	{
		char: 'קֱ',
		nameAudio: '/audio/name-qof-chataf-segol.mp3',
		soundAudio: '/audio/sound-qof-e-reduced.mp3',
	},
	{
		char: 'קֳ',
		nameAudio: '/audio/name-qof-chataf-qamats.mp3',
		soundAudio: '/audio/sound-qof-o-reduced.mp3',
	},
	{
		char: 'קִי',
		nameAudio: '/audio/name-qof-hiriq-yod.mp3',
		soundAudio: '/audio/sound-qof-i-long.mp3',
	},
	{
		char: 'קֵי',
		nameAudio: '/audio/name-qof-tsere-yod.mp3',
		soundAudio: '/audio/sound-qof-ei.mp3',
	},
	{
		char: 'קֶי',
		nameAudio: '/audio/name-qof-segol-yod.mp3',
		soundAudio: '/audio/sound-qof-ei-segol.mp3',
	},
	{
		char: 'ק',
		nameAudio: '/audio/name-qof-base.mp3',
		soundAudio: '/audio/sound-qof-base.mp3',
		category: 'base',
	},
	{
		char: 'רַ',
		nameAudio: '/audio/name-resh-patach.mp3',
		soundAudio: '/audio/sound-resh-a.mp3',
	},
	{
		char: 'רָ',
		nameAudio: '/audio/name-resh-qamats.mp3',
		soundAudio: '/audio/sound-resh-a-long.mp3',
	},
	{
		char: 'רֶ',
		nameAudio: '/audio/name-resh-segol.mp3',
		soundAudio: '/audio/sound-resh-e.mp3',
	},
	{
		char: 'רֵ',
		nameAudio: '/audio/name-resh-tsere.mp3',
		soundAudio: '/audio/sound-resh-e-long.mp3',
	},
	{
		char: 'רִ',
		nameAudio: '/audio/name-resh-hiriq.mp3',
		soundAudio: '/audio/sound-resh-i.mp3',
	},
	{
		char: 'רֻ',
		nameAudio: '/audio/name-resh-qubutz.mp3',
		soundAudio: '/audio/sound-resh-u-short.mp3',
	},
	{
		char: 'רֹ',
		nameAudio: '/audio/name-resh-holam.mp3',
		soundAudio: '/audio/sound-resh-o.mp3',
	},
	{
		char: 'רְ',
		nameAudio: '/audio/name-resh-shva.mp3',
		soundAudio: '/audio/sound-resh-silent.mp3',
	},
	{
		char: 'רּ',
		nameAudio: '/audio/name-resh-dagesh.mp3',
		soundAudio: '/audio/sound-resh-emph.mp3',
	},
	{
		char: 'רֲ',
		nameAudio: '/audio/name-resh-chataf-patach.mp3',
		soundAudio: '/audio/sound-resh-a-reduced.mp3',
	},
	{
		char: 'רֱ',
		nameAudio: '/audio/name-resh-chataf-segol.mp3',
		soundAudio: '/audio/sound-resh-e-reduced.mp3',
	},
	{
		char: 'רֳ',
		nameAudio: '/audio/name-resh-chataf-qamats.mp3',
		soundAudio: '/audio/sound-resh-o-reduced.mp3',
	},
	{
		char: 'רִי',
		nameAudio: '/audio/name-resh-hiriq-yod.mp3',
		soundAudio: '/audio/sound-resh-i-long.mp3',
	},
	{
		char: 'רֵי',
		nameAudio: '/audio/name-resh-tsere-yod.mp3',
		soundAudio: '/audio/sound-resh-ei.mp3',
	},
	{
		char: 'רֶי',
		nameAudio: '/audio/name-resh-segol-yod.mp3',
		soundAudio: '/audio/sound-resh-ei-segol.mp3',
	},
	{
		char: 'ר',
		nameAudio: '/audio/name-resh-base.mp3',
		soundAudio: '/audio/sound-resh-base.mp3',
		category: 'base',
	},
	{
		char: 'שַׁ',
		nameAudio: '/audio/name-shin-patach.mp3',
		soundAudio: '/audio/sound-shin-a.mp3',
	},
	{
		char: 'שָׁ',
		nameAudio: '/audio/name-shin-qamats.mp3',
		soundAudio: '/audio/sound-shin-a-long.mp3',
	},
	{
		char: 'שֶׁ',
		nameAudio: '/audio/name-shin-segol.mp3',
		soundAudio: '/audio/sound-shin-e.mp3',
	},
	{
		char: 'שֵׁ',
		nameAudio: '/audio/name-shin-tsere.mp3',
		soundAudio: '/audio/sound-shin-e-long.mp3',
	},
	{
		char: 'שִׁ',
		nameAudio: '/audio/name-shin-hiriq.mp3',
		soundAudio: '/audio/sound-shin-i.mp3',
	},
	{
		char: 'שֻׁ',
		nameAudio: '/audio/name-shin-qubutz.mp3',
		soundAudio: '/audio/sound-shin-u-short.mp3',
	},
	{
		char: 'שֹׁ',
		nameAudio: '/audio/name-shin-holam.mp3',
		soundAudio: '/audio/sound-shin-o.mp3',
	},
	{
		char: 'שְׁ',
		nameAudio: '/audio/name-shin-shva.mp3',
		soundAudio: '/audio/sound-shin-silent.mp3',
	},
	{
		char: 'שּׁ',
		nameAudio: '/audio/name-shin-dagesh.mp3',
		soundAudio: '/audio/sound-shin-emph.mp3',
	},
	{
		char: 'שֲׁ',
		nameAudio: '/audio/name-shin-chataf-patach.mp3',
		soundAudio: '/audio/sound-shin-a-reduced.mp3',
	},
	{
		char: 'שֱׁ',
		nameAudio: '/audio/name-shin-chataf-segol.mp3',
		soundAudio: '/audio/sound-shin-e-reduced.mp3',
	},
	{
		char: 'שֳׁ',
		nameAudio: '/audio/name-shin-chataf-qamats.mp3',
		soundAudio: '/audio/sound-shin-o-reduced.mp3',
	},
	{
		char: 'שִׁי',
		nameAudio: '/audio/name-shin-hiriq-yod.mp3',
		soundAudio: '/audio/sound-shin-i-long.mp3',
	},
	{
		char: 'שֵׁי',
		nameAudio: '/audio/name-shin-tsere-yod.mp3',
		soundAudio: '/audio/sound-shin-ei.mp3',
	},
	{
		char: 'שֶׁי',
		nameAudio: '/audio/name-shin-segol-yod.mp3',
		soundAudio: '/audio/sound-shin-ei-segol.mp3',
	},
	{
		char: 'שׁ',
		nameAudio: '/audio/name-shin-base.mp3',
		soundAudio: '/audio/sound-shin-base.mp3',
		category: 'base',
	},
	{
		char: 'שַׂ',
		nameAudio: '/audio/name-sin-patach.mp3',
		soundAudio: '/audio/sound-sin-a.mp3',
	},
	{
		char: 'שָׂ',
		nameAudio: '/audio/name-sin-qamats.mp3',
		soundAudio: '/audio/sound-sin-a-long.mp3',
	},
	{
		char: 'שֶׂ',
		nameAudio: '/audio/name-sin-segol.mp3',
		soundAudio: '/audio/sound-sin-e.mp3',
	},
	{
		char: 'שֵׂ',
		nameAudio: '/audio/name-sin-tsere.mp3',
		soundAudio: '/audio/sound-sin-e-long.mp3',
	},
	{
		char: 'שִׂ',
		nameAudio: '/audio/name-sin-hiriq.mp3',
		soundAudio: '/audio/sound-sin-i.mp3',
	},
	{
		char: 'שֻׂ',
		nameAudio: '/audio/name-sin-qubutz.mp3',
		soundAudio: '/audio/sound-sin-u-short.mp3',
	},
	{
		char: 'שֹׂ',
		nameAudio: '/audio/name-sin-holam.mp3',
		soundAudio: '/audio/sound-sin-o.mp3',
	},
	{
		char: 'שְׂ',
		nameAudio: '/audio/name-sin-shva.mp3',
		soundAudio: '/audio/sound-sin-silent.mp3',
	},
	{
		char: 'שּׂ',
		nameAudio: '/audio/name-sin-dagesh.mp3',
		soundAudio: '/audio/sound-sin-emph.mp3',
	},
	{
		char: 'שֲׂ',
		nameAudio: '/audio/name-sin-chataf-patach.mp3',
		soundAudio: '/audio/sound-sin-a-reduced.mp3',
	},
	{
		char: 'שֱׂ',
		nameAudio: '/audio/name-sin-chataf-segol.mp3',
		soundAudio: '/audio/sound-sin-e-reduced.mp3',
	},
	{
		char: 'שֳׂ',
		nameAudio: '/audio/name-sin-chataf-qamats.mp3',
		soundAudio: '/audio/sound-sin-o-reduced.mp3',
	},
	{
		char: 'שִׂי',
		nameAudio: '/audio/name-sin-hiriq-yod.mp3',
		soundAudio: '/audio/sound-sin-i-long.mp3',
	},
	{
		char: 'שֵׂי',
		nameAudio: '/audio/name-sin-tsere-yod.mp3',
		soundAudio: '/audio/sound-sin-ei.mp3',
	},
	{
		char: 'שֶׂי',
		nameAudio: '/audio/name-sin-segol-yod.mp3',
		soundAudio: '/audio/sound-sin-ei-segol.mp3',
	},
	{
		char: 'שׂ',
		nameAudio: '/audio/name-sin-base.mp3',
		soundAudio: '/audio/sound-sin-base.mp3',
		category: 'base',
	},
	{
		char: 'תַ',
		nameAudio: '/audio/name-thav-patach.mp3',
		soundAudio: '/audio/sound-thav-a.mp3',
	},
	{
		char: 'תָ',
		nameAudio: '/audio/name-thav-qamats.mp3',
		soundAudio: '/audio/sound-thav-a-long.mp3',
	},
	{
		char: 'תֶ',
		nameAudio: '/audio/name-thav-segol.mp3',
		soundAudio: '/audio/sound-thav-e.mp3',
	},
	{
		char: 'תֵ',
		nameAudio: '/audio/name-thav-tsere.mp3',
		soundAudio: '/audio/sound-thav-e-long.mp3',
	},
	{
		char: 'תִ',
		nameAudio: '/audio/name-thav-hiriq.mp3',
		soundAudio: '/audio/sound-thav-i.mp3',
	},
	{
		char: 'תֻ',
		nameAudio: '/audio/name-thav-qubutz.mp3',
		soundAudio: '/audio/sound-thav-u-short.mp3',
	},
	{
		char: 'תֹ',
		nameAudio: '/audio/name-thav-holam.mp3',
		soundAudio: '/audio/sound-thav-o.mp3',
	},
	{
		char: 'תְ',
		nameAudio: '/audio/name-thav-shva.mp3',
		soundAudio: '/audio/sound-thav-silent.mp3',
	},
	{
		char: 'תּ',
		nameAudio: '/audio/name-thav-dagesh.mp3',
		soundAudio: '/audio/sound-thav-emph.mp3',
	},
	{
		char: 'תֲ',
		nameAudio: '/audio/name-thav-chataf-patach.mp3',
		soundAudio: '/audio/sound-thav-a-reduced.mp3',
	},
	{
		char: 'תֱ',
		nameAudio: '/audio/name-thav-chataf-segol.mp3',
		soundAudio: '/audio/sound-thav-e-reduced.mp3',
	},
	{
		char: 'תֳ',
		nameAudio: '/audio/name-thav-chataf-qamats.mp3',
		soundAudio: '/audio/sound-thav-o-reduced.mp3',
	},
	{
		char: 'תִי',
		nameAudio: '/audio/name-thav-hiriq-yod.mp3',
		soundAudio: '/audio/sound-thav-i-long.mp3',
	},
	{
		char: 'תֵי',
		nameAudio: '/audio/name-thav-tsere-yod.mp3',
		soundAudio: '/audio/sound-thav-ei.mp3',
	},
	{
		char: 'תֶי',
		nameAudio: '/audio/name-thav-segol-yod.mp3',
		soundAudio: '/audio/sound-thav-ei-segol.mp3',
	},
	{
		char: 'ת',
		nameAudio: '/audio/name-thav-base.mp3',
		soundAudio: '/audio/sound-thav-base.mp3',
		category: 'base',
	},
	{
		char: 'תַּ',
		nameAudio: '/audio/name-tav-patach.mp3',
		soundAudio: '/audio/sound-tav-a.mp3',
	},
	{
		char: 'תָּ',
		nameAudio: '/audio/name-tav-qamats.mp3',
		soundAudio: '/audio/sound-tav-a-long.mp3',
	},
	{
		char: 'תֶּ',
		nameAudio: '/audio/name-tav-segol.mp3',
		soundAudio: '/audio/sound-tav-e.mp3',
	},
	{
		char: 'תֵּ',
		nameAudio: '/audio/name-tav-tsere.mp3',
		soundAudio: '/audio/sound-tav-e-long.mp3',
	},
	{
		char: 'תִּ',
		nameAudio: '/audio/name-tav-hiriq.mp3',
		soundAudio: '/audio/sound-tav-i.mp3',
	},
	{
		char: 'תֻּ',
		nameAudio: '/audio/name-tav-qubutz.mp3',
		soundAudio: '/audio/sound-tav-u-short.mp3',
	},
	{
		char: 'תֹּ',
		nameAudio: '/audio/name-tav-holam.mp3',
		soundAudio: '/audio/sound-tav-o.mp3',
	},
	{
		char: 'תְּ',
		nameAudio: '/audio/name-tav-shva.mp3',
		soundAudio: '/audio/sound-tav-silent.mp3',
	},
	{
		char: 'תּּ',
		nameAudio: '/audio/name-tav-dagesh.mp3',
		soundAudio: '/audio/sound-tav-emph.mp3',
	},
	{
		char: 'תֲּ',
		nameAudio: '/audio/name-tav-chataf-patach.mp3',
		soundAudio: '/audio/sound-tav-a-reduced.mp3',
	},
	{
		char: 'תֱּ',
		nameAudio: '/audio/name-tav-chataf-segol.mp3',
		soundAudio: '/audio/sound-tav-e-reduced.mp3',
	},
	{
		char: 'תֳּ',
		nameAudio: '/audio/name-tav-chataf-qamats.mp3',
		soundAudio: '/audio/sound-tav-o-reduced.mp3',
	},
	{
		char: 'תִּי',
		nameAudio: '/audio/name-tav-hiriq-yod.mp3',
		soundAudio: '/audio/sound-tav-i-long.mp3',
	},
	{
		char: 'תֵּי',
		nameAudio: '/audio/name-tav-tsere-yod.mp3',
		soundAudio: '/audio/sound-tav-ei.mp3',
	},
	{
		char: 'תֶּי',
		nameAudio: '/audio/name-tav-segol-yod.mp3',
		soundAudio: '/audio/sound-tav-ei-segol.mp3',
	},
	{
		char: 'תּ',
		nameAudio: '/audio/name-tav-base.mp3',
		soundAudio: '/audio/sound-tav-base.mp3',
		category: 'base',
	},
]
