export type VocabEntry = {
	id: number
	word: string
	gender: 'm' | 'f' | 'mf' | string
	quantity: 's' | 'p'
	type: 'noun' | 'adjective' | 'demonstrative' | string
}

export const vocab = [
	{
		id: 1,
		word: 'אִישׁ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 2,
		word: 'אֵלֶּה',
		gender: 'mf',
		quantity: 'p',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 3,
		word: 'אֲנָשִׁים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 4,
		word: 'אִשָּׁה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 5,
		word: 'גַּדוֹל',
		gender: 'm',
		quantity: 's',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 6,
		word: 'גְּדוֹלָה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 7,
		word: 'גְּדֹלוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 8,
		word: 'גְּדֹלִים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 9,
		word: 'גְּמַלִּים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 10,
		word: 'הָאִישׁ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 11,
		word: 'הָאֵלֶּה',
		gender: 'mf',
		quantity: 'p',
		type: 'demonstrative',
		levels: [5, 6, 7, 8, 9],
	},
	{
		id: 12,
		word: 'הָאֲנָשִׁים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 13,
		word: 'הָאִשָּׁה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 14,
		word: 'הַגַּדוֹל',
		gender: 'm',
		quantity: 's',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	// {
	// 	id: 15,
	// 	word: 'הַגָּדוֹל',
	// 	gender: 'm',
	// 	quantity: 's',
	// 	type: 'adjective',
	// 	levels: [2, 3, 4, 5, 6, 7, 8, 9],
	// },
	{
		id: 16,
		word: 'הַגְּדוֹלָה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 17,
		word: 'הַגְּדֹלוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 18,
		word: 'הַגְּדֹלִים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 19,
		word: 'הַגְּמַלִּים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 20,
		word: 'הַהֲמוֹר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 21,
		word: 'הַזֹּאת',
		gender: 'f',
		quantity: 's',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 22,
		word: 'הַזֶּה',
		gender: 'm',
		quantity: 's',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 23,
		word: 'הַחֲמוֹרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 24,
		word: 'הַכֶּ֫בֶשׂ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 25,
		word: 'הַכְּבָשִׂים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 26,
		word: 'הֲמוֹר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 27,
		word: 'הַנְּעָרוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 28,
		word: 'הַנְּעָרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 29,
		word: 'הַנָּשִׁים',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 30,
		word: 'הַסוּס',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 31,
		word: 'הַסּוּסִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 32,
		word: 'הַעֵז',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 33,
		word: 'הָעִזִּים',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 34,
		word: 'הַפַּר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 35,
		word: 'הַפָּרָה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 36,
		word: 'הַפָּרוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 37,
		word: 'הַפָּרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 38,
		word: 'הַקָּטֹן',
		gender: 'm',
		quantity: 's',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 39,
		word: 'הַקְּטַנָּה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 40,
		word: 'הַקְּטַנּוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 41,
		word: 'הַקְּטַנִּים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 42,
		word: 'זֹאת',
		gender: 'f',
		quantity: 's',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 43,
		word: 'זֶה',
		gender: 'm',
		quantity: 's',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 44,
		word: 'חֲמוֹרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 45,
		word: 'כֶּ֫בֶשׂ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 46,
		word: 'כְּבָשִׂים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 47,
		word: 'נְעָרוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 48,
		word: 'נְעָרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 49,
		word: 'נָשִׁים',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 50,
		word: 'סוּס',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 51,
		word: 'סוּסִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 52,
		word: 'עֵז',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 53,
		word: 'עִזִּים',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 54,
		word: 'פַּר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 55,
		word: 'פָּרָה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 56,
		word: 'פָּרוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 57,
		word: 'פָּרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 58,
		word: 'קָטֹן',
		gender: 'm',
		quantity: 's',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 59,
		word: 'קְטַנָּה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 60,
		word: 'קְטַנּוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 61,
		word: 'קְטַנִּים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
] as const
