export type VocabEntry = {
	id: number
	word: string
	gender: 'm' | 'f' | 'mf' | string
	quantity: 's' | 'p'
	type: 'noun' | 'adjective' | 'demonstrative' | string
}

export const vocab = [
	{ id: 1, word: 'אִישׁ', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 2, word: 'אֵלֶּה', gender: 'mf', quantity: 'p', type: 'demonstrative' },
	{ id: 3, word: 'אֲנָשִׁים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 4, word: 'אִשָּׁה', gender: 'f', quantity: 's', type: 'noun' },
	{ id: 5, word: 'גַּדוֹל', gender: 'm', quantity: 's', type: 'adjective' },
	{ id: 6, word: 'גְּדוֹלָה', gender: 'f', quantity: 's', type: 'adjective' },
	{ id: 7, word: 'גְּדֹלוֹת', gender: 'f', quantity: 'p', type: 'adjective' },
	{ id: 8, word: 'גְּדֹלִים', gender: 'm', quantity: 'p', type: 'adjective' },
	{ id: 9, word: 'גְּמַלִּים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 10, word: 'הָאִישׁ', gender: 'm', quantity: 's', type: 'noun' },
	{
		id: 11,
		word: 'הָאֵלֶּה',
		gender: 'mf',
		quantity: 'p',
		type: 'demonstrative',
	},
	{ id: 12, word: 'הָאֲנָשִׁים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 13, word: 'הָאִשָּׁה', gender: 'f', quantity: 's', type: 'noun' },
	{ id: 14, word: 'הַגַּדוֹל', gender: 'm', quantity: 's', type: 'adjective' },
	{ id: 15, word: 'הַגָּדוֹל', gender: 'm', quantity: 's', type: 'adjective' },
	{
		id: 16,
		word: 'הַגְּדוֹלָה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
	},
	{
		id: 17,
		word: 'הַגְּדֹלוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
	},
	{
		id: 18,
		word: 'הַגְּדֹלִים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
	},
	{ id: 19, word: 'הַגְּמַלִּים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 20, word: 'הַהֲמוֹר', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 21, word: 'הַזֹּאת', gender: 'f', quantity: 's', type: 'demonstrative' },
	{ id: 22, word: 'הַזֶּה', gender: 'm', quantity: 's', type: 'demonstrative' },
	{ id: 23, word: 'הַחֲמוֹרִים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 24, word: 'הַכֶּ֫בֶשׂ', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 25, word: 'הַכְּבָשִׂים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 26, word: 'הֲמוֹר', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 27, word: 'הַנְּעָרוֹת', gender: 'f', quantity: 'p', type: 'noun' },
	{ id: 28, word: 'הַנְּעָרִים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 29, word: 'הַנָּשִׁים', gender: 'f', quantity: 'p', type: 'noun' },
	{ id: 30, word: 'הַסוּס', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 31, word: 'הַסּוּסִים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 32, word: 'הַעֵז', gender: 'f', quantity: 's', type: 'noun' },
	{ id: 33, word: 'הָעִזִּים', gender: 'f', quantity: 'p', type: 'noun' },
	{ id: 34, word: 'הַפַּר', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 35, word: 'הַפָּרָה', gender: 'f', quantity: 's', type: 'noun' },
	{ id: 36, word: 'הַפָּרוֹת', gender: 'f', quantity: 'p', type: 'noun' },
	{ id: 37, word: 'הַפָּרִים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 38, word: 'הַקָּטֹן', gender: 'm', quantity: 's', type: 'adjective' },
	{ id: 39, word: 'הַקְּטַנָּה', gender: 'f', quantity: 's', type: 'adjective' },
	{
		id: 40,
		word: 'הַקְּטַנּוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
	},
	{
		id: 41,
		word: 'הַקְּטַנִּים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
	},
	{ id: 42, word: 'זֹאת', gender: 'f', quantity: 's', type: 'demonstrative' },
	{ id: 43, word: 'זֶה', gender: 'm', quantity: 's', type: 'demonstrative' },
	{ id: 44, word: 'חֲמוֹרִים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 45, word: 'כֶּ֫בֶשׂ', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 46, word: 'כְּבָשִׂים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 47, word: 'נְעָרוֹת', gender: 'f', quantity: 'p', type: 'noun' },
	{ id: 48, word: 'נְעָרִים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 49, word: 'נָשִׁים', gender: 'f', quantity: 'p', type: 'noun' },
	{ id: 50, word: 'סוּס', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 51, word: 'סוּסִים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 52, word: 'עֵז', gender: 'f', quantity: 's', type: 'noun' },
	{ id: 53, word: 'עִזִּים', gender: 'f', quantity: 'p', type: 'noun' },
	{ id: 54, word: 'פַּר', gender: 'm', quantity: 's', type: 'noun' },
	{ id: 55, word: 'פָּרָה', gender: 'f', quantity: 's', type: 'noun' },
	{ id: 56, word: 'פָּרוֹת', gender: 'f', quantity: 'p', type: 'noun' },
	{ id: 57, word: 'פָּרִים', gender: 'm', quantity: 'p', type: 'noun' },
	{ id: 58, word: 'קָטֹן', gender: 'm', quantity: 's', type: 'adjective' },
	{ id: 59, word: 'קְטַנָּה', gender: 'f', quantity: 's', type: 'adjective' },
	{ id: 60, word: 'קְטַנּוֹת', gender: 'f', quantity: 'p', type: 'adjective' },
	{ id: 61, word: 'קְטַנִּים', gender: 'm', quantity: 'p', type: 'adjective' },
] as const
