export type VocabEntry = {
	id: number
	word: string
	gender: 'm' | 'f' | 'mf' | string
	quantity: 's' | 'p'
	type: 'noun' | 'adjective' | 'demonstrative' | string
}

export const vocab = [
	{
		id: 1,
		word: 'אִישׁ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 2,
		word: 'אֵלֶּה',
		gender: 'mf',
		quantity: 'p',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 3,
		word: 'אֲנָשִׁים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 4,
		word: 'אִשָּׁה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 5,
		word: 'גַּדוֹל',
		gender: 'm',
		quantity: 's',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 6,
		word: 'גְּדוֹלָה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 7,
		word: 'גְּדֹלוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 8,
		word: 'גְּדֹלִים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 9,
		word: 'גְּמַלִּים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 10,
		word: 'הָאִישׁ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 11,
		word: 'הָאֵלֶּה',
		gender: 'mf',
		quantity: 'p',
		type: 'demonstrative',
		levels: [5, 6, 7, 8, 9],
	},
	{
		id: 12,
		word: 'הָאֲנָשִׁים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 13,
		word: 'הָאִשָּׁה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 14,
		word: 'הַגַּדוֹל',
		gender: 'm',
		quantity: 's',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	// {
	// 	id: 15,
	// 	word: 'הַגָּדוֹל',
	// 	gender: 'm',
	// 	quantity: 's',
	// 	type: 'adjective',
	// 	levels: [2, 3, 4, 5, 6, 7, 8, 9],
	// },
	{
		id: 16,
		word: 'הַגְּדוֹלָה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 17,
		word: 'הַגְּדֹלוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 18,
		word: 'הַגְּדֹלִים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 19,
		word: 'הַגְּמַלִּים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 20,
		word: 'הַהֲמוֹר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 21,
		word: 'הַזֹּאת',
		gender: 'f',
		quantity: 's',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 22,
		word: 'הַזֶּה',
		gender: 'm',
		quantity: 's',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 23,
		word: 'הַחֲמוֹרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 24,
		word: 'הַכֶּ֫בֶשׂ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 25,
		word: 'הַכְּבָשִׂים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 26,
		word: 'הֲמוֹר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 27,
		word: 'הַנְּעָרוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 28,
		word: 'הַנְּעָרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 29,
		word: 'הַנָּשִׁים',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 30,
		word: 'הַסוּס',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 31,
		word: 'הַסּוּסִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 32,
		word: 'הַעֵז',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 33,
		word: 'הָעִזִּים',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 34,
		word: 'הַפַּר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 35,
		word: 'הַפָּרָה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 36,
		word: 'הַפָּרוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 37,
		word: 'הַפָּרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 38,
		word: 'הַקָּטֹן',
		gender: 'm',
		quantity: 's',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 39,
		word: 'הַקְּטַנָּה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 40,
		word: 'הַקְּטַנּוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 41,
		word: 'הַקְּטַנִּים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
		levels: [2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 42,
		word: 'זֹאת',
		gender: 'f',
		quantity: 's',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 43,
		word: 'זֶה',
		gender: 'm',
		quantity: 's',
		type: 'demonstrative',
		levels: [4, 5, 6, 7, 8, 9],
	},
	{
		id: 44,
		word: 'חֲמוֹרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 45,
		word: 'כֶּ֫בֶשׂ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 46,
		word: 'כְּבָשִׂים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 47,
		word: 'נְעָרוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 48,
		word: 'נְעָרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 49,
		word: 'נָשִׁים',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 50,
		word: 'סוּס',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 51,
		word: 'סוּסִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 52,
		word: 'עֵז',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 53,
		word: 'עִזִּים',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 54,
		word: 'פַּר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 55,
		word: 'פָּרָה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 56,
		word: 'פָּרוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 57,
		word: 'פָּרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
	{
		id: 58,
		word: 'קָטֹן',
		gender: 'm',
		quantity: 's',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 59,
		word: 'קְטַנָּה',
		gender: 'f',
		quantity: 's',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 60,
		word: 'קְטַנּוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 61,
		word: 'קְטַנִּים',
		gender: 'm',
		quantity: 'p',
		type: 'adjective',
		levels: [1, 2, 3, 4, 5, 6, 7, 8, 9],
	},
	{
		id: 62,
		word: 'אָב',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 63,
		word: 'אֲבִי',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 64,
		word: 'אָח',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 65,
		word: 'אֲחִי',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 66,
		word: 'אָחוֹת',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 67,
		word: 'אֲחוֹת',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 68,
		word: 'אֵשֶׁת',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 69,
		word: 'אֵם',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 70,
		word: 'בֵּן',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 71,
		word: 'בֶּן־',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 72,
		word: 'בַּת',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 73,
		word: 'מֶ֫לֶךְ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 74,
		word: 'שֵׁם',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 75,
		word: 'שְׁמִי',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 76,
		word: 'שְׁמוֹ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 77,
		word: 'שְׁמָה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 78,
		word: 'דֶּ֫רֶךְ',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 79,
		word: 'הַר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 80,
		word: 'מִדְבָּר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 81,
		word: 'עֵץ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 82,
		word: 'שָׂדֶה',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 83,
		word: 'אֹ֫זֶן',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 84,
		word: 'אָזְנַ֫יִם',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 85,
		word: 'אַף',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 86,
		word: 'בֶּ֫טֶן',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 87,
		word: 'יָד',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 88,
		word: 'יַד',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 89,
		word: 'יָדַ֫יִם',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 90,
		word: 'עֵינַ֫יִם',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 91,
		word: 'כַּף',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 92,
		word: 'כַּף־רֶ֫גֶל',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 93,
		word: 'כַּפַּ֫יִם',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 94,
		word: 'עַ֫יִן',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 95,
		word: 'פֶּה',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 96,
		word: 'פָּנִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 97,
		word: 'רֹאשׁ',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 98,
		word: 'רֶ֫גֶל',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 99,
		word: 'רַגְלַיִם',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 100,
		word: 'שָׂפָה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 101,
		word: 'שְׂפָתַיִם',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 102,
		word: 'דָּבָר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 103,
		word: 'דְּבָרִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 104,
		word: 'כַּד',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 105,
		word: 'בָּנִים',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 106,
		word: 'בָּנוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 107,
		word: 'אָהֳלֵי',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 108,
		word: 'בֵּית',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 109,
		word: 'נְשֵׁי',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 110,
		word: 'בְּנֵי',
		gender: 'm',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 111,
		word: 'בְּנוֹת',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 112,
		word: 'עֵינֵי',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 113,
		word: 'פָּרַת',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 114,
		word: 'נַעֲרָה',
		gender: 'f',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 115,
		word: 'נַעַר',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 116,
		word: 'רַגְלֵי',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 117,
		word: 'אָזְנֵי',
		gender: 'f',
		quantity: 'p',
		type: 'noun',
		levels: [10, 11],
	},
	{
		id: 118,
		word: 'גָּמָל',
		gender: 'm',
		quantity: 's',
		type: 'noun',
		levels: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
	},
] as const
