export const phrases = [
	{
		hebrew: 'אִישׁ גַּדוֹל',
		english: 'big man',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'כֶּ֫בֶשׂ גַּדוֹל',
		english: 'big lamb',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'סוּס גַּדוֹל',
		english: 'big horse',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'פַּר גַּדוֹל',
		english: 'big bull',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'הֲמוֹר גַּדוֹל',
		english: 'big donkey',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'עֵז גְּדוֹלָה',
		english: 'big goat',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'פָּרָה גְּדוֹלָה',
		english: 'big cow',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'אִשָּׁה גְּדוֹלָה',
		english: 'big woman',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'אִישׁ קָטֹן',
		english: 'small man',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'כֶּ֫בֶשׂ קָטֹן',
		english: 'small lamb',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'סוּס קָטֹן',
		english: 'small horse',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'פַּר קָטֹן',
		english: 'small bull',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'הֲמוֹר קָטֹן',
		english: 'small donkey',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'עֵז קְטַנָּה',
		english: 'small goat',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'פָּרָה קְטַנָּה',
		english: 'small cow',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'אִשָּׁה קְטַנָּה',
		english: 'small woman',
		level: 1,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ גַּדוֹל',
		english: 'The man (is) big',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ גַּדוֹל',
		english: 'The lamb (is) big',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס גַּדוֹל',
		english: 'The horse (is) big',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר גַּדוֹל',
		english: 'The bull (is) big',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר גַּדוֹל',
		english: 'The donkey (is) big',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז גְּדוֹלָה',
		english: 'The goat (is) big',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה גְּדוֹלָה',
		english: 'The cow (is) big',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה גְּדוֹלָה',
		english: 'The woman (is) big',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ קָטֹן',
		english: 'The man (is) small',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ קָטֹן',
		english: 'The lamb (is) small',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס קָטֹן',
		english: 'The horse (is) small',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר קָטֹן',
		english: 'The bull (is) small',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר קָטֹן',
		english: 'The donkey (is) small',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז קְטַנָּה',
		english: 'The goat (is) small',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה קְטַנָּה',
		english: 'The cow (is) small',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה קְטַנָּה',
		english: 'The woman (is) small',
		level: 3,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ הַגַּדוֹל',
		english: 'the big man',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ הַגַּדוֹל',
		english: 'the big lamb',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס הַגַּדוֹל',
		english: 'the big horse',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר הַגַּדוֹל',
		english: 'the big bull',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר הַגַּדוֹל',
		english: 'the big donkey',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז הַגְּדוֹלָה',
		english: 'the big goat',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה הַגְּדוֹלָה',
		english: 'the big cow',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה הַגְּדוֹלָה',
		english: 'the big woman',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ הַקָּטֹן',
		english: 'the small man',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ הַקָּטֹן',
		english: 'the small lamb',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס הַקָּטֹן',
		english: 'the small horse',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר הַקָּטֹן',
		english: 'the small bull',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר הַקָּטֹן',
		english: 'the small donkey',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז הַקְּטַנָּה',
		english: 'the small goat',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה הַקְּטַנָּה',
		english: 'the small cow',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה הַקְּטַנָּה',
		english: 'the small woman',
		level: 2,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ הַגָּדוֹל הַזֶּה',
		english: 'this big man',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ הַגָּדוֹל הַזֶּה',
		english: 'this big lamb',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס הַגָּדוֹל הַזֶּה',
		english: 'this big horse',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר הַגָּדוֹל הַזֶּה',
		english: 'this big bull',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר הַגָּדוֹל הַזֶּה',
		english: 'this big donkey',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז הַגְּדוֹלָה הַזֹּאת',
		english: 'this big goat',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה הַגְּדוֹלָה הַזֹּאת',
		english: 'this big cow',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה הַגְּדוֹלָה הַזֹּאת',
		english: 'this big woman',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ הַקָּטֹן הַזֶּה',
		english: 'this small man',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ הַקָּטֹן הַזֶּה',
		english: 'this small lamb',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס הַקָּטֹן הַזֶּה',
		english: 'this small horse',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר הַקָּטֹן הַזֶּה',
		english: 'this small bull',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר הַקָּטֹן הַזֶּה',
		english: 'this small donkey',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז הַקְּטַנָּה הַזֹּאת',
		english: 'this small goat',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה הַקְּטַנָּה הַזֹּאת',
		english: 'this small cow',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה הַקְּטַנָּה הַזֹּאת',
		english: 'this small woman',
		level: 6,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הָאִישׁ הַגָּדוֹל',
		english: 'This (is) the big man',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הַכֶּ֫בֶשׂ הַגָּדוֹל',
		english: 'This (is) the big lamb',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הַסוּס הַגָּדוֹל',
		english: 'This (is) the big horse',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הַפַּר הַגָּדוֹל',
		english: 'This (is) the big bull',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הַהֲמוֹר הַגָּדוֹל',
		english: 'This (is) the big donkey',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת הַעֵז הַגְּדוֹלָה',
		english: 'This (is) the big goat',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת הַפָּרָה הַגְּדוֹלָה',
		english: 'This (is) the big cow',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת הָאִשָּׁה הַגְּדוֹלָה',
		english: 'This (is) the big woman',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הָאִישׁ הַקָּטֹן',
		english: 'This (is) the small man',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הַכֶּ֫בֶשׂ הַקָּטֹן',
		english: 'This (is) the small lamb',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הַסוּס הַקָּטֹן',
		english: 'This (is) the small horse',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הַפַּר הַקָּטֹן',
		english: 'This (is) the small bull',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הַהֲמוֹר הַקָּטֹן',
		english: 'This (is) the small donkey',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת הַעֵז הַקְּטַנָּה',
		english: 'This (is) the small goat',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת הַפָּרָה הַקְּטַנָּה',
		english: 'This (is) the small cow',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת הָאִשָּׁה הַקְּטַנָּה',
		english: 'This (is) the small woman',
		level: 9,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ הַזֶּה גַּדוֹל',
		english: 'This man (is) big',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ הַזֶּה גַּדוֹל',
		english: 'This lamb (is) big',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס הַזֶּה גַּדוֹל',
		english: 'This horse (is) big',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר הַזֶּה גַּדוֹל',
		english: 'This bull (is) big',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר הַזֶּה גַּדוֹל',
		english: 'This donkey (is) big',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז הַזֹּאת גְּדוֹלָה',
		english: 'This goat (is) big',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה הַזֹּאת גְּדוֹלָה',
		english: 'This cow (is) big',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה הַזֹּאת גְּדוֹלָה',
		english: 'This woman (is) big',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ הַזֶּה קָטֹן',
		english: 'This man (is) small',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ הַזֶּה קָטֹן',
		english: 'This lamb (is) small',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס הַזֶּה קָטֹן',
		english: 'This horse (is) small',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר הַזֶּה קָטֹן',
		english: 'This bull (is) small',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר הַזֶּה קָטֹן',
		english: 'This donkey (is) small',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז הַזֹּאת קְטַנָּה',
		english: 'This goat (is) small',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה הַזֹּאת קְטַנָּה',
		english: 'This cow (is) small',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה הַזֹּאת קְטַנָּה',
		english: 'This woman (is) small',
		level: 7,
		quantity: 's',
	},
	{
		hebrew: 'זֶה אִישׁ ',
		english: 'This (is) a man',
		level: 4,
		quantity: 's',
	},
	{
		hebrew: 'זֶה כֶּ֫בֶשׂ ',
		english: 'This (is) a lamb',
		level: 4,
		quantity: 's',
	},
	{
		hebrew: 'זֶה סוּס ',
		english: 'This (is) a horse',
		level: 4,
		quantity: 's',
	},
	{
		hebrew: 'זֶה פַּר ',
		english: 'This (is) a bull',
		level: 4,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הֲמוֹר ',
		english: 'This (is) a donkey',
		level: 4,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת עֵז ',
		english: 'This (is) a goat',
		level: 4,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת פָּרָה ',
		english: 'This (is) a cow',
		level: 4,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת אִשָּׁה ',
		english: 'This (is) a woman',
		level: 4,
		quantity: 's',
	},
	{
		hebrew: 'הָאִישׁ הַזֶּה ',
		english: 'This man',
		level: 5,
		quantity: 's',
	},
	{
		hebrew: 'הַכֶּ֫בֶשׂ הַזֶּה ',
		english: 'This lamb',
		level: 5,
		quantity: 's',
	},
	{
		hebrew: 'הַסוּס הַזֶּה ',
		english: 'This horse',
		level: 5,
		quantity: 's',
	},
	{
		hebrew: 'הַפַּר הַזֶּה ',
		english: 'This bull',
		level: 5,
		quantity: 's',
	},
	{
		hebrew: 'הַהֲמוֹר הַזֶּה ',
		english: 'This donkey',
		level: 5,
		quantity: 's',
	},
	{
		hebrew: 'הַעֵז הַזֹּאת ',
		english: 'This goat',
		level: 5,
		quantity: 's',
	},
	{
		hebrew: 'הַפָּרָה הַזֹּאת ',
		english: 'This cow',
		level: 5,
		quantity: 's',
	},
	{
		hebrew: 'הָאִשָּׁה הַזֹּאת ',
		english: 'This woman',
		level: 5,
		quantity: 's',
	},
	{
		hebrew: 'זֶה אִישׁ גַּדוֹל',
		english: 'This (is a) big man',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֶה כֶּ֫בֶשׂ גַּדוֹל',
		english: 'This (is a) big lamb',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֶה סוּס גַּדוֹל',
		english: 'This (is a) big horse',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֶה פַּר גַּדוֹל',
		english: 'This (is a) big bull',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הֲמוֹר גַּדוֹל',
		english: 'This (is a) big donkey',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת עֵז גְּדוֹלָה',
		english: 'This (is a) big goat',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת פָּרָה גְּדוֹלָה',
		english: 'This (is a) big cow',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת אִשָּׁה גְּדוֹלָה',
		english: 'This (is a) big woman',
		level: 8,
		quantity: 's',
	},

	{
		hebrew: 'זֶה כֶּ֫בֶשׂ קָטֹן',
		english: 'This (is a) small lamb',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֶה סוּס קָטֹן',
		english: 'This (is a) small horse',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֶה פַּר קָטֹן',
		english: 'This (is a) small bull',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֶה הֲמוֹר קָטֹן',
		english: 'This (is a) small donkey',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת עֵז קְטַנָּה',
		english: 'This (is a) small goat',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת פָּרָה קְטַנָּה',
		english: 'This (is a) small cow',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'זֹאת אִשָּׁה קְטַנָּה',
		english: 'This (is a) small woman',
		level: 8,
		quantity: 's',
	},
	{
		hebrew: 'אֲנָשִׁים גְּדֹלִים',
		english: 'big men',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'נְעָרִים גְּדֹלִים',
		english: 'big boys',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'כְּבָשִׂים גְּדֹלִים',
		english: 'big lambs',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'סוּסִים גְּדֹלִים',
		english: 'big horses',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'פָּרִים גְּדֹלִים',
		english: 'big bulls',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'חֲמוֹרִים גְּדֹלִים',
		english: 'big donkeys',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'גְּמַלִּים גְּדֹלִים',
		english: 'big camels',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'עִזִּים גְּדֹלוֹת',
		english: 'big goats',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'פָּרוֹת גְּדֹלוֹת',
		english: 'big cows',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'נָשִׁים גְּדֹלוֹת',
		english: 'big women',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'נְעָרוֹת גְּדֹלוֹת',
		english: 'big girls',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'אֲנָשִׁים קְטַנִּים',
		english: 'small men',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'נְעָרִים קְטַנִּים',
		english: 'small boys',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'כְּבָשִׂים קְטַנִּים',
		english: 'small lambs',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'סוּסִים קְטַנִּים',
		english: 'small horses',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'פָּרִים קְטַנִּים',
		english: 'small bulls',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'חֲמוֹרִים קְטַנִּים',
		english: 'small donkeys',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'גְּמַלִּים קְטַנִּים',
		english: 'small camels',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'עִזִּים קְטַנּוֹת',
		english: 'small goats',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'פָּרוֹת קְטַנּוֹת',
		english: 'small cows',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'נָשִׁים קְטַנּוֹת',
		english: 'small women',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'נְעָרוֹת קְטַנּוֹת',
		english: 'small girls',
		level: 1,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים גְּדֹלִים',
		english: 'The men (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים גְּדֹלִים',
		english: 'The boys (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים גְּדֹלִים',
		english: 'The lambs (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים גְּדֹלִים',
		english: 'The horses (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים גְּדֹלִים',
		english: 'The bulls (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים גְּדֹלִים',
		english: 'The donkeys (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים גְּדֹלִים',
		english: 'The camels (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים גְּדֹלוֹת',
		english: 'The goats (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת גְּדֹלוֹת',
		english: 'The cows (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים גְּדֹלוֹת',
		english: 'The women (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת גְּדֹלוֹת',
		english: 'The girls (are) big',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים קְטַנִּים',
		english: 'The men (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים קְטַנִּים',
		english: 'The boys (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים קְטַנִּים',
		english: 'The lambs (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים קְטַנִּים',
		english: 'The horses (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים קְטַנִּים',
		english: 'The bulls (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים קְטַנִּים',
		english: 'The donkeys (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים קְטַנִּים',
		english: 'The camels (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים קְטַנּוֹת',
		english: 'The goats (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת קְטַנּוֹת',
		english: 'The cows (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים קְטַנּוֹת',
		english: 'The women (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת קְטַנּוֹת',
		english: 'The girls (are) small',
		level: 3,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים הַגְּדֹלִים',
		english: 'The big men',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים הַגְּדֹלִים',
		english: 'The big boys',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים הַגְּדֹלִים',
		english: 'The big lambs',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים הַגְּדֹלִים',
		english: 'The big horses',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים הַגְּדֹלִים',
		english: 'The big bulls',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים הַגְּדֹלִים',
		english: 'The big donkeys',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים הַגְּדֹלִים',
		english: 'The big camels',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים הַגְּדֹלוֹת',
		english: 'The big goats',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת הַגְּדֹלוֹת',
		english: 'The big cows',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים הַגְּדֹלוֹת',
		english: 'The big women',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת הַגְּדֹלוֹת',
		english: 'The big girls',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים הַקְּטַנִּים',
		english: 'The small men',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים הַקְּטַנִּים',
		english: 'The small boys',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים הַקְּטַנִּים',
		english: 'The small lambs',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים הַקְּטַנִּים',
		english: 'The small horses',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים הַקְּטַנִּים',
		english: 'The small bulls',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים הַקְּטַנִּים',
		english: 'The small donkeys',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים הַקְּטַנִּים',
		english: 'The small camels',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים הַקְּטַנּוֹת',
		english: 'The small goats',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת הַקְּטַנּוֹת',
		english: 'The small cows',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים הַקְּטַנּוֹת',
		english: 'The small women',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת הַקְּטַנּוֹת',
		english: 'The small girls',
		level: 2,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים הַגְּדֹלִים הָאֵלֶּה',
		english: 'these big men',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים הַגְּדֹלִים הָאֵלֶּה',
		english: 'these big boys',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים הַגְּדֹלִים הָאֵלֶּה',
		english: 'these big lambs',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים הַגְּדֹלִים הָאֵלֶּה',
		english: 'these big horses',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים הַגְּדֹלִים הָאֵלֶּה',
		english: 'these big bulls',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים הַגְּדֹלִים הָאֵלֶּה',
		english: 'these big donkeys',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים הַגְּדֹלִים הָאֵלֶּה',
		english: 'these big camels',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים הַגְּדֹלוֹת הָאֵלֶּה',
		english: 'these big goats',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת הַגְּדֹלוֹת הָאֵלֶּה',
		english: 'these big cows',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים הַגְּדֹלוֹת הָאֵלֶּה',
		english: 'these big women',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת הַגְּדֹלוֹת הָאֵלֶּה',
		english: 'these big girls',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים הַקְּטַנִּים הָאֵלֶּה',
		english: 'these small men',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים הַקְּטַנִּים הָאֵלֶּה',
		english: 'these small boys',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים הַקְּטַנִּים הָאֵלֶּה',
		english: 'these small lambs',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים הַקְּטַנִּים הָאֵלֶּה',
		english: 'these small horses',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים הַקְּטַנִּים הָאֵלֶּה',
		english: 'these small bulls',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים הַקְּטַנִּים הָאֵלֶּה',
		english: 'these small donkeys',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים הַקְּטַנִּים הָאֵלֶּה',
		english: 'these small camels',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים הַקְּטַנּוֹת הָאֵלֶּה',
		english: 'these small goats',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת הַקְּטַנּוֹת הָאֵלֶּה',
		english: 'these small cows',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים הַקְּטַנּוֹת הָאֵלֶּה',
		english: 'these small women',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת הַקְּטַנּוֹת הָאֵלֶּה',
		english: 'these small girls',
		level: 6,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הָאֲנָשִׁים הַגְּדֹלִים',
		english: 'These (are) the big men',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַנְּעָרִים הַגְּדֹלִים',
		english: 'These (are) the big boys',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַכְּבָשִׂים הַגְּדֹלִים',
		english: 'These (are) the big lambs',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַסּוּסִים הַגְּדֹלִים',
		english: 'These (are) the big horses',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַפָּרִים הַגְּדֹלִים',
		english: 'These (are) the big bulls',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַחֲמוֹרִים הַגְּדֹלִים',
		english: 'These (are) the big donkeys',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַגְּמַלִּים הַגְּדֹלִים',
		english: 'These (are) the big camels',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הָעִזִּים הַגְּדֹלוֹת',
		english: 'These (are) the big goats',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַפָּרוֹת הַגְּדֹלוֹת',
		english: 'These (are) the big cows',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַנָּשִׁים הַגְּדֹלוֹת',
		english: 'These (are) the big women',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַנְּעָרוֹת הַגְּדֹלוֹת',
		english: 'These (are) the big girls',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הָאֲנָשִׁים הַקְּטַנִּים',
		english: 'These (are) the small men',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַנְּעָרִים הַקְּטַנִּים',
		english: 'These (are) the small boys',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַכְּבָשִׂים הַקְּטַנִּים',
		english: 'These (are) the small lambs',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַסּוּסִים הַקְּטַנִּים',
		english: 'These (are) the small horses',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַפָּרִים הַקְּטַנִּים',
		english: 'These (are) the small bulls',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַחֲמוֹרִים הַקְּטַנִּים',
		english: 'These (are) the small donkeys',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַגְּמַלִּים הַקְּטַנִּים',
		english: 'These (are) the small camels',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הָעִזִּים הַקְּטַנּוֹת',
		english: 'These (are) the small goats',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַפָּרוֹת הַקְּטַנּוֹת',
		english: 'These (are) the small cows',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַנָּשִׁים הַקְּטַנּוֹת',
		english: 'These (are) the small women',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה הַנְּעָרוֹת הַקְּטַנּוֹת',
		english: 'These (are) the small girls',
		level: 9,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים הָאֵלֶּה גְּדֹלִים',
		english: 'These men (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים הָאֵלֶּה גְּדֹלִים',
		english: 'These boys (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים הָאֵלֶּה גְּדֹלִים',
		english: 'These lambs (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים הָאֵלֶּה גְּדֹלִים',
		english: 'These horses (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים הָאֵלֶּה גְּדֹלִים',
		english: 'These bulls (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים הָאֵלֶּה גְּדֹלִים',
		english: 'These donkeys (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים הָאֵלֶּה גְּדֹלִים',
		english: 'These camels (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים הָאֵלֶּה גְּדֹלוֹת',
		english: 'These goats (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת הָאֵלֶּה גְּדֹלוֹת',
		english: 'These cows (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים הָאֵלֶּה גְּדֹלוֹת',
		english: 'These women (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת הָאֵלֶּה גְּדֹלוֹת',
		english: 'These girls (are) big',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים הָאֵלֶּה קְטַנִּים',
		english: 'These men (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים הָאֵלֶּה קְטַנִּים',
		english: 'These boys (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים הָאֵלֶּה קְטַנִּים',
		english: 'These lambs (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים הָאֵלֶּה קְטַנִּים',
		english: 'These horses (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים הָאֵלֶּה קְטַנִּים',
		english: 'These bulls (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים הָאֵלֶּה קְטַנִּים',
		english: 'These donkeys (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים הָאֵלֶּה קְטַנִּים',
		english: 'These camels (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים הָאֵלֶּה קְטַנּוֹת',
		english: 'These goats (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת הָאֵלֶּה קְטַנּוֹת',
		english: 'These cows (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים הָאֵלֶּה קְטַנּוֹת',
		english: 'These women (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת הָאֵלֶּה קְטַנּוֹת',
		english: 'These girls (are) small',
		level: 7,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה אֲנָשִׁים ',
		english: 'These (are) men',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נְעָרִים ',
		english: 'These (are) boys',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה כְּבָשִׂים ',
		english: 'These (are) lamb',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה סוּסִים ',
		english: 'These (are) horses',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה פָּרִים ',
		english: 'These (are) bulls',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה חֲמוֹרִים ',
		english: 'These (are) donkeys',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה גְּמַלִּים ',
		english: 'These (are) camels',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה עִזִּים ',
		english: 'These (are) goats',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה פָּרוֹת ',
		english: 'These (are) cows',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נָשִׁים ',
		english: 'These (are) women',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נְעָרוֹת ',
		english: 'These (are) girls',
		level: 4,
		quantity: 'p',
	},
	{
		hebrew: 'הָאֲנָשִׁים הָאֵלֶּה ',
		english: 'These men',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרִים הָאֵלֶּה ',
		english: 'These boys',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַכְּבָשִׂים הָאֵלֶּה ',
		english: 'These lamb',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַסּוּסִים הָאֵלֶּה ',
		english: 'These horses',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרִים הָאֵלֶּה ',
		english: 'These bulls',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַחֲמוֹרִים הָאֵלֶּה ',
		english: 'These donkeys',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַגְּמַלִּים הָאֵלֶּה ',
		english: 'These camels',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הָעִזִּים הָאֵלֶּה ',
		english: 'These goats',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַפָּרוֹת הָאֵלֶּה ',
		english: 'These cows',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַנָּשִׁים הָאֵלֶּה ',
		english: 'These women',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'הַנְּעָרוֹת הָאֵלֶּה ',
		english: 'These girls',
		level: 5,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה אֲנָשִׁים גְּדֹלִים',
		english: 'These (are) big men',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נְעָרִים גְּדֹלִים',
		english: 'These (are) big boys',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה כְּבָשִׂים גְּדֹלִים',
		english: 'These (are) big lamb',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה סוּסִים גְּדֹלִים',
		english: 'These (are) big horses',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה פָּרִים גְּדֹלִים',
		english: 'These (are) big bulls',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה חֲמוֹרִים גְּדֹלִים',
		english: 'These (are) big donkeys',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה גְּמַלִּים גְּדֹלִים',
		english: 'These (are) big camels',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה עִזִּים גְּדֹלוֹת',
		english: 'These (are) big goats',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה פָּרוֹת גְּדֹלוֹת',
		english: 'These (are) big cows',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נָשִׁים גְּדֹלוֹת',
		english: 'These (are) big women',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נְעָרוֹת גְּדֹלוֹת',
		english: 'These (are) big girls',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה אֲנָשִׁים קְטַנִּים',
		english: 'These (are) small men',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נְעָרִים קְטַנִּים',
		english: 'These (are) small boys',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה כְּבָשִׂים קְטַנִּים',
		english: 'These (are) small lamb',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה סוּסִים קְטַנִּים',
		english: 'These (are) small horses',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה פָּרִים קְטַנִּים',
		english: 'These (are) small bulls',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה חֲמוֹרִים קְטַנִּים',
		english: 'These (are) small donkeys',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה גְּמַלִּים קְטַנִּים',
		english: 'These (are) small camels',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה עִזִּים קְטַנּוֹת',
		english: 'These (are) small goats',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה פָּרוֹת קְטַנּוֹת',
		english: 'These (are) small cows',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נָשִׁים קְטַנּוֹת',
		english: 'These (are) small women',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נְעָרוֹת קְטַנּוֹת',
		english: 'These (are) small girls',
		level: 8,
		quantity: 'p',
	},
	{
		hebrew: 'אֵלֶּה נְעָרוֹת קְטַנּוֹת',
		english: 'These (are) small girls',
		level: 8,
		quantity: 'p',
	},

	{
		hebrew: 'בֵּית אָב',
		english: 'house of a father',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'בֶּן־ מֶלֶךְ',
		english: 'son of a king',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'אֵשֶׁת אִישׁ',
		english: 'wife of a man',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'יַד אָח',
		english: 'hand of a brother',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'שֵׁם נַעַר',
		english: 'name of a boy',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'פָּרַת אָב',
		english: 'cow of a father',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'אָחוֹת נַעֲרָה',
		english: 'sister of a girl',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'בַּת מֶלֶךְ',
		english: 'daughter of a king',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'רֹאשׁ גָּמָל',
		english: 'head of a camel',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'כּוֹס אֵם',
		english: 'cup of a mother',
		level: 10,
		quantity: 's',
	},
	{
		hebrew: 'בְּנֵי מֶלֶךְ',
		english: 'sons of a king',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'בְּנוֹת אִישׁ',
		english: 'daughters of a man',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'נְשֵׁי אָח',
		english: 'wives of a brother',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'אָהֳלֵי גְּמַלִּים',
		english: 'tents of camels',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'עֵינֵי נַעַר',
		english: 'eyes of a boy',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'דְּבָרִים אָב',
		english: 'words of a father',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'בָּנוֹת מֶלֶךְ',
		english: 'daughters of a king',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'רַגְלֵי פָּרָה',
		english: 'feet of a cow',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'אָזְנֵי כֶּבֶשׂ',
		english: 'ears of a sheep',
		level: 10,
		quantity: 'p',
	},
	{
		hebrew: 'כַּפַּ֫יִם אִשָּׁה',
		english: 'palms of a woman',
		level: 10,
		quantity: 'p',
	},
]
