export const hebrewNiqqud = [
	{
		char: 'אְ',
		name: 'shva',
		key: 'shva',
		soundAudio: '/alphabet/heb/shva.mp3',
		nameAudio: '/alphabet/heb/sound-alef-base.mp3',
	},
	{
		char: 'אֱ',
		name: 'Chataf Segol',
		key: 'chataf-segol',
		soundAudio: '/alphabet/heb/chataf-segol.mp3',
		nameAudio: '/alphabet/heb/sound-alef-chataf-segol.mp3',
	},
	{
		char: 'אֲ',
		name: 'Chataf Patach',
		key: 'chataf-patach',
		soundAudio: '/alphabet/heb/chataf-patach.mp3',
		nameAudio: '/alphabet/heb/sound-alef-chataf-patach.mp3',
	},
	{
		char: 'אֳ',
		name: 'Chataf Kamatz',
		key: 'chataf-kamatz',
		soundAudio: '/alphabet/heb/chataf-kamatz.mp3',
		nameAudio: '/alphabet/heb/sound-alef-chataf-qamats.mp3',
	},
	{
		char: 'אִ',
		name: 'Chiriq',
		key: 'chiriq',
		soundAudio: '/alphabet/heb/chiriq.mp3',
		nameAudio: '/alphabet/heb/sound-alef-hiriq.mp3',
	},
	{
		char: 'אִי',
		name: 'Chiriq Malei',
		key: 'chiriq-malei',
		soundAudio: '/alphabet/heb/chiriq-malei.mp3',
		nameAudio: '/alphabet/heb/sound-alef-hiriq-yod.mp3',
	},
	{
		char: 'אֵ',
		name: 'Tsere',
		key: 'tsere',
		soundAudio: '/alphabet/heb/tsere.mp3',
		nameAudio: '/alphabet/heb/sound-alef-tsere.mp3',
	},
	{
		char: 'אֵי',
		name: 'Tsere Malei',
		key: 'tsere-malei',
		soundAudio: '/alphabet/heb/tsere-malei.mp3',
		nameAudio: '/alphabet/heb/sound-alef-tsere-yod.mp3',
	},
	{
		char: 'אֶ',
		name: 'Segol',
		key: 'segol',
		soundAudio: '/alphabet/heb/segol.mp3',
		nameAudio: '/alphabet/heb/sound-alef-segol.mp3',
	},
	{
		char: 'אֶי',
		name: 'Segol Malei',
		key: 'segol-malei',
		soundAudio: '/alphabet/heb/segol-malei.mp3',
		nameAudio: '/alphabet/heb/sound-alef-segol-yod.mp3',
	},
	{
		char: 'אַ',
		name: 'Patach',
		key: 'patach',
		soundAudio: '/alphabet/heb/patach.mp3',
		nameAudio: '/alphabet/heb/sound-alef-patach.mp3',
	},
	{
		char: 'אַה',
		name: 'Patach Malei',
		key: 'patach-malei',
		soundAudio: '/alphabet/heb/patach-malei.mp3',
		nameAudio: '/alphabet/heb/sound-alef-patach.mp3',
	},
	{
		char: 'אָ',
		name: 'Kamatz Gadol',
		key: 'kamatz-gadol',
		soundAudio: '/alphabet/heb/kamatz-gadol.mp3',
		nameAudio: '/alphabet/heb/sound-alef-qamats.mp3',
	},
	{
		char: 'אָה',
		name: 'Kamatz Malei',
		key: 'kamatz-malei',
		soundAudio: '/alphabet/heb/kamatz-malei.mp3',
		nameAudio: '/alphabet/heb/sound-alef-qamats-hey.mp3',
	},
	{
		char: 'אׇ',
		name: 'Kamatz Katan',
		key: 'kamatz-katan',
		soundAudio: '/alphabet/heb/kamatz-katan.mp3',
		nameAudio: '/alphabet/heb/sound-alef-chataf-qamats.mp3',
	},
	{
		char: 'אֹ',
		name: 'Cholam',
		key: 'cholam',
		soundAudio: '/alphabet/heb/cholam.mp3',
		nameAudio: '/alphabet/heb/sound-alef-holam.mp3',
	},
	{
		char: 'אוֹ',
		name: 'Cholam Malei',
		key: 'cholam-malei',
		soundAudio: '/alphabet/heb/cholam-malei.mp3',
		nameAudio: '/alphabet/heb/sound-alef-holam-male.mp3',
	},
	{
		char: 'אֻ',
		name: 'Kubutz',
		key: 'kubutz',
		soundAudio: '/alphabet/heb/kubutz.mp3',
		nameAudio: '/alphabet/heb/sound-alef-qubutz.mp3',
	},
	{
		char: 'אוּ',
		name: 'Shuruk',
		key: 'shuruk',
		soundAudio: '/alphabet/heb/shuruk.mp3',
		nameAudio: '/alphabet/heb/sound-alef-shuruk.mp3',
	},
	{
		char: 'בּ',
		name: 'Dagesh',
		key: 'dagesh',
		soundAudio: '/alphabet/heb/dagesh.mp3',
		nameAudio: '/alphabet/heb/sound-alef-dagesh.mp3',
	},
	{
		char: 'אֿ',
		name: 'Rafe',
		key: 'rafe',
		soundAudio: '/alphabet/heb/rafe.mp3',
		nameAudio: '/alphabet/heb/sound-alef-base.mp3',
	},
	{
		char: 'שׁ',
		name: 'Shin Ymanit',
		key: 'shin-dot',
		soundAudio: '/alphabet/heb/shin-dot.mp3',
		nameAudio: '/alphabet/heb/sound-shin-base.mp3',
	},
	{
		char: 'שׂ',
		name: 'Shin Simalit',
		key: 'shin-dot',
		soundAudio: '/alphabet/heb/sin-dot.mp3',
		nameAudio: '/alphabet/heb/sound-sin-base.mp3',
	},
]
