export const hebrewLetters = [
	{
		char: 'א',
		nameAudio: '/alphabet/heb/name-alef-base.mp3',
		soundAudio: '/alphabet/heb/sound-alef-base.mp3',
		imageKey: 'alef',
	},
	{
		char: 'אְ',
		nameAudio: '/alphabet/heb/name-alef-shva.mp3',
		soundAudio: '/alphabet/heb/sound-alef-base.mp3',
	},
	{
		char: 'אּ',
		nameAudio: '/alphabet/heb/name-alef-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-alef-dagesh.mp3',
	},
	{
		char: 'אָה',
		nameAudio: '/alphabet/heb/name-alef-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-alef-qamats-hey.mp3',
	},
	{
		char: 'אָ',
		nameAudio: '/alphabet/heb/name-alef-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-alef-qamats.mp3',
	},
	{
		char: 'אַ',
		nameAudio: '/alphabet/heb/name-alef-patach.mp3',
		soundAudio: '/alphabet/heb/sound-alef-patach.mp3',
	},
	{
		char: 'אֲ',
		nameAudio: '/alphabet/heb/name-alef-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-alef-chataf-patach.mp3',
	},
	{
		char: 'אֵי',
		nameAudio: '/alphabet/heb/name-alef-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-alef-tsere-yod.mp3',
	},
	{
		char: 'אֵ',
		nameAudio: '/alphabet/heb/name-alef-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-alef-tsere.mp3',
	},
	{
		char: 'אֶי',
		nameAudio: '/alphabet/heb/name-alef-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-alef-segol-yod.mp3',
	},
	{
		char: 'אֶ',
		nameAudio: '/alphabet/heb/name-alef-segol.mp3',
		soundAudio: '/alphabet/heb/sound-alef-segol.mp3',
	},
	{
		char: 'אֱ',
		nameAudio: '/alphabet/heb/name-alef-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-alef-chataf-segol.mp3',
	},
	{
		char: 'אִי',
		nameAudio: '/alphabet/heb/name-alef-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-alef-hiriq-yod.mp3',
	},
	{
		char: 'אִ',
		nameAudio: '/alphabet/heb/name-alef-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-alef-hiriq.mp3',
	},
	{
		char: 'אוֹ',
		nameAudio: '/alphabet/heb/name-alef-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-alef-holam-male.mp3',
	},
	{
		char: 'אֹ',
		nameAudio: '/alphabet/heb/name-alef-holam.mp3',
		soundAudio: '/alphabet/heb/sound-alef-holam.mp3',
	},
	{
		char: 'אֳ',
		nameAudio: '/alphabet/heb/name-alef-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-alef-chataf-qamats.mp3',
	},
	{
		char: 'אוּ',
		nameAudio: '/alphabet/heb/name-alef-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-alef-shuruk.mp3',
	},
	{
		char: 'אֻ',
		nameAudio: '/alphabet/heb/name-alef-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-alef-qubutz.mp3',
	},
	{
		char: 'אַי',
		nameAudio: '/alphabet/heb/name-alef-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-alef-patach-yod.mp3',
	},
	{
		char: 'ב',
		nameAudio: '/alphabet/heb/name-vet-base.mp3',
		soundAudio: '/alphabet/heb/sound-vet-base.mp3',
	},
	{
		char: 'בְ',
		nameAudio: '/alphabet/heb/name-vet-shva.mp3',
		soundAudio: '/alphabet/heb/sound-vet-base.mp3',
	},
	{
		char: 'בָה',
		nameAudio: '/alphabet/heb/name-vet-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-vet-qamats-hey.mp3',
	},
	{
		char: 'בָ',
		nameAudio: '/alphabet/heb/name-vet-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-vet-qamats.mp3',
	},
	{
		char: 'בַ',
		nameAudio: '/alphabet/heb/name-vet-patach.mp3',
		soundAudio: '/alphabet/heb/sound-vet-patach.mp3',
	},
	{
		char: 'בֲ',
		nameAudio: '/alphabet/heb/name-vet-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-vet-chataf-patach.mp3',
	},
	{
		char: 'בֵי',
		nameAudio: '/alphabet/heb/name-vet-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-vet-tsere-yod.mp3',
	},
	{
		char: 'בֵ',
		nameAudio: '/alphabet/heb/name-vet-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-vet-tsere.mp3',
	},
	{
		char: 'בֶי',
		nameAudio: '/alphabet/heb/name-vet-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-vet-segol-yod.mp3',
	},
	{
		char: 'בֶ',
		nameAudio: '/alphabet/heb/name-vet-segol.mp3',
		soundAudio: '/alphabet/heb/sound-vet-segol.mp3',
	},
	{
		char: 'בֱ',
		nameAudio: '/alphabet/heb/name-vet-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-vet-chataf-segol.mp3',
	},
	{
		char: 'בִי',
		nameAudio: '/alphabet/heb/name-vet-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-vet-hiriq-yod.mp3',
	},
	{
		char: 'בִ',
		nameAudio: '/alphabet/heb/name-vet-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-vet-hiriq.mp3',
	},
	{
		char: 'בוֹ',
		nameAudio: '/alphabet/heb/name-vet-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-vet-holam-male.mp3',
	},
	{
		char: 'בֹ',
		nameAudio: '/alphabet/heb/name-vet-holam.mp3',
		soundAudio: '/alphabet/heb/sound-vet-holam.mp3',
	},
	{
		char: 'בֳ',
		nameAudio: '/alphabet/heb/name-vet-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-vet-chataf-qamats.mp3',
	},
	{
		char: 'בוּ',
		nameAudio: '/alphabet/heb/name-vet-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-vet-shuruk.mp3',
	},
	{
		char: 'בֻ',
		nameAudio: '/alphabet/heb/name-vet-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-vet-qubutz.mp3',
	},
	{
		char: 'בַי',
		nameAudio: '/alphabet/heb/name-vet-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-vet-patach-yod.mp3',
	},
	{
		char: 'בּ',
		nameAudio: '/alphabet/heb/name-bet-base.mp3',
		soundAudio: '/alphabet/heb/sound-bet-base.mp3',
		imageKey: 'bet',
	},
	{
		char: 'בְּ',
		nameAudio: '/alphabet/heb/name-bet-shva.mp3',
		soundAudio: '/alphabet/heb/sound-bet-base.mp3',
	},
	{
		char: 'בָּה',
		nameAudio: '/alphabet/heb/name-bet-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-bet-qamats-hey.mp3',
	},
	{
		char: 'בָּ',
		nameAudio: '/alphabet/heb/name-bet-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-bet-qamats.mp3',
	},
	{
		char: 'בַּ',
		nameAudio: '/alphabet/heb/name-bet-patach.mp3',
		soundAudio: '/alphabet/heb/sound-bet-patach.mp3',
	},
	{
		char: 'בֲּ',
		nameAudio: '/alphabet/heb/name-bet-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-bet-chataf-patach.mp3',
	},
	{
		char: 'בֵּי',
		nameAudio: '/alphabet/heb/name-bet-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-bet-tsere-yod.mp3',
	},
	{
		char: 'בֵּ',
		nameAudio: '/alphabet/heb/name-bet-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-bet-tsere.mp3',
	},
	{
		char: 'בֶּי',
		nameAudio: '/alphabet/heb/name-bet-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-bet-segol-yod.mp3',
	},
	{
		char: 'בֶּ',
		nameAudio: '/alphabet/heb/name-bet-segol.mp3',
		soundAudio: '/alphabet/heb/sound-bet-segol.mp3',
	},
	{
		char: 'בֱּ',
		nameAudio: '/alphabet/heb/name-bet-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-bet-chataf-segol.mp3',
	},
	{
		char: 'בִּי',
		nameAudio: '/alphabet/heb/name-bet-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-bet-hiriq-yod.mp3',
	},
	{
		char: 'בִּ',
		nameAudio: '/alphabet/heb/name-bet-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-bet-hiriq.mp3',
	},
	{
		char: 'בּוֹ',
		nameAudio: '/alphabet/heb/name-bet-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-bet-holam-male.mp3',
	},
	{
		char: 'בֹּ',
		nameAudio: '/alphabet/heb/name-bet-holam.mp3',
		soundAudio: '/alphabet/heb/sound-bet-holam.mp3',
	},
	{
		char: 'בֳּ',
		nameAudio: '/alphabet/heb/name-bet-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-bet-chataf-qamats.mp3',
	},
	{
		char: 'בּוּ',
		nameAudio: '/alphabet/heb/name-bet-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-bet-shuruk.mp3',
	},
	{
		char: 'בֻּ',
		nameAudio: '/alphabet/heb/name-bet-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-bet-qubutz.mp3',
	},
	{
		char: 'בַּי',
		nameAudio: '/alphabet/heb/name-bet-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-bet-patach-yod.mp3',
	},
	{
		char: 'ג',
		nameAudio: '/alphabet/heb/name-ghimel-base.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-base.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-base.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-base.mp3',
	},
	{
		char: 'גְ',
		nameAudio: '/alphabet/heb/name-ghimel-shva.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-base.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-shva.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-base.mp3',
	},
	{
		char: 'גָה',
		nameAudio: '/alphabet/heb/name-ghimel-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-qamats-hey.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-qamats-hey.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-qamats-hey.mp3',
	},
	{
		char: 'גָ',
		nameAudio: '/alphabet/heb/name-ghimel-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-qamats.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-qamats.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-qamats.mp3',
	},
	{
		char: 'גַ',
		nameAudio: '/alphabet/heb/name-ghimel-patach.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-patach.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-patach.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-patach.mp3',
	},
	{
		char: 'גֲ',
		nameAudio: '/alphabet/heb/name-ghimel-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-chataf-patach.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-chataf-patach.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-chataf-patach.mp3',
	},
	{
		char: 'גֵי',
		nameAudio: '/alphabet/heb/name-ghimel-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-tsere-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-tsere-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-tsere-yod.mp3',
	},
	{
		char: 'גֵ',
		nameAudio: '/alphabet/heb/name-ghimel-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-tsere.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-tsere.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-tsere.mp3',
	},
	{
		char: 'גֶי',
		nameAudio: '/alphabet/heb/name-ghimel-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-segol-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-segol-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-segol-yod.mp3',
	},
	{
		char: 'גֶ',
		nameAudio: '/alphabet/heb/name-ghimel-segol.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-segol.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-segol.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-segol.mp3',
	},
	{
		char: 'גֱ',
		nameAudio: '/alphabet/heb/name-ghimel-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-chataf-segol.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-chataf-segol.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-chataf-segol.mp3',
	},
	{
		char: 'גִי',
		nameAudio: '/alphabet/heb/name-ghimel-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-hiriq-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-hiriq-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-hiriq-yod.mp3',
	},
	{
		char: 'גִ',
		nameAudio: '/alphabet/heb/name-ghimel-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-hiriq.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-hiriq.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-hiriq.mp3',
	},
	{
		char: 'גוֹ',
		nameAudio: '/alphabet/heb/name-ghimel-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-holam-male.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-holam-male.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-holam-male.mp3',
	},
	{
		char: 'גֹ',
		nameAudio: '/alphabet/heb/name-ghimel-holam.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-holam.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-holam.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-holam.mp3',
	},
	{
		char: 'גֳ',
		nameAudio: '/alphabet/heb/name-ghimel-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-chataf-qamats.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-chataf-qamats.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-chataf-qamats.mp3',
	},
	{
		char: 'גוּ',
		nameAudio: '/alphabet/heb/name-ghimel-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-shuruk.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-shuruk.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-shuruk.mp3',
	},
	{
		char: 'גֻ',
		nameAudio: '/alphabet/heb/name-ghimel-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-qubutz.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-qubutz.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-qubutz.mp3',
	},
	{
		char: 'גַי',
		nameAudio: '/alphabet/heb/name-ghimel-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-ghimel-patach-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-gimel-patach-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-gimel-patach-yod.mp3',
	},
	{
		char: 'גּ',
		nameAudio: '/alphabet/heb/name-gimel-base.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-base.mp3',
		imageKey: 'gimel',
	},
	{
		char: 'גְּ',
		nameAudio: '/alphabet/heb/name-gimel-shva.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-base.mp3',
	},
	{
		char: 'גָּה',
		nameAudio: '/alphabet/heb/name-gimel-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-qamats-hey.mp3',
	},
	{
		char: 'גָּ',
		nameAudio: '/alphabet/heb/name-gimel-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-qamats.mp3',
	},
	{
		char: 'גַּ',
		nameAudio: '/alphabet/heb/name-gimel-patach.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-patach.mp3',
	},
	{
		char: 'גֲּ',
		nameAudio: '/alphabet/heb/name-gimel-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-chataf-patach.mp3',
	},
	{
		char: 'גֵּי',
		nameAudio: '/alphabet/heb/name-gimel-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-tsere-yod.mp3',
	},
	{
		char: 'גֵּ',
		nameAudio: '/alphabet/heb/name-gimel-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-tsere.mp3',
	},
	{
		char: 'גֶּי',
		nameAudio: '/alphabet/heb/name-gimel-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-segol-yod.mp3',
	},
	{
		char: 'גֶּ',
		nameAudio: '/alphabet/heb/name-gimel-segol.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-segol.mp3',
	},
	{
		char: 'גֱּ',
		nameAudio: '/alphabet/heb/name-gimel-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-chataf-segol.mp3',
	},
	{
		char: 'גִּי',
		nameAudio: '/alphabet/heb/name-gimel-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-hiriq-yod.mp3',
	},
	{
		char: 'גִּ',
		nameAudio: '/alphabet/heb/name-gimel-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-hiriq.mp3',
	},
	{
		char: 'גּוֹ',
		nameAudio: '/alphabet/heb/name-gimel-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-holam-male.mp3',
	},
	{
		char: 'גֹּ',
		nameAudio: '/alphabet/heb/name-gimel-holam.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-holam.mp3',
	},
	{
		char: 'גֳּ',
		nameAudio: '/alphabet/heb/name-gimel-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-chataf-qamats.mp3',
	},
	{
		char: 'גּוּ',
		nameAudio: '/alphabet/heb/name-gimel-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-shuruk.mp3',
	},
	{
		char: 'גֻּ',
		nameAudio: '/alphabet/heb/name-gimel-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-qubutz.mp3',
	},
	{
		char: 'גַּי',
		nameAudio: '/alphabet/heb/name-gimel-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-gimel-patach-yod.mp3',
	},
	{
		char: 'ד',
		nameAudio: '/alphabet/heb/name-dhalet-base.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-base.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-base.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-base.mp3',
	},
	{
		char: 'דְ',
		nameAudio: '/alphabet/heb/name-dhalet-shva.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-base.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-shva.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-base.mp3',
	},
	{
		char: 'דָה',
		nameAudio: '/alphabet/heb/name-dhalet-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-qamats-hey.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-qamats-hey.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-qamats-hey.mp3',
	},
	{
		char: 'דָ',
		nameAudio: '/alphabet/heb/name-dhalet-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-qamats.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-qamats.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-qamats.mp3',
	},
	{
		char: 'דַ',
		nameAudio: '/alphabet/heb/name-dhalet-patach.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-patach.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-patach.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-patach.mp3',
	},
	{
		char: 'דֲ',
		nameAudio: '/alphabet/heb/name-dhalet-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-chataf-patach.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-chataf-patach.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-chataf-patach.mp3',
	},
	{
		char: 'דֵי',
		nameAudio: '/alphabet/heb/name-dhalet-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-tsere-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-tsere-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-tsere-yod.mp3',
	},
	{
		char: 'דֵ',
		nameAudio: '/alphabet/heb/name-dhalet-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-tsere.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-tsere.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-tsere.mp3',
	},
	{
		char: 'דֶי',
		nameAudio: '/alphabet/heb/name-dhalet-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-segol-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-segol-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-segol-yod.mp3',
	},
	{
		char: 'דֶ',
		nameAudio: '/alphabet/heb/name-dhalet-segol.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-segol.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-segol.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-segol.mp3',
	},
	{
		char: 'דֱ',
		nameAudio: '/alphabet/heb/name-dhalet-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-chataf-segol.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-chataf-segol.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-chataf-segol.mp3',
	},
	{
		char: 'דִי',
		nameAudio: '/alphabet/heb/name-dhalet-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-hiriq-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-hiriq-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-hiriq-yod.mp3',
	},
	{
		char: 'דִ',
		nameAudio: '/alphabet/heb/name-dhalet-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-hiriq.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-hiriq.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-hiriq.mp3',
	},
	{
		char: 'דוֹ',
		nameAudio: '/alphabet/heb/name-dhalet-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-holam-male.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-holam-male.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-holam-male.mp3',
	},
	{
		char: 'דֹ',
		nameAudio: '/alphabet/heb/name-dhalet-holam.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-holam.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-holam.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-holam.mp3',
	},
	{
		char: 'דֳ',
		nameAudio: '/alphabet/heb/name-dhalet-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-chataf-qamats.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-chataf-qamats.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-chataf-qamats.mp3',
	},
	{
		char: 'דוּ',
		nameAudio: '/alphabet/heb/name-dhalet-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-shuruk.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-shuruk.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-shuruk.mp3',
	},
	{
		char: 'דֻ',
		nameAudio: '/alphabet/heb/name-dhalet-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-qubutz.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-qubutz.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-qubutz.mp3',
	},
	{
		char: 'דַי',
		nameAudio: '/alphabet/heb/name-dhalet-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-dhalet-patach-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-dalet-patach-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-dalet-patach-yod.mp3',
	},
	{
		char: 'דּ',
		nameAudio: '/alphabet/heb/name-dalet-base.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-base.mp3',
		imageKey: 'dalet',
	},
	{
		char: 'דְּ',
		nameAudio: '/alphabet/heb/name-dalet-shva.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-base.mp3',
	},
	{
		char: 'דָּה',
		nameAudio: '/alphabet/heb/name-dalet-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-qamats-hey.mp3',
	},
	{
		char: 'דָּ',
		nameAudio: '/alphabet/heb/name-dalet-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-qamats.mp3',
	},
	{
		char: 'דַּ',
		nameAudio: '/alphabet/heb/name-dalet-patach.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-patach.mp3',
	},
	{
		char: 'דֲּ',
		nameAudio: '/alphabet/heb/name-dalet-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-chataf-patach.mp3',
	},
	{
		char: 'דֵּי',
		nameAudio: '/alphabet/heb/name-dalet-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-tsere-yod.mp3',
	},
	{
		char: 'דֵּ',
		nameAudio: '/alphabet/heb/name-dalet-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-tsere.mp3',
	},
	{
		char: 'דֶּי',
		nameAudio: '/alphabet/heb/name-dalet-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-segol-yod.mp3',
	},
	{
		char: 'דֶּ',
		nameAudio: '/alphabet/heb/name-dalet-segol.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-segol.mp3',
	},
	{
		char: 'דֱּ',
		nameAudio: '/alphabet/heb/name-dalet-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-chataf-segol.mp3',
	},
	{
		char: 'דִּי',
		nameAudio: '/alphabet/heb/name-dalet-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-hiriq-yod.mp3',
	},
	{
		char: 'דִּ',
		nameAudio: '/alphabet/heb/name-dalet-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-hiriq.mp3',
	},
	{
		char: 'דּוֹ',
		nameAudio: '/alphabet/heb/name-dalet-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-holam-male.mp3',
	},
	{
		char: 'דֹּ',
		nameAudio: '/alphabet/heb/name-dalet-holam.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-holam.mp3',
	},
	{
		char: 'דֳּ',
		nameAudio: '/alphabet/heb/name-dalet-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-chataf-qamats.mp3',
	},
	{
		char: 'דּוּ',
		nameAudio: '/alphabet/heb/name-dalet-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-shuruk.mp3',
	},
	{
		char: 'דֻּ',
		nameAudio: '/alphabet/heb/name-dalet-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-qubutz.mp3',
	},
	{
		char: 'דַּי',
		nameAudio: '/alphabet/heb/name-dalet-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-dalet-patach-yod.mp3',
	},
	{
		char: 'ה',
		nameAudio: '/alphabet/heb/name-he-base.mp3',
		soundAudio: '/alphabet/heb/sound-he-base.mp3',
		imageKey: 'he',
	},
	{
		char: 'הְ',
		nameAudio: '/alphabet/heb/name-he-shva.mp3',
		soundAudio: '/alphabet/heb/sound-he-base.mp3',
	},
	{
		char: 'הּ',
		nameAudio: '/alphabet/heb/name-he-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-he-dagesh.mp3',
	},
	{
		char: 'הָה',
		nameAudio: '/alphabet/heb/name-he-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-he-qamats-hey.mp3',
	},
	{
		char: 'הָ',
		nameAudio: '/alphabet/heb/name-he-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-he-qamats.mp3',
	},
	{
		char: 'הַ',
		nameAudio: '/alphabet/heb/name-he-patach.mp3',
		soundAudio: '/alphabet/heb/sound-he-patach.mp3',
	},
	{
		char: 'הֲ',
		nameAudio: '/alphabet/heb/name-he-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-he-chataf-patach.mp3',
	},
	{
		char: 'הֵי',
		nameAudio: '/alphabet/heb/name-he-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-he-tsere-yod.mp3',
	},
	{
		char: 'הֵ',
		nameAudio: '/alphabet/heb/name-he-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-he-tsere.mp3',
	},
	{
		char: 'הֶי',
		nameAudio: '/alphabet/heb/name-he-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-he-segol-yod.mp3',
	},
	{
		char: 'הֶ',
		nameAudio: '/alphabet/heb/name-he-segol.mp3',
		soundAudio: '/alphabet/heb/sound-he-segol.mp3',
	},
	{
		char: 'הֱ',
		nameAudio: '/alphabet/heb/name-he-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-he-chataf-segol.mp3',
	},
	{
		char: 'הִי',
		nameAudio: '/alphabet/heb/name-he-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-he-hiriq-yod.mp3',
	},
	{
		char: 'הִ',
		nameAudio: '/alphabet/heb/name-he-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-he-hiriq.mp3',
	},
	{
		char: 'הוֹ',
		nameAudio: '/alphabet/heb/name-he-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-he-holam-male.mp3',
	},
	{
		char: 'הֹ',
		nameAudio: '/alphabet/heb/name-he-holam.mp3',
		soundAudio: '/alphabet/heb/sound-he-holam.mp3',
	},
	{
		char: 'הֳ',
		nameAudio: '/alphabet/heb/name-he-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-he-chataf-qamats.mp3',
	},
	{
		char: 'הוּ',
		nameAudio: '/alphabet/heb/name-he-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-he-shuruk.mp3',
	},
	{
		char: 'הֻ',
		nameAudio: '/alphabet/heb/name-he-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-he-qubutz.mp3',
	},
	{
		char: 'הַי',
		nameAudio: '/alphabet/heb/name-he-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-he-patach-yod.mp3',
	},
	{
		char: 'ו',
		nameAudio: '/alphabet/heb/name-vav-base.mp3',
		soundAudio: '/alphabet/heb/sound-vet-base.mp3',
		imageKey: 'vav',
	},
	{
		char: 'וְ',
		nameAudio: '/alphabet/heb/name-vav-shva.mp3',
		soundAudio: '/alphabet/heb/sound-vet-base.mp3',
	},
	{
		char: 'וּ',
		nameAudio: '/alphabet/heb/name-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-shuruk.mp3',
	},
	{
		char: 'וָה',
		nameAudio: '/alphabet/heb/name-vav-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-vet-qamats-hey.mp3',
	},
	{
		char: 'וָ',
		nameAudio: '/alphabet/heb/name-vav-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-vet-qamats.mp3',
	},
	{
		char: 'וַ',
		nameAudio: '/alphabet/heb/name-vav-patach.mp3',
		soundAudio: '/alphabet/heb/sound-vet-patach.mp3',
	},
	{
		char: 'וֲ',
		nameAudio: '/alphabet/heb/name-vav-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-vet-chataf-patach.mp3',
	},
	{
		char: 'וֵי',
		nameAudio: '/alphabet/heb/name-vav-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-vet-tsere-yod.mp3',
	},
	{
		char: 'וֵ',
		nameAudio: '/alphabet/heb/name-vav-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-vet-tsere.mp3',
	},
	{
		char: 'וֶי',
		nameAudio: '/alphabet/heb/name-vav-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-vet-segol-yod.mp3',
	},
	{
		char: 'וֶ',
		nameAudio: '/alphabet/heb/name-vav-segol.mp3',
		soundAudio: '/alphabet/heb/sound-vet-segol.mp3',
	},
	{
		char: 'וֱ',
		nameAudio: '/alphabet/heb/name-vav-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-vet-chataf-segol.mp3',
	},
	{
		char: 'וִי',
		nameAudio: '/alphabet/heb/name-vav-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-vet-hiriq-yod.mp3',
	},
	{
		char: 'וִ',
		nameAudio: '/alphabet/heb/name-vav-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-vet-hiriq.mp3',
	},
	{
		char: 'ווֹ',
		nameAudio: '/alphabet/heb/name-vav-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-vet-holam-male.mp3',
	},
	{
		char: 'וֹ',
		nameAudio: '/alphabet/heb/name-vav-holam.mp3',
		soundAudio: '/alphabet/heb/sound-vet-holam.mp3',
	},
	{
		char: 'וֳ',
		nameAudio: '/alphabet/heb/name-vav-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-vet-chataf-qamats.mp3',
	},
	{
		char: 'ווּ',
		nameAudio: '/alphabet/heb/name-vav-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-vet-shuruk.mp3',
	},
	{
		char: 'וֻ',
		nameAudio: '/alphabet/heb/name-vav-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-vet-qubutz.mp3',
	},
	{
		char: 'וַי',
		nameAudio: '/alphabet/heb/name-vav-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-vet-patach-yod.mp3',
	},
	{
		char: 'ז',
		nameAudio: '/alphabet/heb/name-zayin-base.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-base.mp3',
		imageKey: 'zayin',
	},
	{
		char: 'זְ',
		nameAudio: '/alphabet/heb/name-zayin-shva.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-base.mp3',
	},
	{
		char: 'זּ',
		nameAudio: '/alphabet/heb/name-zayin-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-dagesh.mp3',
	},
	{
		char: 'זָה',
		nameAudio: '/alphabet/heb/name-zayin-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-qamats-hey.mp3',
	},
	{
		char: 'זָ',
		nameAudio: '/alphabet/heb/name-zayin-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-qamats.mp3',
	},
	{
		char: 'זַ',
		nameAudio: '/alphabet/heb/name-zayin-patach.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-patach.mp3',
	},
	{
		char: 'זֲ',
		nameAudio: '/alphabet/heb/name-zayin-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-chataf-patach.mp3',
	},
	{
		char: 'זֵי',
		nameAudio: '/alphabet/heb/name-zayin-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-tsere-yod.mp3',
	},
	{
		char: 'זֵ',
		nameAudio: '/alphabet/heb/name-zayin-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-tsere.mp3',
	},
	{
		char: 'זֶי',
		nameAudio: '/alphabet/heb/name-zayin-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-segol-yod.mp3',
	},
	{
		char: 'זֶ',
		nameAudio: '/alphabet/heb/name-zayin-segol.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-segol.mp3',
	},
	{
		char: 'זֱ',
		nameAudio: '/alphabet/heb/name-zayin-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-chataf-segol.mp3',
	},
	{
		char: 'זִי',
		nameAudio: '/alphabet/heb/name-zayin-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-hiriq-yod.mp3',
	},
	{
		char: 'זִ',
		nameAudio: '/alphabet/heb/name-zayin-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-hiriq.mp3',
	},
	{
		char: 'זוֹ',
		nameAudio: '/alphabet/heb/name-zayin-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-holam-male.mp3',
	},
	{
		char: 'זֹ',
		nameAudio: '/alphabet/heb/name-zayin-holam.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-holam.mp3',
	},
	{
		char: 'זֳ',
		nameAudio: '/alphabet/heb/name-zayin-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-chataf-qamats.mp3',
	},
	{
		char: 'זוּ',
		nameAudio: '/alphabet/heb/name-zayin-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-shuruk.mp3',
	},
	{
		char: 'זֻ',
		nameAudio: '/alphabet/heb/name-zayin-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-qubutz.mp3',
	},
	{
		char: 'זַי',
		nameAudio: '/alphabet/heb/name-zayin-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-zayin-patach-yod.mp3',
	},
	{
		char: 'ח',
		nameAudio: '/alphabet/heb/name-chet-base.mp3',
		soundAudio: '/alphabet/heb/sound-chet-base.mp3',
		imageKey: 'chet',
	},
	{
		char: 'חְ',
		nameAudio: '/alphabet/heb/name-chet-shva.mp3',
		soundAudio: '/alphabet/heb/sound-chet-base.mp3',
	},
	{
		char: 'חּ',
		nameAudio: '/alphabet/heb/name-chet-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-chet-dagesh.mp3',
	},
	{
		char: 'חָה',
		nameAudio: '/alphabet/heb/name-chet-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-chet-qamats-hey.mp3',
	},
	{
		char: 'חָ',
		nameAudio: '/alphabet/heb/name-chet-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-chet-qamats.mp3',
	},
	{
		char: 'חַ',
		nameAudio: '/alphabet/heb/name-chet-patach.mp3',
		soundAudio: '/alphabet/heb/sound-chet-patach.mp3',
	},
	{
		char: 'חֲ',
		nameAudio: '/alphabet/heb/name-chet-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-chet-chataf-patach.mp3',
	},
	{
		char: 'חֵי',
		nameAudio: '/alphabet/heb/name-chet-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-chet-tsere-yod.mp3',
	},
	{
		char: 'חֵ',
		nameAudio: '/alphabet/heb/name-chet-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-chet-tsere.mp3',
	},
	{
		char: 'חֶי',
		nameAudio: '/alphabet/heb/name-chet-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-chet-segol-yod.mp3',
	},
	{
		char: 'חֶ',
		nameAudio: '/alphabet/heb/name-chet-segol.mp3',
		soundAudio: '/alphabet/heb/sound-chet-segol.mp3',
	},
	{
		char: 'חֱ',
		nameAudio: '/alphabet/heb/name-chet-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-chet-chataf-segol.mp3',
	},
	{
		char: 'חִי',
		nameAudio: '/alphabet/heb/name-chet-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-chet-hiriq-yod.mp3',
	},
	{
		char: 'חִ',
		nameAudio: '/alphabet/heb/name-chet-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-chet-hiriq.mp3',
	},
	{
		char: 'חוֹ',
		nameAudio: '/alphabet/heb/name-chet-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-chet-holam-male.mp3',
	},
	{
		char: 'חֹ',
		nameAudio: '/alphabet/heb/name-chet-holam.mp3',
		soundAudio: '/alphabet/heb/sound-chet-holam.mp3',
	},
	{
		char: 'חֳ',
		nameAudio: '/alphabet/heb/name-chet-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-chet-chataf-qamats.mp3',
	},
	{
		char: 'חוּ',
		nameAudio: '/alphabet/heb/name-chet-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-chet-shuruk.mp3',
	},
	{
		char: 'חֻ',
		nameAudio: '/alphabet/heb/name-chet-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-chet-qubutz.mp3',
	},
	{
		char: 'חַי',
		nameAudio: '/alphabet/heb/name-chet-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-chet-patach-yod.mp3',
	},
	{
		char: 'ט',
		nameAudio: '/alphabet/heb/name-tet-base.mp3',
		soundAudio: '/alphabet/heb/sound-tav-base.mp3',
		imageKey: 'tet',
	},
	{
		char: 'טְ',
		nameAudio: '/alphabet/heb/name-tet-shva.mp3',
		soundAudio: '/alphabet/heb/sound-tav-base.mp3',
	},
	{
		char: 'טּ',
		nameAudio: '/alphabet/heb/name-tet-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-tav-dagesh.mp3',
	},
	{
		char: 'טָה',
		nameAudio: '/alphabet/heb/name-tet-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-tav-qamats-hey.mp3',
	},
	{
		char: 'טָ',
		nameAudio: '/alphabet/heb/name-tet-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-tav-qamats.mp3',
	},
	{
		char: 'טַ',
		nameAudio: '/alphabet/heb/name-tet-patach.mp3',
		soundAudio: '/alphabet/heb/sound-tav-patach.mp3',
	},
	{
		char: 'טֲ',
		nameAudio: '/alphabet/heb/name-tet-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-tav-chataf-patach.mp3',
	},
	{
		char: 'טֵי',
		nameAudio: '/alphabet/heb/name-tet-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tav-tsere-yod.mp3',
	},
	{
		char: 'טֵ',
		nameAudio: '/alphabet/heb/name-tet-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-tav-tsere.mp3',
	},
	{
		char: 'טֶי',
		nameAudio: '/alphabet/heb/name-tet-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tav-segol-yod.mp3',
	},
	{
		char: 'טֶ',
		nameAudio: '/alphabet/heb/name-tet-segol.mp3',
		soundAudio: '/alphabet/heb/sound-tav-segol.mp3',
	},
	{
		char: 'טֱ',
		nameAudio: '/alphabet/heb/name-tet-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-tav-chataf-segol.mp3',
	},
	{
		char: 'טִי',
		nameAudio: '/alphabet/heb/name-tet-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tav-hiriq-yod.mp3',
	},
	{
		char: 'טִ',
		nameAudio: '/alphabet/heb/name-tet-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-tav-hiriq.mp3',
	},
	{
		char: 'טוֹ',
		nameAudio: '/alphabet/heb/name-tet-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-tav-holam-male.mp3',
	},
	{
		char: 'טֹ',
		nameAudio: '/alphabet/heb/name-tet-holam.mp3',
		soundAudio: '/alphabet/heb/sound-tav-holam.mp3',
	},
	{
		char: 'טֳ',
		nameAudio: '/alphabet/heb/name-tet-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-tav-chataf-qamats.mp3',
	},
	{
		char: 'טוּ',
		nameAudio: '/alphabet/heb/name-tet-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-tav-shuruk.mp3',
	},
	{
		char: 'טֻ',
		nameAudio: '/alphabet/heb/name-tet-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-tav-qubutz.mp3',
	},
	{
		char: 'טַי',
		nameAudio: '/alphabet/heb/name-tet-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tav-patach-yod.mp3',
	},
	{
		char: 'י',
		nameAudio: '/alphabet/heb/name-yod-base.mp3',
		soundAudio: '/alphabet/heb/sound-yod-base.mp3',
		imageKey: 'yod',
	},
	{
		char: 'יְ',
		nameAudio: '/alphabet/heb/name-yod-shva.mp3',
		soundAudio: '/alphabet/heb/sound-yod-base.mp3',
	},
	{
		char: 'יּ',
		nameAudio: '/alphabet/heb/name-yod-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-yod-dagesh.mp3',
	},
	{
		char: 'יָה',
		nameAudio: '/alphabet/heb/name-yod-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-yod-qamats-hey.mp3',
	},
	{
		char: 'יָ',
		nameAudio: '/alphabet/heb/name-yod-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-yod-qamats.mp3',
	},
	{
		char: 'יַ',
		nameAudio: '/alphabet/heb/name-yod-patach.mp3',
		soundAudio: '/alphabet/heb/sound-yod-patach.mp3',
	},
	{
		char: 'יֲ',
		nameAudio: '/alphabet/heb/name-yod-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-yod-chataf-patach.mp3',
	},
	{
		char: 'יֵי',
		nameAudio: '/alphabet/heb/name-yod-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-yod-tsere-yod.mp3',
	},
	{
		char: 'יֵ',
		nameAudio: '/alphabet/heb/name-yod-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-yod-tsere.mp3',
	},
	{
		char: 'יֶי',
		nameAudio: '/alphabet/heb/name-yod-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-yod-segol-yod.mp3',
	},
	{
		char: 'יֶ',
		nameAudio: '/alphabet/heb/name-yod-segol.mp3',
		soundAudio: '/alphabet/heb/sound-yod-segol.mp3',
	},
	{
		char: 'יֱ',
		nameAudio: '/alphabet/heb/name-yod-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-yod-chataf-segol.mp3',
	},
	{
		char: 'יִי',
		nameAudio: '/alphabet/heb/name-yod-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-yod-hiriq-yod.mp3',
	},
	{
		char: 'יִ',
		nameAudio: '/alphabet/heb/name-yod-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-yod-hiriq.mp3',
	},
	{
		char: 'יוֹ',
		nameAudio: '/alphabet/heb/name-yod-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-yod-holam-male.mp3',
	},
	{
		char: 'יֹ',
		nameAudio: '/alphabet/heb/name-yod-holam.mp3',
		soundAudio: '/alphabet/heb/sound-yod-holam.mp3',
	},
	{
		char: 'יֳ',
		nameAudio: '/alphabet/heb/name-yod-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-yod-chataf-qamats.mp3',
	},
	{
		char: 'יוּ',
		nameAudio: '/alphabet/heb/name-yod-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-yod-shuruk.mp3',
	},
	{
		char: 'יֻ',
		nameAudio: '/alphabet/heb/name-yod-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-yod-qubutz.mp3',
	},
	{
		char: 'יַי',
		nameAudio: '/alphabet/heb/name-yod-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-yod-patach-yod.mp3',
	},
	{
		char: 'כ',
		nameAudio: '/alphabet/heb/name-khaf-base.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-base.mp3',
	},
	{
		char: 'כְ',
		nameAudio: '/alphabet/heb/name-khaf-shva.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-base.mp3',
	},
	{
		char: 'כָה',
		nameAudio: '/alphabet/heb/name-khaf-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-qamats-hey.mp3',
	},
	{
		char: 'כָ',
		nameAudio: '/alphabet/heb/name-khaf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-qamats.mp3',
	},
	{
		char: 'כַ',
		nameAudio: '/alphabet/heb/name-khaf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-patach.mp3',
	},
	{
		char: 'כֲ',
		nameAudio: '/alphabet/heb/name-khaf-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-chataf-patach.mp3',
	},
	{
		char: 'כֵי',
		nameAudio: '/alphabet/heb/name-khaf-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-tsere-yod.mp3',
	},
	{
		char: 'כֵ',
		nameAudio: '/alphabet/heb/name-khaf-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-tsere.mp3',
	},
	{
		char: 'כֶי',
		nameAudio: '/alphabet/heb/name-khaf-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-segol-yod.mp3',
	},
	{
		char: 'כֶ',
		nameAudio: '/alphabet/heb/name-khaf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-segol.mp3',
	},
	{
		char: 'כֱ',
		nameAudio: '/alphabet/heb/name-khaf-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-chataf-segol.mp3',
	},
	{
		char: 'כִי',
		nameAudio: '/alphabet/heb/name-khaf-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-hiriq-yod.mp3',
	},
	{
		char: 'כִ',
		nameAudio: '/alphabet/heb/name-khaf-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-hiriq.mp3',
	},
	{
		char: 'כוֹ',
		nameAudio: '/alphabet/heb/name-khaf-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-holam-male.mp3',
	},
	{
		char: 'כֹ',
		nameAudio: '/alphabet/heb/name-khaf-holam.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-holam.mp3',
	},
	{
		char: 'כֳ',
		nameAudio: '/alphabet/heb/name-khaf-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-chataf-qamats.mp3',
	},
	{
		char: 'כוּ',
		nameAudio: '/alphabet/heb/name-khaf-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-shuruk.mp3',
	},
	{
		char: 'כֻ',
		nameAudio: '/alphabet/heb/name-khaf-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-qubutz.mp3',
	},
	{
		char: 'כַי',
		nameAudio: '/alphabet/heb/name-khaf-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-patach-yod.mp3',
	},
	{
		char: 'ך',
		nameAudio: '/alphabet/heb/name-khaf sofit-base.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-base.mp3',
	},
	{
		char: 'ךְ',
		nameAudio: '/alphabet/heb/name-khaf-shva.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-base.mp3',
	},
	{
		char: 'ךָ',
		nameAudio: '/alphabet/heb/name-khaf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-khaf-qamats.mp3',
	},
	{
		char: 'כּ',
		nameAudio: '/alphabet/heb/name-kaf-base.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-base.mp3',
		imageKey: 'kaf',
	},
	{
		char: 'כְּ',
		nameAudio: '/alphabet/heb/name-kaf-shva.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-base.mp3',
	},
	{
		char: 'כָּה',
		nameAudio: '/alphabet/heb/name-kaf-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-qamats-hey.mp3',
	},
	{
		char: 'כָּ',
		nameAudio: '/alphabet/heb/name-kaf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-qamats.mp3',
	},
	{
		char: 'כַּ',
		nameAudio: '/alphabet/heb/name-kaf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-patach.mp3',
	},
	{
		char: 'כֲּ',
		nameAudio: '/alphabet/heb/name-kaf-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-chataf-patach.mp3',
	},
	{
		char: 'כֵּי',
		nameAudio: '/alphabet/heb/name-kaf-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-tsere-yod.mp3',
	},
	{
		char: 'כֵּ',
		nameAudio: '/alphabet/heb/name-kaf-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-tsere.mp3',
	},
	{
		char: 'כֶּי',
		nameAudio: '/alphabet/heb/name-kaf-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-segol-yod.mp3',
	},
	{
		char: 'כֶּ',
		nameAudio: '/alphabet/heb/name-kaf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-segol.mp3',
	},
	{
		char: 'כֱּ',
		nameAudio: '/alphabet/heb/name-kaf-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-chataf-segol.mp3',
	},
	{
		char: 'כִּי',
		nameAudio: '/alphabet/heb/name-kaf-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-hiriq-yod.mp3',
	},
	{
		char: 'כִּ',
		nameAudio: '/alphabet/heb/name-kaf-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-hiriq.mp3',
	},
	{
		char: 'כּוֹ',
		nameAudio: '/alphabet/heb/name-kaf-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-holam-male.mp3',
	},
	{
		char: 'כֹּ',
		nameAudio: '/alphabet/heb/name-kaf-holam.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-holam.mp3',
	},
	{
		char: 'כֳּ',
		nameAudio: '/alphabet/heb/name-kaf-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-chataf-qamats.mp3',
	},
	{
		char: 'כּוּ',
		nameAudio: '/alphabet/heb/name-kaf-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-shuruk.mp3',
	},
	{
		char: 'כֻּ',
		nameAudio: '/alphabet/heb/name-kaf-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-qubutz.mp3',
	},
	{
		char: 'כַּי',
		nameAudio: '/alphabet/heb/name-kaf-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-patach-yod.mp3',
	},
	{
		char: 'ךּ',
		nameAudio: '/alphabet/heb/name-kaf sofit-base.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-base.mp3',
	},
	{
		char: 'ךְּ',
		nameAudio: '/alphabet/heb/name-kaf-shva.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-base.mp3',
	},
	{
		char: 'ךָּ',
		nameAudio: '/alphabet/heb/name-kaf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-qamats.mp3',
	},
	{
		char: 'ל',
		nameAudio: '/alphabet/heb/name-lamed-base.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-base.mp3',
		imageKey: 'lamed',
	},
	{
		char: 'לְ',
		nameAudio: '/alphabet/heb/name-lamed-shva.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-base.mp3',
	},
	{
		char: 'לּ',
		nameAudio: '/alphabet/heb/name-lamed-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-dagesh.mp3',
	},
	{
		char: 'לָה',
		nameAudio: '/alphabet/heb/name-lamed-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-qamats-hey.mp3',
	},
	{
		char: 'לָ',
		nameAudio: '/alphabet/heb/name-lamed-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-qamats.mp3',
	},
	{
		char: 'לַ',
		nameAudio: '/alphabet/heb/name-lamed-patach.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-patach.mp3',
	},
	{
		char: 'לֲ',
		nameAudio: '/alphabet/heb/name-lamed-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-chataf-patach.mp3',
	},
	{
		char: 'לֵי',
		nameAudio: '/alphabet/heb/name-lamed-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-tsere-yod.mp3',
	},
	{
		char: 'לֵ',
		nameAudio: '/alphabet/heb/name-lamed-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-tsere.mp3',
	},
	{
		char: 'לֶי',
		nameAudio: '/alphabet/heb/name-lamed-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-segol-yod.mp3',
	},
	{
		char: 'לֶ',
		nameAudio: '/alphabet/heb/name-lamed-segol.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-segol.mp3',
	},
	{
		char: 'לֱ',
		nameAudio: '/alphabet/heb/name-lamed-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-chataf-segol.mp3',
	},
	{
		char: 'לִי',
		nameAudio: '/alphabet/heb/name-lamed-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-hiriq-yod.mp3',
	},
	{
		char: 'לִ',
		nameAudio: '/alphabet/heb/name-lamed-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-hiriq.mp3',
	},
	{
		char: 'לוֹ',
		nameAudio: '/alphabet/heb/name-lamed-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-holam-male.mp3',
	},
	{
		char: 'לֹ',
		nameAudio: '/alphabet/heb/name-lamed-holam.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-holam.mp3',
	},
	{
		char: 'לֳ',
		nameAudio: '/alphabet/heb/name-lamed-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-chataf-qamats.mp3',
	},
	{
		char: 'לוּ',
		nameAudio: '/alphabet/heb/name-lamed-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-shuruk.mp3',
	},
	{
		char: 'לֻ',
		nameAudio: '/alphabet/heb/name-lamed-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-qubutz.mp3',
	},
	{
		char: 'לַי',
		nameAudio: '/alphabet/heb/name-lamed-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-lamed-patach-yod.mp3',
	},
	{
		char: 'מ',
		nameAudio: '/alphabet/heb/name-mem-base.mp3',
		soundAudio: '/alphabet/heb/sound-mem-base.mp3',
		imageKey: 'mem',
	},
	{
		char: 'מְ',
		nameAudio: '/alphabet/heb/name-mem-shva.mp3',
		soundAudio: '/alphabet/heb/sound-mem-base.mp3',
	},
	{
		char: 'מּ',
		nameAudio: '/alphabet/heb/name-mem-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-mem-dagesh.mp3',
	},
	{
		char: 'מָה',
		nameAudio: '/alphabet/heb/name-mem-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-mem-qamats-hey.mp3',
	},
	{
		char: 'מָ',
		nameAudio: '/alphabet/heb/name-mem-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-mem-qamats.mp3',
	},
	{
		char: 'מַ',
		nameAudio: '/alphabet/heb/name-mem-patach.mp3',
		soundAudio: '/alphabet/heb/sound-mem-patach.mp3',
	},
	{
		char: 'מֲ',
		nameAudio: '/alphabet/heb/name-mem-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-mem-chataf-patach.mp3',
	},
	{
		char: 'מֵי',
		nameAudio: '/alphabet/heb/name-mem-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-mem-tsere-yod.mp3',
	},
	{
		char: 'מֵ',
		nameAudio: '/alphabet/heb/name-mem-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-mem-tsere.mp3',
	},
	{
		char: 'מֶי',
		nameAudio: '/alphabet/heb/name-mem-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-mem-segol-yod.mp3',
	},
	{
		char: 'מֶ',
		nameAudio: '/alphabet/heb/name-mem-segol.mp3',
		soundAudio: '/alphabet/heb/sound-mem-segol.mp3',
	},
	{
		char: 'מֱ',
		nameAudio: '/alphabet/heb/name-mem-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-mem-chataf-segol.mp3',
	},
	{
		char: 'מִי',
		nameAudio: '/alphabet/heb/name-mem-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-mem-hiriq-yod.mp3',
	},
	{
		char: 'מִ',
		nameAudio: '/alphabet/heb/name-mem-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-mem-hiriq.mp3',
	},
	{
		char: 'מוֹ',
		nameAudio: '/alphabet/heb/name-mem-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-mem-holam-male.mp3',
	},
	{
		char: 'מֹ',
		nameAudio: '/alphabet/heb/name-mem-holam.mp3',
		soundAudio: '/alphabet/heb/sound-mem-holam.mp3',
	},
	{
		char: 'מֳ',
		nameAudio: '/alphabet/heb/name-mem-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-mem-chataf-qamats.mp3',
	},
	{
		char: 'מוּ',
		nameAudio: '/alphabet/heb/name-mem-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-mem-shuruk.mp3',
	},
	{
		char: 'מֻ',
		nameAudio: '/alphabet/heb/name-mem-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-mem-qubutz.mp3',
	},
	{
		char: 'מַי',
		nameAudio: '/alphabet/heb/name-mem-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-mem-patach-yod.mp3',
	},
	{
		char: 'ם',
		nameAudio: '/alphabet/heb/name-mem sofit-base.mp3',
		soundAudio: '/alphabet/heb/sound-mem-base.mp3',
		imageKey: 'mem-sofit',
	},
	{
		char: 'נ',
		nameAudio: '/alphabet/heb/name-nun-base.mp3',
		soundAudio: '/alphabet/heb/sound-nun-base.mp3',
		imageKey: 'nun',
	},
	{
		char: 'נְ',
		nameAudio: '/alphabet/heb/name-nun-shva.mp3',
		soundAudio: '/alphabet/heb/sound-nun-base.mp3',
	},
	{
		char: 'נּ',
		nameAudio: '/alphabet/heb/name-nun-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-nun-dagesh.mp3',
	},
	{
		char: 'נָה',
		nameAudio: '/alphabet/heb/name-nun-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-nun-qamats-hey.mp3',
	},
	{
		char: 'נָ',
		nameAudio: '/alphabet/heb/name-nun-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-nun-qamats.mp3',
	},
	{
		char: 'נַ',
		nameAudio: '/alphabet/heb/name-nun-patach.mp3',
		soundAudio: '/alphabet/heb/sound-nun-patach.mp3',
	},
	{
		char: 'נֲ',
		nameAudio: '/alphabet/heb/name-nun-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-nun-chataf-patach.mp3',
	},
	{
		char: 'נֵי',
		nameAudio: '/alphabet/heb/name-nun-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-nun-tsere-yod.mp3',
	},
	{
		char: 'נֵ',
		nameAudio: '/alphabet/heb/name-nun-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-nun-tsere.mp3',
	},
	{
		char: 'נֶי',
		nameAudio: '/alphabet/heb/name-nun-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-nun-segol-yod.mp3',
	},
	{
		char: 'נֶ',
		nameAudio: '/alphabet/heb/name-nun-segol.mp3',
		soundAudio: '/alphabet/heb/sound-nun-segol.mp3',
	},
	{
		char: 'נֱ',
		nameAudio: '/alphabet/heb/name-nun-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-nun-chataf-segol.mp3',
	},
	{
		char: 'נִי',
		nameAudio: '/alphabet/heb/name-nun-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-nun-hiriq-yod.mp3',
	},
	{
		char: 'נִ',
		nameAudio: '/alphabet/heb/name-nun-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-nun-hiriq.mp3',
	},
	{
		char: 'נוֹ',
		nameAudio: '/alphabet/heb/name-nun-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-nun-holam-male.mp3',
	},
	{
		char: 'נֹ',
		nameAudio: '/alphabet/heb/name-nun-holam.mp3',
		soundAudio: '/alphabet/heb/sound-nun-holam.mp3',
	},
	{
		char: 'נֳ',
		nameAudio: '/alphabet/heb/name-nun-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-nun-chataf-qamats.mp3',
	},
	{
		char: 'נוּ',
		nameAudio: '/alphabet/heb/name-nun-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-nun-shuruk.mp3',
	},
	{
		char: 'נֻ',
		nameAudio: '/alphabet/heb/name-nun-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-nun-qubutz.mp3',
	},
	{
		char: 'נַי',
		nameAudio: '/alphabet/heb/name-nun-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-nun-patach-yod.mp3',
	},
	{
		char: 'ן',
		nameAudio: '/alphabet/heb/name-nun sofit-base.mp3',
		soundAudio: '/alphabet/heb/sound-nun-base.mp3',
		imageKey: 'nun-sofit',
	},
	{
		char: 'ס',
		nameAudio: '/alphabet/heb/name-samekh-base.mp3',
		soundAudio: '/alphabet/heb/sound-sin-base.mp3',
		imageKey: 'samekh',
	},
	{
		char: 'סְ',
		nameAudio: '/alphabet/heb/name-samekh-shva.mp3',
		soundAudio: '/alphabet/heb/sound-sin-base.mp3',
	},
	{
		char: 'סּ',
		nameAudio: '/alphabet/heb/name-samekh-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-sin-dagesh.mp3',
	},
	{
		char: 'סָה',
		nameAudio: '/alphabet/heb/name-samekh-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-sin-qamats-hey.mp3',
	},
	{
		char: 'סָ',
		nameAudio: '/alphabet/heb/name-samekh-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-sin-qamats.mp3',
	},
	{
		char: 'סַ',
		nameAudio: '/alphabet/heb/name-samekh-patach.mp3',
		soundAudio: '/alphabet/heb/sound-sin-patach.mp3',
	},
	{
		char: 'סֲ',
		nameAudio: '/alphabet/heb/name-samekh-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-sin-chataf-patach.mp3',
	},
	{
		char: 'סֵי',
		nameAudio: '/alphabet/heb/name-samekh-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-sin-tsere-yod.mp3',
	},
	{
		char: 'סֵ',
		nameAudio: '/alphabet/heb/name-samekh-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-sin-tsere.mp3',
	},
	{
		char: 'סֶי',
		nameAudio: '/alphabet/heb/name-samekh-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-sin-segol-yod.mp3',
	},
	{
		char: 'סֶ',
		nameAudio: '/alphabet/heb/name-samekh-segol.mp3',
		soundAudio: '/alphabet/heb/sound-sin-segol.mp3',
	},
	{
		char: 'סֱ',
		nameAudio: '/alphabet/heb/name-samekh-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-sin-chataf-segol.mp3',
	},
	{
		char: 'סִי',
		nameAudio: '/alphabet/heb/name-samekh-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-sin-hiriq-yod.mp3',
	},
	{
		char: 'סִ',
		nameAudio: '/alphabet/heb/name-samekh-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-sin-hiriq.mp3',
	},
	{
		char: 'סוֹ',
		nameAudio: '/alphabet/heb/name-samekh-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-sin-holam-male.mp3',
	},
	{
		char: 'סֹ',
		nameAudio: '/alphabet/heb/name-samekh-holam.mp3',
		soundAudio: '/alphabet/heb/sound-sin-holam.mp3',
	},
	{
		char: 'סֳ',
		nameAudio: '/alphabet/heb/name-samekh-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-sin-chataf-qamats.mp3',
	},
	{
		char: 'סוּ',
		nameAudio: '/alphabet/heb/name-samekh-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-sin-shuruk.mp3',
	},
	{
		char: 'סֻ',
		nameAudio: '/alphabet/heb/name-samekh-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-sin-qubutz.mp3',
	},
	{
		char: 'סַי',
		nameAudio: '/alphabet/heb/name-samekh-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-sin-patach-yod.mp3',
	},
	{
		char: 'ע',
		nameAudio: '/alphabet/heb/name-ayin-base.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-base.mp3',
		imageKey: 'ayin',
	},
	{
		char: 'עְ',
		nameAudio: '/alphabet/heb/name-ayin-shva.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-base.mp3',
	},
	{
		char: 'עּ',
		nameAudio: '/alphabet/heb/name-ayin-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-dagesh.mp3',
	},
	{
		char: 'עָה',
		nameAudio: '/alphabet/heb/name-ayin-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-qamats-hey.mp3',
	},
	{
		char: 'עָ',
		nameAudio: '/alphabet/heb/name-ayin-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-qamats.mp3',
	},
	{
		char: 'עַ',
		nameAudio: '/alphabet/heb/name-ayin-patach.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-patach.mp3',
	},
	{
		char: 'עֲ',
		nameAudio: '/alphabet/heb/name-ayin-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-chataf-patach.mp3',
	},
	{
		char: 'עֵי',
		nameAudio: '/alphabet/heb/name-ayin-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-tsere-yod.mp3',
	},
	{
		char: 'עֵ',
		nameAudio: '/alphabet/heb/name-ayin-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-tsere.mp3',
	},
	{
		char: 'עֶי',
		nameAudio: '/alphabet/heb/name-ayin-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-segol-yod.mp3',
	},
	{
		char: 'עֶ',
		nameAudio: '/alphabet/heb/name-ayin-segol.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-segol.mp3',
	},
	{
		char: 'עֱ',
		nameAudio: '/alphabet/heb/name-ayin-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-chataf-segol.mp3',
	},
	{
		char: 'עִי',
		nameAudio: '/alphabet/heb/name-ayin-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-hiriq-yod.mp3',
	},
	{
		char: 'עִ',
		nameAudio: '/alphabet/heb/name-ayin-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-hiriq.mp3',
	},
	{
		char: 'עוֹ',
		nameAudio: '/alphabet/heb/name-ayin-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-holam-male.mp3',
	},
	{
		char: 'עֹ',
		nameAudio: '/alphabet/heb/name-ayin-holam.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-holam.mp3',
	},
	{
		char: 'עֳ',
		nameAudio: '/alphabet/heb/name-ayin-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-chataf-qamats.mp3',
	},
	{
		char: 'עוּ',
		nameAudio: '/alphabet/heb/name-ayin-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-shuruk.mp3',
	},
	{
		char: 'עֻ',
		nameAudio: '/alphabet/heb/name-ayin-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-qubutz.mp3',
	},
	{
		char: 'עַי',
		nameAudio: '/alphabet/heb/name-ayin-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-ayin-patach-yod.mp3',
	},
	{
		char: 'פ',
		nameAudio: '/alphabet/heb/name-fe-base.mp3',
		soundAudio: '/alphabet/heb/sound-fe-base.mp3',
	},
	{
		char: 'פְ',
		nameAudio: '/alphabet/heb/name-fe-shva.mp3',
		soundAudio: '/alphabet/heb/sound-fe-base.mp3',
	},
	{
		char: 'פָה',
		nameAudio: '/alphabet/heb/name-fe-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-fe-qamats-hey.mp3',
	},
	{
		char: 'פָ',
		nameAudio: '/alphabet/heb/name-fe-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-fe-qamats.mp3',
	},
	{
		char: 'פַ',
		nameAudio: '/alphabet/heb/name-fe-patach.mp3',
		soundAudio: '/alphabet/heb/sound-fe-patach.mp3',
	},
	{
		char: 'פֲ',
		nameAudio: '/alphabet/heb/name-fe-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-fe-chataf-patach.mp3',
	},
	{
		char: 'פֵי',
		nameAudio: '/alphabet/heb/name-fe-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-fe-tsere-yod.mp3',
	},
	{
		char: 'פֵ',
		nameAudio: '/alphabet/heb/name-fe-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-fe-tsere.mp3',
	},
	{
		char: 'פֶי',
		nameAudio: '/alphabet/heb/name-fe-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-fe-segol-yod.mp3',
	},
	{
		char: 'פֶ',
		nameAudio: '/alphabet/heb/name-fe-segol.mp3',
		soundAudio: '/alphabet/heb/sound-fe-segol.mp3',
	},
	{
		char: 'פֱ',
		nameAudio: '/alphabet/heb/name-fe-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-fe-chataf-segol.mp3',
	},
	{
		char: 'פִי',
		nameAudio: '/alphabet/heb/name-fe-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-fe-hiriq-yod.mp3',
	},
	{
		char: 'פִ',
		nameAudio: '/alphabet/heb/name-fe-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-fe-hiriq.mp3',
	},
	{
		char: 'פוֹ',
		nameAudio: '/alphabet/heb/name-fe-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-fe-holam-male.mp3',
	},
	{
		char: 'פֹ',
		nameAudio: '/alphabet/heb/name-fe-holam.mp3',
		soundAudio: '/alphabet/heb/sound-fe-holam.mp3',
	},
	{
		char: 'פֳ',
		nameAudio: '/alphabet/heb/name-fe-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-fe-chataf-qamats.mp3',
	},
	{
		char: 'פוּ',
		nameAudio: '/alphabet/heb/name-fe-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-fe-shuruk.mp3',
	},
	{
		char: 'פֻ',
		nameAudio: '/alphabet/heb/name-fe-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-fe-qubutz.mp3',
	},
	{
		char: 'פַי',
		nameAudio: '/alphabet/heb/name-fe-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-fe-patach-yod.mp3',
	},
	{
		char: 'ף',
		nameAudio: '/alphabet/heb/name-fe sofit-base.mp3',
		soundAudio: '/alphabet/heb/sound-fe-base.mp3',
	},
	{
		char: 'פּ',
		nameAudio: '/alphabet/heb/name-pe-base.mp3',
		soundAudio: '/alphabet/heb/sound-pe-base.mp3',
		imageKey: 'pe',
	},
	{
		char: 'פְּ',
		nameAudio: '/alphabet/heb/name-pe-shva.mp3',
		soundAudio: '/alphabet/heb/sound-pe-base.mp3',
	},
	{
		char: 'פָּה',
		nameAudio: '/alphabet/heb/name-pe-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-pe-qamats-hey.mp3',
	},
	{
		char: 'פָּ',
		nameAudio: '/alphabet/heb/name-pe-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-pe-qamats.mp3',
	},
	{
		char: 'פַּ',
		nameAudio: '/alphabet/heb/name-pe-patach.mp3',
		soundAudio: '/alphabet/heb/sound-pe-patach.mp3',
	},
	{
		char: 'פֲּ',
		nameAudio: '/alphabet/heb/name-pe-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-pe-chataf-patach.mp3',
	},
	{
		char: 'פֵּי',
		nameAudio: '/alphabet/heb/name-pe-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-pe-tsere-yod.mp3',
	},
	{
		char: 'פֵּ',
		nameAudio: '/alphabet/heb/name-pe-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-pe-tsere.mp3',
	},
	{
		char: 'פֶּי',
		nameAudio: '/alphabet/heb/name-pe-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-pe-segol-yod.mp3',
	},
	{
		char: 'פֶּ',
		nameAudio: '/alphabet/heb/name-pe-segol.mp3',
		soundAudio: '/alphabet/heb/sound-pe-segol.mp3',
	},
	{
		char: 'פֱּ',
		nameAudio: '/alphabet/heb/name-pe-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-pe-chataf-segol.mp3',
	},
	{
		char: 'פִּי',
		nameAudio: '/alphabet/heb/name-pe-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-pe-hiriq-yod.mp3',
	},
	{
		char: 'פִּ',
		nameAudio: '/alphabet/heb/name-pe-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-pe-hiriq.mp3',
	},
	{
		char: 'פּוֹ',
		nameAudio: '/alphabet/heb/name-pe-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-pe-holam-male.mp3',
	},
	{
		char: 'פֹּ',
		nameAudio: '/alphabet/heb/name-pe-holam.mp3',
		soundAudio: '/alphabet/heb/sound-pe-holam.mp3',
	},
	{
		char: 'פֳּ',
		nameAudio: '/alphabet/heb/name-pe-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-pe-chataf-qamats.mp3',
	},
	{
		char: 'פּוּ',
		nameAudio: '/alphabet/heb/name-pe-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-pe-shuruk.mp3',
	},
	{
		char: 'פֻּ',
		nameAudio: '/alphabet/heb/name-pe-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-pe-qubutz.mp3',
	},
	{
		char: 'פַּי',
		nameAudio: '/alphabet/heb/name-pe-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-pe-patach-yod.mp3',
	},
	{
		char: 'ףּ',
		nameAudio: '/alphabet/heb/name-pe sofit-base.mp3',
		soundAudio: '/alphabet/heb/sound-pe-base.mp3',
		imageKey: 'pe-sofit',
	},
	{
		char: 'צ',
		nameAudio: '/alphabet/heb/name-tsadi-base.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-base.mp3',
		imageKey: 'tsadi',
	},
	{
		char: 'צְ',
		nameAudio: '/alphabet/heb/name-tsadi-shva.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-base.mp3',
	},
	{
		char: 'צּ',
		nameAudio: '/alphabet/heb/name-tsadi-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-dagesh.mp3',
	},
	{
		char: 'צָה',
		nameAudio: '/alphabet/heb/name-tsadi-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-qamats-hey.mp3',
	},
	{
		char: 'צָ',
		nameAudio: '/alphabet/heb/name-tsadi-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-qamats.mp3',
	},
	{
		char: 'צַ',
		nameAudio: '/alphabet/heb/name-tsadi-patach.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-patach.mp3',
	},
	{
		char: 'צֲ',
		nameAudio: '/alphabet/heb/name-tsadi-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-chataf-patach.mp3',
	},
	{
		char: 'צֵי',
		nameAudio: '/alphabet/heb/name-tsadi-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-tsere-yod.mp3',
	},
	{
		char: 'צֵ',
		nameAudio: '/alphabet/heb/name-tsadi-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-tsere.mp3',
	},
	{
		char: 'צֶי',
		nameAudio: '/alphabet/heb/name-tsadi-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-segol-yod.mp3',
	},
	{
		char: 'צֶ',
		nameAudio: '/alphabet/heb/name-tsadi-segol.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-segol.mp3',
	},
	{
		char: 'צֱ',
		nameAudio: '/alphabet/heb/name-tsadi-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-chataf-segol.mp3',
	},
	{
		char: 'צִי',
		nameAudio: '/alphabet/heb/name-tsadi-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-hiriq-yod.mp3',
	},
	{
		char: 'צִ',
		nameAudio: '/alphabet/heb/name-tsadi-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-hiriq.mp3',
	},
	{
		char: 'צוֹ',
		nameAudio: '/alphabet/heb/name-tsadi-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-holam-male.mp3',
	},
	{
		char: 'צֹ',
		nameAudio: '/alphabet/heb/name-tsadi-holam.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-holam.mp3',
	},
	{
		char: 'צֳ',
		nameAudio: '/alphabet/heb/name-tsadi-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-chataf-qamats.mp3',
	},
	{
		char: 'צוּ',
		nameAudio: '/alphabet/heb/name-tsadi-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-shuruk.mp3',
	},
	{
		char: 'צֻ',
		nameAudio: '/alphabet/heb/name-tsadi-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-qubutz.mp3',
	},
	{
		char: 'צַי',
		nameAudio: '/alphabet/heb/name-tsadi-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-patach-yod.mp3',
	},
	{
		char: 'ץ',
		nameAudio: '/alphabet/heb/name-tsadi sofit-base.mp3',
		soundAudio: '/alphabet/heb/sound-tsadi-base.mp3',
		imageKey: 'tsadi-sofit',
	},
	{
		char: 'ק',
		nameAudio: '/alphabet/heb/name-qof-base.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-base.mp3',
		imageKey: 'qof',
	},
	{
		char: 'קְ',
		nameAudio: '/alphabet/heb/name-qof-shva.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-base.mp3',
	},
	{
		char: 'קּ',
		nameAudio: '/alphabet/heb/name-qof-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-dagesh.mp3',
	},
	{
		char: 'קָה',
		nameAudio: '/alphabet/heb/name-qof-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-qamats-hey.mp3',
	},
	{
		char: 'קָ',
		nameAudio: '/alphabet/heb/name-qof-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-qamats.mp3',
	},
	{
		char: 'קַ',
		nameAudio: '/alphabet/heb/name-qof-patach.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-patach.mp3',
	},
	{
		char: 'קֲ',
		nameAudio: '/alphabet/heb/name-qof-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-chataf-patach.mp3',
	},
	{
		char: 'קֵי',
		nameAudio: '/alphabet/heb/name-qof-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-tsere-yod.mp3',
	},
	{
		char: 'קֵ',
		nameAudio: '/alphabet/heb/name-qof-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-tsere.mp3',
	},
	{
		char: 'קֶי',
		nameAudio: '/alphabet/heb/name-qof-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-segol-yod.mp3',
	},
	{
		char: 'קֶ',
		nameAudio: '/alphabet/heb/name-qof-segol.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-segol.mp3',
	},
	{
		char: 'קֱ',
		nameAudio: '/alphabet/heb/name-qof-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-chataf-segol.mp3',
	},
	{
		char: 'קִי',
		nameAudio: '/alphabet/heb/name-qof-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-hiriq-yod.mp3',
	},
	{
		char: 'קִ',
		nameAudio: '/alphabet/heb/name-qof-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-hiriq.mp3',
	},
	{
		char: 'קוֹ',
		nameAudio: '/alphabet/heb/name-qof-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-holam-male.mp3',
	},
	{
		char: 'קֹ',
		nameAudio: '/alphabet/heb/name-qof-holam.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-holam.mp3',
	},
	{
		char: 'קֳ',
		nameAudio: '/alphabet/heb/name-qof-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-chataf-qamats.mp3',
	},
	{
		char: 'קוּ',
		nameAudio: '/alphabet/heb/name-qof-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-shuruk.mp3',
	},
	{
		char: 'קֻ',
		nameAudio: '/alphabet/heb/name-qof-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-qubutz.mp3',
	},
	{
		char: 'קַי',
		nameAudio: '/alphabet/heb/name-qof-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-kaf-patach-yod.mp3',
	},
	{
		char: 'ר',
		nameAudio: '/alphabet/heb/name-resh-base.mp3',
		soundAudio: '/alphabet/heb/sound-resh-base.mp3',
		imageKey: 'resh',
	},
	{
		char: 'רְ',
		nameAudio: '/alphabet/heb/name-resh-shva.mp3',
		soundAudio: '/alphabet/heb/sound-resh-base.mp3',
	},
	{
		char: 'רּ',
		nameAudio: '/alphabet/heb/name-resh-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-resh-dagesh.mp3',
	},
	{
		char: 'רָה',
		nameAudio: '/alphabet/heb/name-resh-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-resh-qamats-hey.mp3',
	},
	{
		char: 'רָ',
		nameAudio: '/alphabet/heb/name-resh-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-resh-qamats.mp3',
	},
	{
		char: 'רַ',
		nameAudio: '/alphabet/heb/name-resh-patach.mp3',
		soundAudio: '/alphabet/heb/sound-resh-patach.mp3',
	},
	{
		char: 'רֲ',
		nameAudio: '/alphabet/heb/name-resh-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-resh-chataf-patach.mp3',
	},
	{
		char: 'רֵי',
		nameAudio: '/alphabet/heb/name-resh-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-resh-tsere-yod.mp3',
	},
	{
		char: 'רֵ',
		nameAudio: '/alphabet/heb/name-resh-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-resh-tsere.mp3',
	},
	{
		char: 'רֶי',
		nameAudio: '/alphabet/heb/name-resh-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-resh-segol-yod.mp3',
	},
	{
		char: 'רֶ',
		nameAudio: '/alphabet/heb/name-resh-segol.mp3',
		soundAudio: '/alphabet/heb/sound-resh-segol.mp3',
	},
	{
		char: 'רֱ',
		nameAudio: '/alphabet/heb/name-resh-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-resh-chataf-segol.mp3',
	},
	{
		char: 'רִי',
		nameAudio: '/alphabet/heb/name-resh-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-resh-hiriq-yod.mp3',
	},
	{
		char: 'רִ',
		nameAudio: '/alphabet/heb/name-resh-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-resh-hiriq.mp3',
	},
	{
		char: 'רוֹ',
		nameAudio: '/alphabet/heb/name-resh-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-resh-holam-male.mp3',
	},
	{
		char: 'רֹ',
		nameAudio: '/alphabet/heb/name-resh-holam.mp3',
		soundAudio: '/alphabet/heb/sound-resh-holam.mp3',
	},
	{
		char: 'רֳ',
		nameAudio: '/alphabet/heb/name-resh-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-resh-chataf-qamats.mp3',
	},
	{
		char: 'רוּ',
		nameAudio: '/alphabet/heb/name-resh-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-resh-shuruk.mp3',
	},
	{
		char: 'רֻ',
		nameAudio: '/alphabet/heb/name-resh-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-resh-qubutz.mp3',
	},
	{
		char: 'רַי',
		nameAudio: '/alphabet/heb/name-resh-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-resh-patach-yod.mp3',
	},
	{
		char: 'שׁ',
		nameAudio: '/alphabet/heb/name-shin-base.mp3',
		soundAudio: '/alphabet/heb/sound-shin-base.mp3',
		imageKey: 'shin',
	},
	{
		char: 'שְׁ',
		nameAudio: '/alphabet/heb/name-shin-shva.mp3',
		soundAudio: '/alphabet/heb/sound-shin-base.mp3',
	},
	{
		char: 'שּׁ',
		nameAudio: '/alphabet/heb/name-shin-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-shin-dagesh.mp3',
	},
	{
		char: 'שָׁה',
		nameAudio: '/alphabet/heb/name-shin-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-shin-qamats-hey.mp3',
	},
	{
		char: 'שָׁ',
		nameAudio: '/alphabet/heb/name-shin-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-shin-qamats.mp3',
	},
	{
		char: 'שַׁ',
		nameAudio: '/alphabet/heb/name-shin-patach.mp3',
		soundAudio: '/alphabet/heb/sound-shin-patach.mp3',
	},
	{
		char: 'שֲׁ',
		nameAudio: '/alphabet/heb/name-shin-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-shin-chataf-patach.mp3',
	},
	{
		char: 'שֵׁי',
		nameAudio: '/alphabet/heb/name-shin-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-shin-tsere-yod.mp3',
	},
	{
		char: 'שֵׁ',
		nameAudio: '/alphabet/heb/name-shin-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-shin-tsere.mp3',
	},
	{
		char: 'שֶׁי',
		nameAudio: '/alphabet/heb/name-shin-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-shin-segol-yod.mp3',
	},
	{
		char: 'שֶׁ',
		nameAudio: '/alphabet/heb/name-shin-segol.mp3',
		soundAudio: '/alphabet/heb/sound-shin-segol.mp3',
	},
	{
		char: 'שֱׁ',
		nameAudio: '/alphabet/heb/name-shin-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-shin-chataf-segol.mp3',
	},
	{
		char: 'שִׁי',
		nameAudio: '/alphabet/heb/name-shin-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-shin-hiriq-yod.mp3',
	},
	{
		char: 'שִׁ',
		nameAudio: '/alphabet/heb/name-shin-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-shin-hiriq.mp3',
	},
	{
		char: 'שׁוֹ',
		nameAudio: '/alphabet/heb/name-shin-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-shin-holam-male.mp3',
	},
	{
		char: 'שֹׁ',
		nameAudio: '/alphabet/heb/name-shin-holam.mp3',
		soundAudio: '/alphabet/heb/sound-shin-holam.mp3',
	},
	{
		char: 'שֳׁ',
		nameAudio: '/alphabet/heb/name-shin-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-shin-chataf-qamats.mp3',
	},
	{
		char: 'שׁוּ',
		nameAudio: '/alphabet/heb/name-shin-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-shin-shuruk.mp3',
	},
	{
		char: 'שֻׁ',
		nameAudio: '/alphabet/heb/name-shin-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-shin-qubutz.mp3',
	},
	{
		char: 'שַׁי',
		nameAudio: '/alphabet/heb/name-shin-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-shin-patach-yod.mp3',
	},
	{
		char: 'שׂ',
		nameAudio: '/alphabet/heb/name-sin-base.mp3',
		soundAudio: '/alphabet/heb/sound-sin-base.mp3',
	},
	{
		char: 'שְׂ',
		nameAudio: '/alphabet/heb/name-sin-shva.mp3',
		soundAudio: '/alphabet/heb/sound-sin-base.mp3',
	},
	{
		char: 'שּׂ',
		nameAudio: '/alphabet/heb/name-sin-dagesh.mp3',
		soundAudio: '/alphabet/heb/sound-sin-dagesh.mp3',
	},
	{
		char: 'שָׂה',
		nameAudio: '/alphabet/heb/name-sin-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-sin-qamats-hey.mp3',
	},
	{
		char: 'שָׂ',
		nameAudio: '/alphabet/heb/name-sin-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-sin-qamats.mp3',
	},
	{
		char: 'שַׂ',
		nameAudio: '/alphabet/heb/name-sin-patach.mp3',
		soundAudio: '/alphabet/heb/sound-sin-patach.mp3',
	},
	{
		char: 'שֲׂ',
		nameAudio: '/alphabet/heb/name-sin-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-sin-chataf-patach.mp3',
	},
	{
		char: 'שֵׂי',
		nameAudio: '/alphabet/heb/name-sin-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-sin-tsere-yod.mp3',
	},
	{
		char: 'שֵׂ',
		nameAudio: '/alphabet/heb/name-sin-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-sin-tsere.mp3',
	},
	{
		char: 'שֶׂי',
		nameAudio: '/alphabet/heb/name-sin-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-sin-segol-yod.mp3',
	},
	{
		char: 'שֶׂ',
		nameAudio: '/alphabet/heb/name-sin-segol.mp3',
		soundAudio: '/alphabet/heb/sound-sin-segol.mp3',
	},
	{
		char: 'שֱׂ',
		nameAudio: '/alphabet/heb/name-sin-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-sin-chataf-segol.mp3',
	},
	{
		char: 'שִׂי',
		nameAudio: '/alphabet/heb/name-sin-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-sin-hiriq-yod.mp3',
	},
	{
		char: 'שִׂ',
		nameAudio: '/alphabet/heb/name-sin-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-sin-hiriq.mp3',
	},
	{
		char: 'שׂוֹ',
		nameAudio: '/alphabet/heb/name-sin-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-sin-holam-male.mp3',
	},
	{
		char: 'שֹׂ',
		nameAudio: '/alphabet/heb/name-sin-holam.mp3',
		soundAudio: '/alphabet/heb/sound-sin-holam.mp3',
	},
	{
		char: 'שֳׂ',
		nameAudio: '/alphabet/heb/name-sin-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-sin-chataf-qamats.mp3',
	},
	{
		char: 'שׂוּ',
		nameAudio: '/alphabet/heb/name-sin-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-sin-shuruk.mp3',
	},
	{
		char: 'שֻׂ',
		nameAudio: '/alphabet/heb/name-sin-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-sin-qubutz.mp3',
	},
	{
		char: 'שַׂי',
		nameAudio: '/alphabet/heb/name-sin-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-sin-patach-yod.mp3',
	},
	{
		char: 'ת',
		nameAudio: '/alphabet/heb/name-thav-base.mp3',
		soundAudio: '/alphabet/heb/sound-thav-base.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-base.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-base.mp3',
	},
	{
		char: 'תְ',
		nameAudio: '/alphabet/heb/name-thav-shva.mp3',
		soundAudio: '/alphabet/heb/sound-thav-base.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-shva.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-base.mp3',
	},
	{
		char: 'תָה',
		nameAudio: '/alphabet/heb/name-thav-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-thav-qamats-hey.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-qamats-hey.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-qamats-hey.mp3',
	},
	{
		char: 'תָ',
		nameAudio: '/alphabet/heb/name-thav-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-thav-qamats.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-qamats.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-qamats.mp3',
	},
	{
		char: 'תַ',
		nameAudio: '/alphabet/heb/name-thav-patach.mp3',
		soundAudio: '/alphabet/heb/sound-thav-patach.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-patach.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-patach.mp3',
	},
	{
		char: 'תֲ',
		nameAudio: '/alphabet/heb/name-thav-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-thav-chataf-patach.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-chataf-patach.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-chataf-patach.mp3',
	},
	{
		char: 'תֵי',
		nameAudio: '/alphabet/heb/name-thav-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-thav-tsere-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-tsere-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-tsere-yod.mp3',
	},
	{
		char: 'תֵ',
		nameAudio: '/alphabet/heb/name-thav-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-thav-tsere.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-tsere.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-tsere.mp3',
	},
	{
		char: 'תֶי',
		nameAudio: '/alphabet/heb/name-thav-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-thav-segol-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-segol-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-segol-yod.mp3',
	},
	{
		char: 'תֶ',
		nameAudio: '/alphabet/heb/name-thav-segol.mp3',
		soundAudio: '/alphabet/heb/sound-thav-segol.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-segol.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-segol.mp3',
	},
	{
		char: 'תֱ',
		nameAudio: '/alphabet/heb/name-thav-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-thav-chataf-segol.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-chataf-segol.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-chataf-segol.mp3',
	},
	{
		char: 'תִי',
		nameAudio: '/alphabet/heb/name-thav-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-thav-hiriq-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-hiriq-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-hiriq-yod.mp3',
	},
	{
		char: 'תִ',
		nameAudio: '/alphabet/heb/name-thav-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-thav-hiriq.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-hiriq.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-hiriq.mp3',
	},
	{
		char: 'תוֹ',
		nameAudio: '/alphabet/heb/name-thav-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-thav-holam-male.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-holam-male.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-holam-male.mp3',
	},
	{
		char: 'תֹ',
		nameAudio: '/alphabet/heb/name-thav-holam.mp3',
		soundAudio: '/alphabet/heb/sound-thav-holam.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-holam.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-holam.mp3',
	},
	{
		char: 'תֳ',
		nameAudio: '/alphabet/heb/name-thav-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-thav-chataf-qamats.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-chataf-qamats.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-chataf-qamats.mp3',
	},
	{
		char: 'תוּ',
		nameAudio: '/alphabet/heb/name-thav-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-thav-shuruk.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-shuruk.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-shuruk.mp3',
	},
	{
		char: 'תֻ',
		nameAudio: '/alphabet/heb/name-thav-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-thav-qubutz.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-qubutz.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-qubutz.mp3',
	},
	{
		char: 'תַי',
		nameAudio: '/alphabet/heb/name-thav-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-thav-patach-yod.mp3',
		sephardicNameAudio: '/alphabet/heb/name-tav-patach-yod.mp3',
		sephardicSoundAudio: '/alphabet/heb/sound-tav-patach-yod.mp3',
	},
	{
		char: 'תּ',
		nameAudio: '/alphabet/heb/name-tav-base.mp3',
		soundAudio: '/alphabet/heb/sound-tav-base.mp3',
		imageKey: 'tav',
	},
	{
		char: 'תְּ',
		nameAudio: '/alphabet/heb/name-tav-shva.mp3',
		soundAudio: '/alphabet/heb/sound-tav-base.mp3',
	},
	{
		char: 'תָּה',
		nameAudio: '/alphabet/heb/name-tav-qamats-hey.mp3',
		soundAudio: '/alphabet/heb/sound-tav-qamats-hey.mp3',
	},
	{
		char: 'תָּ',
		nameAudio: '/alphabet/heb/name-tav-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-tav-qamats.mp3',
	},
	{
		char: 'תַּ',
		nameAudio: '/alphabet/heb/name-tav-patach.mp3',
		soundAudio: '/alphabet/heb/sound-tav-patach.mp3',
	},
	{
		char: 'תֲּ',
		nameAudio: '/alphabet/heb/name-tav-chataf-patach.mp3',
		soundAudio: '/alphabet/heb/sound-tav-chataf-patach.mp3',
	},
	{
		char: 'תֵּי',
		nameAudio: '/alphabet/heb/name-tav-tsere-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tav-tsere-yod.mp3',
	},
	{
		char: 'תֵּ',
		nameAudio: '/alphabet/heb/name-tav-tsere.mp3',
		soundAudio: '/alphabet/heb/sound-tav-tsere.mp3',
	},
	{
		char: 'תֶּי',
		nameAudio: '/alphabet/heb/name-tav-segol-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tav-segol-yod.mp3',
	},
	{
		char: 'תֶּ',
		nameAudio: '/alphabet/heb/name-tav-segol.mp3',
		soundAudio: '/alphabet/heb/sound-tav-segol.mp3',
	},
	{
		char: 'תֱּ',
		nameAudio: '/alphabet/heb/name-tav-chataf-segol.mp3',
		soundAudio: '/alphabet/heb/sound-tav-chataf-segol.mp3',
	},
	{
		char: 'תִּי',
		nameAudio: '/alphabet/heb/name-tav-hiriq-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tav-hiriq-yod.mp3',
	},
	{
		char: 'תִּ',
		nameAudio: '/alphabet/heb/name-tav-hiriq.mp3',
		soundAudio: '/alphabet/heb/sound-tav-hiriq.mp3',
	},
	{
		char: 'תּוֹ',
		nameAudio: '/alphabet/heb/name-tav-holam-male.mp3',
		soundAudio: '/alphabet/heb/sound-tav-holam-male.mp3',
	},
	{
		char: 'תֹּ',
		nameAudio: '/alphabet/heb/name-tav-holam.mp3',
		soundAudio: '/alphabet/heb/sound-tav-holam.mp3',
	},
	{
		char: 'תֳּ',
		nameAudio: '/alphabet/heb/name-tav-chataf-qamats.mp3',
		soundAudio: '/alphabet/heb/sound-tav-chataf-qamats.mp3',
	},
	{
		char: 'תּוּ',
		nameAudio: '/alphabet/heb/name-tav-shuruk.mp3',
		soundAudio: '/alphabet/heb/sound-tav-shuruk.mp3',
	},
	{
		char: 'תֻּ',
		nameAudio: '/alphabet/heb/name-tav-qubutz.mp3',
		soundAudio: '/alphabet/heb/sound-tav-qubutz.mp3',
	},
	{
		char: 'תַּי',
		nameAudio: '/alphabet/heb/name-tav-patach-yod.mp3',
		soundAudio: '/alphabet/heb/sound-tav-patach-yod.mp3',
	},
]
