// scripts/seed-events.ts
import 'dotenv/config'
import db from '@/db/drizzle'
import { events } from '@/db/schema'
import { parse } from 'date-fns'

// Paste your JSON here (or import from a file)
const raw = [
	{
		name: 'Lesson 36',
		category: 'virtual',
		startTime: '2025-07-14T12:30:00',
		recordingUrl: 'https://www.youtube.com/watch?v=1U58519kM2w&authuser=0',
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 8',
		category: 'inperson',
		startTime: '2025-07-14T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Kamats Part 3',
		category: 'inperson',
		startTime: '2025-07-14T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 24',
		category: 'inperson',
		startTime: '2025-07-14T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'ToZ Chapter 7',
		category: 'bookclub',
		startTime: '2025-07-14T19:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 37',
		category: 'virtual',
		startTime: '2025-07-21T12:30:00',
		recordingUrl: 'https://www.youtube.com/watch?v=zRSmHj8h6qI&authuser=0',
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 8',
		category: 'inperson',
		startTime: '2025-07-21T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Kamats Part 4',
		category: 'inperson',
		startTime: '2025-07-21T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 25',
		category: 'inperson',
		startTime: '2025-07-21T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'ToZ Chapter 8',
		category: 'bookclub',
		startTime: '2025-07-21T19:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 38',
		category: 'virtual',
		startTime: '2025-07-28T12:30:00',
		recordingUrl: 'https://www.youtube.com/watch?v=Wv-tq_2T9lg&authuser=0',
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 9',
		category: 'inperson',
		startTime: '2025-07-28T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Kamats Part 5',
		category: 'inperson',
		startTime: '2025-07-28T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 26',
		category: 'inperson',
		startTime: '2025-07-28T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'ToZ Chapter 9',
		category: 'bookclub',
		startTime: '2025-07-28T19:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 39',
		category: 'virtual',
		startTime: '2025-08-04T12:30:00',
		recordingUrl: 'https://www.youtube.com/watch?v=xZoZ_NRrQKI&authuser=0',
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 9',
		category: 'inperson',
		startTime: '2025-08-04T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Kamats Part 5',
		category: 'inperson',
		startTime: '2025-08-04T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 27',
		category: 'inperson',
		startTime: '2025-08-04T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'ToZ Chapter 10.1',
		category: 'bookclub',
		startTime: '2025-08-04T19:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP - Summer Break',
		category: 'virtual',
		startTime: '2025-08-11T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Kamats Testing',
		category: 'inperson',
		startTime: '2025-08-11T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #1',
		category: 'inperson',
		startTime: '2025-08-11T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 28',
		category: 'inperson',
		startTime: '2025-08-11T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Asher',
		category: 'dinner',
		startTime: '2025-08-11T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'ToZ Chapter 10.2',
		category: 'bookclub',
		startTime: '2025-08-11T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP - Summer Break',
		category: 'virtual',
		startTime: '2025-08-18T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Kamats Testing',
		category: 'inperson',
		startTime: '2025-08-18T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #1',
		category: 'inperson',
		startTime: '2025-08-18T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 29',
		category: 'inperson',
		startTime: '2025-08-18T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Zebulun',
		category: 'dinner',
		startTime: '2025-08-18T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'ToZ Chapter 10.3',
		category: 'bookclub',
		startTime: '2025-08-18T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP - Summer Break',
		category: 'virtual',
		startTime: '2025-08-25T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Patach Part 1',
		category: 'part',
		startTime: '2025-08-25T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #2',
		category: 'classroom',
		startTime: '2025-08-25T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 30',
		category: 'lesson',
		startTime: '2025-08-25T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Naphtali',
		category: 'dinner',
		startTime: '2025-08-25T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'ToZ Chapter 10.4',
		category: 'bookclub',
		startTime: '2025-08-25T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP - Summer Break',
		category: 'virtual',
		startTime: '2025-09-01T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Patach Part 2',
		category: 'part',
		startTime: '2025-09-01T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #2',
		category: 'classroom',
		startTime: '2025-09-01T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 31',
		category: 'lesson',
		startTime: '2025-09-01T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Reuben',
		category: 'dinner',
		startTime: '2025-09-01T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'S7S: Secret 1',
		category: 'secret',
		startTime: '2025-09-01T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP - Summer Break',
		category: 'virtual',
		startTime: '2025-09-08T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Patach Part 3',
		category: 'part',
		startTime: '2025-09-08T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #3',
		category: 'classroom',
		startTime: '2025-09-08T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 32',
		category: 'lesson',
		startTime: '2025-09-08T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Goyim',
		category: 'dinner',
		startTime: '2025-09-08T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'S7S: Secret 2',
		category: 'secret',
		startTime: '2025-09-08T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP - Summer Break',
		category: 'virtual',
		startTime: '2025-09-15T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Patach Part 4',
		category: 'part',
		startTime: '2025-09-15T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #3',
		category: 'classroom',
		startTime: '2025-09-15T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 33',
		category: 'lesson',
		startTime: '2025-09-15T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Asher',
		category: 'dinner',
		startTime: '2025-09-15T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'S7S: Secret 3',
		category: 'bookclub',
		startTime: '2025-09-15T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP - Summer Break',
		category: 'virtual',
		startTime: '2025-09-22T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-09-22T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-09-22T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP - Rosh Hashana Dinner',
		category: 'feast',
		startTime: '2025-09-22T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-09-22T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-09-22T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 30 Review',
		category: 'virtual',
		startTime: '2025-09-29T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Patach Part 5',
		category: 'inperson',
		startTime: '2025-09-29T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #4',
		category: 'inperson',
		startTime: '2025-09-29T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 34',
		category: 'inperson',
		startTime: '2025-09-29T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Zebulun',
		category: 'dinner',
		startTime: '2025-09-29T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'S7S: Secret 5',
		category: 'bookclub',
		startTime: '2025-09-29T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 31 Review',
		category: 'virtual',
		startTime: '2025-10-06T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Patach Testing',
		category: 'inperson',
		startTime: '2025-10-06T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #4',
		category: 'inperson',
		startTime: '2025-10-06T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 35',
		category: 'inperson',
		startTime: '2025-10-06T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Naphtali',
		category: 'dinner',
		startTime: '2025-10-06T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'S7S: Secret 6',
		category: 'bookclub',
		startTime: '2025-10-06T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 32 Review',
		category: 'virtual',
		startTime: '2025-10-13T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Patach Testing',
		category: 'inperson',
		startTime: '2025-10-13T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #5',
		category: 'inperson',
		startTime: '2025-10-13T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 36',
		category: 'inperson',
		startTime: '2025-10-13T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Reuben',
		category: 'dinner',
		startTime: '2025-10-13T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'S7S: Secret 7',
		category: 'bookclub',
		startTime: '2025-10-13T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 33 Review',
		category: 'virtual',
		startTime: '2025-10-20T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Tzeireh Part 1',
		category: 'inperson',
		startTime: '2025-10-20T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #5',
		category: 'inperson',
		startTime: '2025-10-20T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 37',
		category: 'inperson',
		startTime: '2025-10-20T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Goyim',
		category: 'dinner',
		startTime: '2025-10-20T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'LoF: Background - School of the Prophets',
		category: 'bookclub',
		startTime: '2025-10-20T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 34 Review',
		category: 'virtual',
		startTime: '2025-10-27T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Tzeireh Part 2',
		category: 'inperson',
		startTime: '2025-10-27T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #6',
		category: 'inperson',
		startTime: '2025-10-27T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 38',
		category: 'inperson',
		startTime: '2025-10-27T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Asher',
		category: 'dinner',
		startTime: '2025-10-27T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'LoF: Ordinances & Salutations',
		category: 'bookclub',
		startTime: '2025-10-27T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 35 Review',
		category: 'virtual',
		startTime: '2025-11-03T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Tzeireh Part 3',
		category: 'inperson',
		startTime: '2025-11-03T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #6',
		category: 'inperson',
		startTime: '2025-11-03T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 39',
		category: 'inperson',
		startTime: '2025-11-03T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Zebulun',
		category: 'dinner',
		startTime: '2025-11-03T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'LoF: The Word of Wisdom',
		category: 'bookclub',
		startTime: '2025-11-03T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 36 Review',
		category: 'virtual',
		startTime: '2025-11-10T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Tzeireh Part 4',
		category: 'inperson',
		startTime: '2025-11-10T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #7',
		category: 'inperson',
		startTime: '2025-11-10T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 40',
		category: 'inperson',
		startTime: '2025-11-10T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Naphtali',
		category: 'dinner',
		startTime: '2025-11-10T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'LoF: Outcomes',
		category: 'bookclub',
		startTime: '2025-11-10T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 37 Review',
		category: 'virtual',
		startTime: '2025-11-17T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Tzeireh Part 5',
		category: 'inperson',
		startTime: '2025-11-17T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #7',
		category: 'inperson',
		startTime: '2025-11-17T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 30 Review',
		category: 'inperson',
		startTime: '2025-11-17T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Reuben',
		category: 'dinner',
		startTime: '2025-11-17T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'LoF: Background and Preface',
		category: 'bookclub',
		startTime: '2025-11-17T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'virtual',
		startTime: '2025-11-24T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-11-24T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-11-24T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-11-24T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'dinner',
		startTime: '2025-11-24T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'bookclub',
		startTime: '2025-11-24T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 38 Review',
		category: 'virtual',
		startTime: '2025-12-01T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Tzeireh Testing',
		category: 'inperson',
		startTime: '2025-12-01T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #8',
		category: 'inperson',
		startTime: '2025-12-01T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 31 Review',
		category: 'inperson',
		startTime: '2025-12-01T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Goyim',
		category: 'dinner',
		startTime: '2025-12-01T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'LoF: Lecture First',
		category: 'bookclub',
		startTime: '2025-12-01T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 39 Review',
		category: 'virtual',
		startTime: '2025-12-08T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Tzeireh Testing',
		category: 'inperson',
		startTime: '2025-12-08T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #8',
		category: 'inperson',
		startTime: '2025-12-08T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 32 Review',
		category: 'inperson',
		startTime: '2025-12-08T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Asher',
		category: 'dinner',
		startTime: '2025-12-08T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'LoF: Lecture Second',
		category: 'bookclub',
		startTime: '2025-12-08T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 40',
		category: 'virtual',
		startTime: '2025-12-15T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl:
			'https://us02web.zoom.us/j/3174376398?pwd=cndPWmt0ZkRYeXdrVm5adnlZaElZQT09',
		address: null,
		notes: null,
	},
	{
		name: 'Review',
		category: 'inperson',
		startTime: '2025-12-15T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Classroom #9',
		category: 'inperson',
		startTime: '2025-12-15T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Lesson 33 Review',
		category: 'inperson',
		startTime: '2025-12-15T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'Dinner: Team Zebulun',
		category: 'dinner',
		startTime: '2025-12-15T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'LoF: Lecture Third',
		category: 'bookclub',
		startTime: '2025-12-15T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'virtual',
		startTime: '2025-12-22T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-12-22T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-12-22T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-12-22T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'dinner',
		startTime: '2025-12-22T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'bookclub',
		startTime: '2025-12-22T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'virtual',
		startTime: '2025-12-29T12:30:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-12-29T16:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-12-29T17:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'inperson',
		startTime: '2025-12-29T18:00:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'dinner',
		startTime: '2025-12-29T18:45:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
	{
		name: 'SKIP',
		category: 'bookclub',
		startTime: '2025-12-29T19:15:00',
		recordingUrl: null,
		hebName: null,
		endTime: null,
		zoomUrl: null,
		address: null,
		notes: null,
	},
]

type InsertEvent = typeof events.$inferInsert
const data: InsertEvent[] = raw.map(({ startTime, ...rest }) => ({
	...rest,
	startTime: new Date(startTime), // "2025-07-14T12:30:00" -> Date
}))

async function seed() {
	await db.insert(events).values(data)
	console.log(`✅ Seeded ${data.length} events`)
}

seed()
	.then(() => process.exit(0))
	.catch((err) => {
		console.error(err)
		process.exit(1)
	})
